/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B3BodyEvents extends NativeObject {

    private B3BodyMoveEvent B3BodyMoveEvent_TEMP_GEN_0;

    static public final B3BodyEvents NULL = B3BodyEvents.native_new();

    public B3BodyEvents() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3BodyEvents(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3BodyEvents native_new() {
        return new B3BodyEvents((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetMoveCount() {
        return internal_native_GetMoveCount(native_address);
    }

    public static int internal_native_GetMoveCount(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetMoveCount__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3BodyMoveEvent GetMoveEvent(int index) {
        long addr = internal_native_GetMoveEvent_addr(native_address, index);
        if (addr == 0)
            return B3BodyMoveEvent.NULL;
        if (B3BodyMoveEvent_TEMP_GEN_0 == null)
            B3BodyMoveEvent_TEMP_GEN_0 = B3BodyMoveEvent.native_new();
        B3BodyMoveEvent_TEMP_GEN_0.internal_reset(addr, false);
        return B3BodyMoveEvent_TEMP_GEN_0;
    }

    public static long internal_native_GetMoveEvent_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetMoveEvent_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3bodyevents_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3bodyevents_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetMoveCount__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3bodyevents_getmovecount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetMoveEvent_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3bodyevents_getmoveevent_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    }
}
