/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class B3Collision extends NativeObject {

    static private B3DistanceOutput B3DistanceOutput_TEMP_STATIC_GEN_0;

    static private B3CastOutput B3CastOutput_TEMP_STATIC_GEN_0;

    static private B3TOIOutput B3TOIOutput_TEMP_STATIC_GEN_0;

    static private B3PlaneSolverResult B3PlaneSolverResult_TEMP_STATIC_GEN_0;

    static private B3Vec3 B3Vec3_TEMP_STATIC_GEN_0;

    static public final B3Collision NULL = B3Collision.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Collision(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Collision native_new() {
        return new B3Collision((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3LocalManifold CollideSpheres(int capacity, B3Sphere sphereA, B3Sphere sphereB, B3Transform transformBtoA) {
        long addr = internal_native_CollideSpheres_addr(capacity, sphereA.native_address, sphereB.native_address, transformBtoA.native_address);
        if (addr == 0)
            return B3LocalManifold.NULL;
        B3LocalManifold B3LocalManifold_NEW = B3LocalManifold.native_new();
        B3LocalManifold_NEW.internal_reset(addr, true);
        return B3LocalManifold_NEW;
    }

    public static long internal_native_CollideSpheres_addr(int capacity, long sphereA_addr, long sphereB_addr, long transformBtoA_addr) {
        try {
            return (long) FFMHandles.internal_native_CollideSpheres_addr__IJJJ.invokeExact(capacity, sphereA_addr, sphereB_addr, transformBtoA_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3LocalManifold CollideCapsuleAndSphere(int capacity, B3Capsule capsuleA, B3Sphere sphereB, B3Transform transformBtoA) {
        long addr = internal_native_CollideCapsuleAndSphere_addr(capacity, capsuleA.native_address, sphereB.native_address, transformBtoA.native_address);
        if (addr == 0)
            return B3LocalManifold.NULL;
        B3LocalManifold B3LocalManifold_NEW = B3LocalManifold.native_new();
        B3LocalManifold_NEW.internal_reset(addr, true);
        return B3LocalManifold_NEW;
    }

    public static long internal_native_CollideCapsuleAndSphere_addr(int capacity, long capsuleA_addr, long sphereB_addr, long transformBtoA_addr) {
        try {
            return (long) FFMHandles.internal_native_CollideCapsuleAndSphere_addr__IJJJ.invokeExact(capacity, capsuleA_addr, sphereB_addr, transformBtoA_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3LocalManifold CollideHullAndSphere(int capacity, B3Hull hullA, B3Sphere sphereB, B3Transform transformBtoA) {
        long addr = internal_native_CollideHullAndSphere_addr(capacity, hullA.native_address, sphereB.native_address, transformBtoA.native_address);
        if (addr == 0)
            return B3LocalManifold.NULL;
        B3LocalManifold B3LocalManifold_NEW = B3LocalManifold.native_new();
        B3LocalManifold_NEW.internal_reset(addr, true);
        return B3LocalManifold_NEW;
    }

    public static long internal_native_CollideHullAndSphere_addr(int capacity, long hullA_addr, long sphereB_addr, long transformBtoA_addr) {
        try {
            return (long) FFMHandles.internal_native_CollideHullAndSphere_addr__IJJJ.invokeExact(capacity, hullA_addr, sphereB_addr, transformBtoA_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3LocalManifold CollideCapsules(int capacity, B3Capsule capsuleA, B3Capsule capsuleB, B3Transform transformBtoA) {
        long addr = internal_native_CollideCapsules_addr(capacity, capsuleA.native_address, capsuleB.native_address, transformBtoA.native_address);
        if (addr == 0)
            return B3LocalManifold.NULL;
        B3LocalManifold B3LocalManifold_NEW = B3LocalManifold.native_new();
        B3LocalManifold_NEW.internal_reset(addr, true);
        return B3LocalManifold_NEW;
    }

    public static long internal_native_CollideCapsules_addr(int capacity, long capsuleA_addr, long capsuleB_addr, long transformBtoA_addr) {
        try {
            return (long) FFMHandles.internal_native_CollideCapsules_addr__IJJJ.invokeExact(capacity, capsuleA_addr, capsuleB_addr, transformBtoA_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3LocalManifold CollideHullAndCapsule(int capacity, B3Hull hullA, B3Capsule capsuleB, B3Transform transformBtoA) {
        long addr = internal_native_CollideHullAndCapsule_addr(capacity, hullA.native_address, capsuleB.native_address, transformBtoA.native_address);
        if (addr == 0)
            return B3LocalManifold.NULL;
        B3LocalManifold B3LocalManifold_NEW = B3LocalManifold.native_new();
        B3LocalManifold_NEW.internal_reset(addr, true);
        return B3LocalManifold_NEW;
    }

    public static long internal_native_CollideHullAndCapsule_addr(int capacity, long hullA_addr, long capsuleB_addr, long transformBtoA_addr) {
        try {
            return (long) FFMHandles.internal_native_CollideHullAndCapsule_addr__IJJJ.invokeExact(capacity, hullA_addr, capsuleB_addr, transformBtoA_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3LocalManifold CollideHulls(int capacity, B3Hull hullA, B3Hull hullB, B3Transform transformBtoA) {
        long addr = internal_native_CollideHulls_addr(capacity, hullA.native_address, hullB.native_address, transformBtoA.native_address);
        if (addr == 0)
            return B3LocalManifold.NULL;
        B3LocalManifold B3LocalManifold_NEW = B3LocalManifold.native_new();
        B3LocalManifold_NEW.internal_reset(addr, true);
        return B3LocalManifold_NEW;
    }

    public static long internal_native_CollideHulls_addr(int capacity, long hullA_addr, long hullB_addr, long transformBtoA_addr) {
        try {
            return (long) FFMHandles.internal_native_CollideHulls_addr__IJJJ.invokeExact(capacity, hullA_addr, hullB_addr, transformBtoA_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3LocalManifold CollideTriangleAndSphere(int capacity, B3Vec3Array triangleA, B3Sphere sphereB) {
        long addr = internal_native_CollideTriangleAndSphere_addr(capacity, triangleA.native_address, sphereB.native_address);
        if (addr == 0)
            return B3LocalManifold.NULL;
        B3LocalManifold B3LocalManifold_NEW = B3LocalManifold.native_new();
        B3LocalManifold_NEW.internal_reset(addr, true);
        return B3LocalManifold_NEW;
    }

    public static long internal_native_CollideTriangleAndSphere_addr(int capacity, long triangleA_addr, long sphereB_addr) {
        try {
            return (long) FFMHandles.internal_native_CollideTriangleAndSphere_addr__IJJ.invokeExact(capacity, triangleA_addr, sphereB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3LocalManifold CollideTriangleAndCapsule(int capacity, B3Vec3Array triangleA, B3Capsule capsuleB) {
        long addr = internal_native_CollideTriangleAndCapsule_addr(capacity, triangleA.native_address, capsuleB.native_address);
        if (addr == 0)
            return B3LocalManifold.NULL;
        B3LocalManifold B3LocalManifold_NEW = B3LocalManifold.native_new();
        B3LocalManifold_NEW.internal_reset(addr, true);
        return B3LocalManifold_NEW;
    }

    public static long internal_native_CollideTriangleAndCapsule_addr(int capacity, long triangleA_addr, long capsuleB_addr) {
        try {
            return (long) FFMHandles.internal_native_CollideTriangleAndCapsule_addr__IJJ.invokeExact(capacity, triangleA_addr, capsuleB_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3LocalManifold CollideTriangleAndHull(int capacity, B3Vec3Array triangleA, int triangleFlags, B3Hull hullB, boolean enableSpeculative) {
        long addr = internal_native_CollideTriangleAndHull_addr(capacity, triangleA.native_address, triangleFlags, hullB.native_address, enableSpeculative);
        if (addr == 0)
            return B3LocalManifold.NULL;
        B3LocalManifold B3LocalManifold_NEW = B3LocalManifold.native_new();
        B3LocalManifold_NEW.internal_reset(addr, true);
        return B3LocalManifold_NEW;
    }

    public static long internal_native_CollideTriangleAndHull_addr(int capacity, long triangleA_addr, int triangleFlags, long hullB_addr, boolean enableSpeculative) {
        try {
            return (long) FFMHandles.internal_native_CollideTriangleAndHull_addr__IJIJZ.invokeExact(capacity, triangleA_addr, triangleFlags, hullB_addr, enableSpeculative);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3DistanceOutput ShapeDistance(B3ShapeProxy proxyA, B3ShapeProxy proxyB, B3Transform transformBtoA, boolean useRadii) {
        long addr = internal_native_ShapeDistance_addr(proxyA.native_address, proxyB.native_address, transformBtoA.native_address, useRadii);
        if (addr == 0)
            return B3DistanceOutput.NULL;
        if (B3DistanceOutput_TEMP_STATIC_GEN_0 == null)
            B3DistanceOutput_TEMP_STATIC_GEN_0 = B3DistanceOutput.native_new();
        B3DistanceOutput_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return B3DistanceOutput_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_ShapeDistance_addr(long proxyA_addr, long proxyB_addr, long transformBtoA_addr, boolean useRadii) {
        try {
            return (long) FFMHandles.internal_native_ShapeDistance_addr__JJJZ.invokeExact(proxyA_addr, proxyB_addr, transformBtoA_addr, useRadii);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3CastOutput ShapeCast(B3ShapeProxy proxyA, B3ShapeProxy proxyB, B3Transform transformBtoA, B3Vec3 translationB, float maxFraction, boolean canEncroach) {
        long addr = internal_native_ShapeCast_addr(proxyA.native_address, proxyB.native_address, transformBtoA.native_address, translationB.native_address, maxFraction, canEncroach);
        if (addr == 0)
            return B3CastOutput.NULL;
        if (B3CastOutput_TEMP_STATIC_GEN_0 == null)
            B3CastOutput_TEMP_STATIC_GEN_0 = B3CastOutput.native_new();
        B3CastOutput_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return B3CastOutput_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_ShapeCast_addr(long proxyA_addr, long proxyB_addr, long transformBtoA_addr, long translationB_addr, float maxFraction, boolean canEncroach) {
        try {
            return (long) FFMHandles.internal_native_ShapeCast_addr__JJJJFZ.invokeExact(proxyA_addr, proxyB_addr, transformBtoA_addr, translationB_addr, maxFraction, canEncroach);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3TOIOutput TimeOfImpact(B3ShapeProxy proxyA, B3ShapeProxy proxyB, B3Sweep sweepA, B3Sweep sweepB, float maxFraction) {
        long addr = internal_native_TimeOfImpact_addr(proxyA.native_address, proxyB.native_address, sweepA.native_address, sweepB.native_address, maxFraction);
        if (addr == 0)
            return B3TOIOutput.NULL;
        if (B3TOIOutput_TEMP_STATIC_GEN_0 == null)
            B3TOIOutput_TEMP_STATIC_GEN_0 = B3TOIOutput.native_new();
        B3TOIOutput_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return B3TOIOutput_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_TimeOfImpact_addr(long proxyA_addr, long proxyB_addr, long sweepA_addr, long sweepB_addr, float maxFraction) {
        try {
            return (long) FFMHandles.internal_native_TimeOfImpact_addr__JJJJF.invokeExact(proxyA_addr, proxyB_addr, sweepA_addr, sweepB_addr, maxFraction);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3PlaneSolverResult SolveMoverPlanes(B3Vec3 targetDelta, B3MoverCollision collision) {
        long addr = internal_native_SolveMoverPlanes_addr(targetDelta.native_address, collision.native_address);
        if (addr == 0)
            return B3PlaneSolverResult.NULL;
        if (B3PlaneSolverResult_TEMP_STATIC_GEN_0 == null)
            B3PlaneSolverResult_TEMP_STATIC_GEN_0 = B3PlaneSolverResult.native_new();
        B3PlaneSolverResult_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return B3PlaneSolverResult_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_SolveMoverPlanes_addr(long targetDelta_addr, long collision_addr) {
        try {
            return (long) FFMHandles.internal_native_SolveMoverPlanes_addr__JJ.invokeExact(targetDelta_addr, collision_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public static B3Vec3 ClipVectorToMoverPlanes(B3Vec3 vector, B3MoverCollision collision) {
        long addr = internal_native_ClipVectorToMoverPlanes_addr(vector.native_address, collision.native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_STATIC_GEN_0 == null)
            B3Vec3_TEMP_STATIC_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_STATIC_GEN_0.internal_reset(addr, false);
        return B3Vec3_TEMP_STATIC_GEN_0;
    }

    public static long internal_native_ClipVectorToMoverPlanes_addr(long vector_addr, long collision_addr) {
        try {
            return (long) FFMHandles.internal_native_ClipVectorToMoverPlanes_addr__JJ.invokeExact(vector_addr, collision_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3collision_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CollideSpheres_addr__IJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_collidespheres_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CollideCapsuleAndSphere_addr__IJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_collidecapsuleandsphere_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CollideHullAndSphere_addr__IJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_collidehullandsphere_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CollideCapsules_addr__IJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_collidecapsules_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CollideHullAndCapsule_addr__IJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_collidehullandcapsule_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CollideHulls_addr__IJJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_collidehulls_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CollideTriangleAndSphere_addr__IJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_collidetriangleandsphere_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CollideTriangleAndCapsule_addr__IJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_collidetriangleandcapsule_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_CollideTriangleAndHull_addr__IJIJZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_collidetriangleandhull_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_ShapeDistance_addr__JJJZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_shapedistance_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_ShapeCast_addr__JJJJFZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_shapecast_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_TimeOfImpact_addr__JJJJF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_timeofimpact_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_SolveMoverPlanes_addr__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_solvemoverplanes_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_ClipVectorToMoverPlanes_addr__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3collision_clipvectortomoverplanes_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
