/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class B3Matrix3 extends NativeObject {

    private B3Vec3 B3Vec3_TEMP_GEN_0;

    private B3Vec3 B3Vec3_TEMP_GEN_1;

    private B3Vec3 B3Vec3_TEMP_GEN_2;

    static public final B3Matrix3 NULL = B3Matrix3.native_new();

    public B3Matrix3() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Matrix3(B3Vec3 columnX, B3Vec3 columnY, B3Vec3 columnZ) {
        long addr = internal_native_create_B3Vec3_B3Vec3_B3Vec3_addr(columnX.native_address, columnY.native_address, columnZ.native_address);
        internal_reset(addr, true);
    }

    public static long internal_native_create_B3Vec3_B3Vec3_B3Vec3_addr(long columnX_addr, long columnY_addr, long columnZ_addr) {
        try {
            return (long) FFMHandles.internal_native_create_B3Vec3_B3Vec3_B3Vec3_addr__JJJ.invokeExact(columnX_addr, columnY_addr, columnZ_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Matrix3(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Matrix3 native_new() {
        return new B3Matrix3((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Vec3 GetColumnX() {
        long addr = internal_native_GetColumnX_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_0 == null)
            B3Vec3_TEMP_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetColumnX_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetColumnX_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetColumnX(B3Vec3 column) {
        internal_native_SetColumnX(native_address, column.native_address);
    }

    public static void internal_native_SetColumnX(long this_addr, long column_addr) {
        try {
            FFMHandles.internal_native_SetColumnX__JJ.invokeExact(this_addr, column_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Vec3 GetColumnY() {
        long addr = internal_native_GetColumnY_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_1 == null)
            B3Vec3_TEMP_GEN_1 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_1;
    }

    public static long internal_native_GetColumnY_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetColumnY_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetColumnY(B3Vec3 column) {
        internal_native_SetColumnY(native_address, column.native_address);
    }

    public static void internal_native_SetColumnY(long this_addr, long column_addr) {
        try {
            FFMHandles.internal_native_SetColumnY__JJ.invokeExact(this_addr, column_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Vec3 GetColumnZ() {
        long addr = internal_native_GetColumnZ_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_2 == null)
            B3Vec3_TEMP_GEN_2 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_2.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_2;
    }

    public static long internal_native_GetColumnZ_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetColumnZ_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetColumnZ(B3Vec3 column) {
        internal_native_SetColumnZ(native_address, column.native_address);
    }

    public static void internal_native_SetColumnZ(long this_addr, long column_addr) {
        try {
            FFMHandles.internal_native_SetColumnZ__JJ.invokeExact(this_addr, column_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3matrix3_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_B3Vec3_B3Vec3_B3Vec3_addr__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3matrix3_create_b3vec3_b3vec3_b3vec3_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3matrix3_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetColumnX_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3matrix3_getcolumnx_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetColumnX__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3matrix3_setcolumnx", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetColumnY_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3matrix3_getcolumny_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetColumnY__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3matrix3_setcolumny", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetColumnZ_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3matrix3_getcolumnz_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetColumnZ__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3matrix3_setcolumnz", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    }
}
