/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B3RevoluteJointDef extends NativeObject {

    private B3Transform B3Transform_TEMP_GEN_0;

    private B3Transform B3Transform_TEMP_GEN_1;

    static public final B3RevoluteJointDef NULL = B3RevoluteJointDef.native_new();

    public B3RevoluteJointDef() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3RevoluteJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3RevoluteJointDef native_new() {
        return new B3RevoluteJointDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetBodyIdA() {
        return internal_native_GetBodyIdA(native_address);
    }

    public static long internal_native_GetBodyIdA(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBodyIdA__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetBodyIdA(long bodyId) {
        internal_native_SetBodyIdA(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdA(long this_addr, long bodyId) {
        try {
            FFMHandles.internal_native_SetBodyIdA__JJ.invokeExact(this_addr, bodyId);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetBodyIdB() {
        return internal_native_GetBodyIdB(native_address);
    }

    public static long internal_native_GetBodyIdB(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBodyIdB__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetBodyIdB(long bodyId) {
        internal_native_SetBodyIdB(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdB(long this_addr, long bodyId) {
        try {
            FFMHandles.internal_native_SetBodyIdB__JJ.invokeExact(this_addr, bodyId);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Transform GetLocalFrameA() {
        long addr = internal_native_GetLocalFrameA_addr(native_address);
        if (addr == 0)
            return B3Transform.NULL;
        if (B3Transform_TEMP_GEN_0 == null)
            B3Transform_TEMP_GEN_0 = B3Transform.native_new();
        B3Transform_TEMP_GEN_0.internal_reset(addr, false);
        return B3Transform_TEMP_GEN_0;
    }

    public static long internal_native_GetLocalFrameA_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalFrameA_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLocalFrameA(B3Transform transform) {
        internal_native_SetLocalFrameA(native_address, transform.native_address);
    }

    public static void internal_native_SetLocalFrameA(long this_addr, long transform_addr) {
        try {
            FFMHandles.internal_native_SetLocalFrameA__JJ.invokeExact(this_addr, transform_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Transform GetLocalFrameB() {
        long addr = internal_native_GetLocalFrameB_addr(native_address);
        if (addr == 0)
            return B3Transform.NULL;
        if (B3Transform_TEMP_GEN_1 == null)
            B3Transform_TEMP_GEN_1 = B3Transform.native_new();
        B3Transform_TEMP_GEN_1.internal_reset(addr, false);
        return B3Transform_TEMP_GEN_1;
    }

    public static long internal_native_GetLocalFrameB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalFrameB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLocalFrameB(B3Transform transform) {
        internal_native_SetLocalFrameB(native_address, transform.native_address);
    }

    public static void internal_native_SetLocalFrameB(long this_addr, long transform_addr) {
        try {
            FFMHandles.internal_native_SetLocalFrameB__JJ.invokeExact(this_addr, transform_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLocalPositionA(B3Vec3 position) {
        internal_native_SetLocalPositionA(native_address, position.native_address);
    }

    public static void internal_native_SetLocalPositionA(long this_addr, long position_addr) {
        try {
            FFMHandles.internal_native_SetLocalPositionA__JJ.invokeExact(this_addr, position_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLocalPositionB(B3Vec3 position) {
        internal_native_SetLocalPositionB(native_address, position.native_address);
    }

    public static void internal_native_SetLocalPositionB(long this_addr, long position_addr) {
        try {
            FFMHandles.internal_native_SetLocalPositionB__JJ.invokeExact(this_addr, position_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetDrawScale() {
        return internal_native_GetDrawScale(native_address);
    }

    public static float internal_native_GetDrawScale(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetDrawScale__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawScale(float scale) {
        internal_native_SetDrawScale(native_address, scale);
    }

    public static void internal_native_SetDrawScale(long this_addr, float scale) {
        try {
            FFMHandles.internal_native_SetDrawScale__JF.invokeExact(this_addr, scale);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetCollideConnected() {
        return internal_native_GetCollideConnected(native_address);
    }

    public static boolean internal_native_GetCollideConnected(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetCollideConnected__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetCollideConnected(boolean collide) {
        internal_native_SetCollideConnected(native_address, collide);
    }

    public static void internal_native_SetCollideConnected(long this_addr, boolean collide) {
        try {
            FFMHandles.internal_native_SetCollideConnected__JZ.invokeExact(this_addr, collide);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetConstraintHertz() {
        return internal_native_GetConstraintHertz(native_address);
    }

    public static float internal_native_GetConstraintHertz(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetConstraintHertz__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetConstraintHertz(float hertz) {
        internal_native_SetConstraintHertz(native_address, hertz);
    }

    public static void internal_native_SetConstraintHertz(long this_addr, float hertz) {
        try {
            FFMHandles.internal_native_SetConstraintHertz__JF.invokeExact(this_addr, hertz);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetConstraintDampingRatio() {
        return internal_native_GetConstraintDampingRatio(native_address);
    }

    public static float internal_native_GetConstraintDampingRatio(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetConstraintDampingRatio__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetConstraintDampingRatio(float ratio) {
        internal_native_SetConstraintDampingRatio(native_address, ratio);
    }

    public static void internal_native_SetConstraintDampingRatio(long this_addr, float ratio) {
        try {
            FFMHandles.internal_native_SetConstraintDampingRatio__JF.invokeExact(this_addr, ratio);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetTargetAngle() {
        return internal_native_GetTargetAngle(native_address);
    }

    public static float internal_native_GetTargetAngle(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetTargetAngle__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetTargetAngle(float radians) {
        internal_native_SetTargetAngle(native_address, radians);
    }

    public static void internal_native_SetTargetAngle(long this_addr, float radians) {
        try {
            FFMHandles.internal_native_SetTargetAngle__JF.invokeExact(this_addr, radians);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableSpring() {
        return internal_native_GetEnableSpring(native_address);
    }

    public static boolean internal_native_GetEnableSpring(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableSpring__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableSpring(boolean enabled) {
        internal_native_SetEnableSpring(native_address, enabled);
    }

    public static void internal_native_SetEnableSpring(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableSpring__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetHertz() {
        return internal_native_GetHertz(native_address);
    }

    public static float internal_native_GetHertz(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetHertz__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetHertz(float hertz) {
        internal_native_SetHertz(native_address, hertz);
    }

    public static void internal_native_SetHertz(long this_addr, float hertz) {
        try {
            FFMHandles.internal_native_SetHertz__JF.invokeExact(this_addr, hertz);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetDampingRatio() {
        return internal_native_GetDampingRatio(native_address);
    }

    public static float internal_native_GetDampingRatio(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetDampingRatio__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDampingRatio(float ratio) {
        internal_native_SetDampingRatio(native_address, ratio);
    }

    public static void internal_native_SetDampingRatio(long this_addr, float ratio) {
        try {
            FFMHandles.internal_native_SetDampingRatio__JF.invokeExact(this_addr, ratio);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableLimit() {
        return internal_native_GetEnableLimit(native_address);
    }

    public static boolean internal_native_GetEnableLimit(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableLimit__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableLimit(boolean enabled) {
        internal_native_SetEnableLimit(native_address, enabled);
    }

    public static void internal_native_SetEnableLimit(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableLimit__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetLowerAngle() {
        return internal_native_GetLowerAngle(native_address);
    }

    public static float internal_native_GetLowerAngle(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetLowerAngle__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLowerAngle(float radians) {
        internal_native_SetLowerAngle(native_address, radians);
    }

    public static void internal_native_SetLowerAngle(long this_addr, float radians) {
        try {
            FFMHandles.internal_native_SetLowerAngle__JF.invokeExact(this_addr, radians);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetUpperAngle() {
        return internal_native_GetUpperAngle(native_address);
    }

    public static float internal_native_GetUpperAngle(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetUpperAngle__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetUpperAngle(float radians) {
        internal_native_SetUpperAngle(native_address, radians);
    }

    public static void internal_native_SetUpperAngle(long this_addr, float radians) {
        try {
            FFMHandles.internal_native_SetUpperAngle__JF.invokeExact(this_addr, radians);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableMotor() {
        return internal_native_GetEnableMotor(native_address);
    }

    public static boolean internal_native_GetEnableMotor(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableMotor__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableMotor(boolean enabled) {
        internal_native_SetEnableMotor(native_address, enabled);
    }

    public static void internal_native_SetEnableMotor(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableMotor__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetMaxMotorTorque() {
        return internal_native_GetMaxMotorTorque(native_address);
    }

    public static float internal_native_GetMaxMotorTorque(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetMaxMotorTorque__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMaxMotorTorque(float torque) {
        internal_native_SetMaxMotorTorque(native_address, torque);
    }

    public static void internal_native_SetMaxMotorTorque(long this_addr, float torque) {
        try {
            FFMHandles.internal_native_SetMaxMotorTorque__JF.invokeExact(this_addr, torque);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetMotorSpeed() {
        return internal_native_GetMotorSpeed(native_address);
    }

    public static float internal_native_GetMotorSpeed(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetMotorSpeed__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMotorSpeed(float speed) {
        internal_native_SetMotorSpeed(native_address, speed);
    }

    public static void internal_native_SetMotorSpeed(long this_addr, float speed) {
        try {
            FFMHandles.internal_native_SetMotorSpeed__JF.invokeExact(this_addr, speed);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3revolutejointdef_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBodyIdA__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getbodyida", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBodyIdA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setbodyida", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBodyIdB__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getbodyidb", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBodyIdB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setbodyidb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalFrameA_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3revolutejointdef_getlocalframea_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLocalFrameA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setlocalframea", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalFrameB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3revolutejointdef_getlocalframeb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLocalFrameB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setlocalframeb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLocalPositionA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setlocalpositiona", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLocalPositionB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setlocalpositionb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawScale__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getdrawscale", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawScale__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setdrawscale", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetCollideConnected__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getcollideconnected", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetCollideConnected__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setcollideconnected", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetConstraintHertz__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getconstrainthertz", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetConstraintHertz__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setconstrainthertz", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetConstraintDampingRatio__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getconstraintdampingratio", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetConstraintDampingRatio__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setconstraintdampingratio", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetTargetAngle__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_gettargetangle", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetTargetAngle__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_settargetangle", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableSpring__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getenablespring", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableSpring__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setenablespring", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetHertz__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_gethertz", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetHertz__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_sethertz", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetDampingRatio__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getdampingratio", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDampingRatio__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setdampingratio", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableLimit__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getenablelimit", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableLimit__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setenablelimit", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetLowerAngle__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getlowerangle", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLowerAngle__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setlowerangle", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetUpperAngle__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getupperangle", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetUpperAngle__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setupperangle", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableMotor__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getenablemotor", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableMotor__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setenablemotor", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetMaxMotorTorque__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getmaxmotortorque", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMaxMotorTorque__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setmaxmotortorque", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetMotorSpeed__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_getmotorspeed", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMotorSpeed__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3revolutejointdef_setmotorspeed", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));
    }
}
