/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B3Shape extends NativeObject {

    private B3Filter B3Filter_TEMP_GEN_0;

    private B3RayResult B3RayResult_TEMP_GEN_0;

    private B3Sphere B3Sphere_TEMP_GEN_0;

    private B3Capsule B3Capsule_TEMP_GEN_0;

    private B3AABB B3AABB_TEMP_GEN_0;

    private B3Vec3 B3Vec3_TEMP_GEN_0;

    static public final B3Shape NULL = B3Shape.native_new();

    public B3Shape() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Shape(long shapeId) {
        long addr = internal_native_create_long_addr(shapeId);
        internal_reset(addr, true);
    }

    public static long internal_native_create_long_addr(long shapeId) {
        try {
            return (long) FFMHandles.internal_native_create_long_addr__J.invokeExact(shapeId);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Shape(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Shape native_new() {
        return new B3Shape((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetId() {
        return internal_native_GetId(native_address);
    }

    public static long internal_native_GetId(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetId__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsValid() {
        return internal_native_IsValid(native_address);
    }

    public static boolean internal_native_IsValid(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsValid__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void Destroy(boolean updateBodyMass) {
        internal_native_Destroy(native_address, updateBodyMass);
    }

    public static void internal_native_Destroy(long this_addr, boolean updateBodyMass) {
        try {
            FFMHandles.internal_native_Destroy__JZ.invokeExact(this_addr, updateBodyMass);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetType() {
        return internal_native_GetType(native_address);
    }

    public static int internal_native_GetType(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetType__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetBodyId() {
        return internal_native_GetBodyId(native_address);
    }

    public static long internal_native_GetBodyId(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBodyId__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean IsSensor() {
        return internal_native_IsSensor(native_address);
    }

    public static boolean internal_native_IsSensor(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_IsSensor__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetDensity() {
        return internal_native_GetDensity(native_address);
    }

    public static float internal_native_GetDensity(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetDensity__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDensity(float density, boolean updateBodyMass) {
        internal_native_SetDensity(native_address, density, updateBodyMass);
    }

    public static void internal_native_SetDensity(long this_addr, float density, boolean updateBodyMass) {
        try {
            FFMHandles.internal_native_SetDensity__JFZ.invokeExact(this_addr, density, updateBodyMass);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetFriction() {
        return internal_native_GetFriction(native_address);
    }

    public static float internal_native_GetFriction(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetFriction__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetFriction(float friction) {
        internal_native_SetFriction(native_address, friction);
    }

    public static void internal_native_SetFriction(long this_addr, float friction) {
        try {
            FFMHandles.internal_native_SetFriction__JF.invokeExact(this_addr, friction);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetRestitution() {
        return internal_native_GetRestitution(native_address);
    }

    public static float internal_native_GetRestitution(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetRestitution__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetRestitution(float restitution) {
        internal_native_SetRestitution(native_address, restitution);
    }

    public static void internal_native_SetRestitution(long this_addr, float restitution) {
        try {
            FFMHandles.internal_native_SetRestitution__JF.invokeExact(this_addr, restitution);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Filter GetFilter() {
        long addr = internal_native_GetFilter_addr(native_address);
        if (addr == 0)
            return B3Filter.NULL;
        if (B3Filter_TEMP_GEN_0 == null)
            B3Filter_TEMP_GEN_0 = B3Filter.native_new();
        B3Filter_TEMP_GEN_0.internal_reset(addr, false);
        return B3Filter_TEMP_GEN_0;
    }

    public static long internal_native_GetFilter_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetFilter_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetFilter(B3Filter filter, boolean invokeContacts) {
        internal_native_SetFilter(native_address, filter.native_address, invokeContacts);
    }

    public static void internal_native_SetFilter(long this_addr, long filter_addr, boolean invokeContacts) {
        try {
            FFMHandles.internal_native_SetFilter__JJZ.invokeExact(this_addr, filter_addr, invokeContacts);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void EnableSensorEvents(boolean enabled) {
        internal_native_EnableSensorEvents(native_address, enabled);
    }

    public static void internal_native_EnableSensorEvents(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_EnableSensorEvents__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean AreSensorEventsEnabled() {
        return internal_native_AreSensorEventsEnabled(native_address);
    }

    public static boolean internal_native_AreSensorEventsEnabled(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_AreSensorEventsEnabled__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void EnableContactEvents(boolean enabled) {
        internal_native_EnableContactEvents(native_address, enabled);
    }

    public static void internal_native_EnableContactEvents(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_EnableContactEvents__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean AreContactEventsEnabled() {
        return internal_native_AreContactEventsEnabled(native_address);
    }

    public static boolean internal_native_AreContactEventsEnabled(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_AreContactEventsEnabled__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void EnableHitEvents(boolean enabled) {
        internal_native_EnableHitEvents(native_address, enabled);
    }

    public static void internal_native_EnableHitEvents(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_EnableHitEvents__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean AreHitEventsEnabled() {
        return internal_native_AreHitEventsEnabled(native_address);
    }

    public static boolean internal_native_AreHitEventsEnabled(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_AreHitEventsEnabled__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3RayResult RayCast(B3Vec3 origin, B3Vec3 translation) {
        long addr = internal_native_RayCast_addr(native_address, origin.native_address, translation.native_address);
        if (addr == 0)
            return B3RayResult.NULL;
        if (B3RayResult_TEMP_GEN_0 == null)
            B3RayResult_TEMP_GEN_0 = B3RayResult.native_new();
        B3RayResult_TEMP_GEN_0.internal_reset(addr, false);
        return B3RayResult_TEMP_GEN_0;
    }

    public static long internal_native_RayCast_addr(long this_addr, long origin_addr, long translation_addr) {
        try {
            return (long) FFMHandles.internal_native_RayCast_addr__JJJ.invokeExact(this_addr, origin_addr, translation_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Sphere GetSphere() {
        long addr = internal_native_GetSphere_addr(native_address);
        if (addr == 0)
            return B3Sphere.NULL;
        if (B3Sphere_TEMP_GEN_0 == null)
            B3Sphere_TEMP_GEN_0 = B3Sphere.native_new();
        B3Sphere_TEMP_GEN_0.internal_reset(addr, false);
        return B3Sphere_TEMP_GEN_0;
    }

    public static long internal_native_GetSphere_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetSphere_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetSphere(B3Sphere sphere) {
        internal_native_SetSphere(native_address, sphere.native_address);
    }

    public static void internal_native_SetSphere(long this_addr, long sphere_addr) {
        try {
            FFMHandles.internal_native_SetSphere__JJ.invokeExact(this_addr, sphere_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Capsule GetCapsule() {
        long addr = internal_native_GetCapsule_addr(native_address);
        if (addr == 0)
            return B3Capsule.NULL;
        if (B3Capsule_TEMP_GEN_0 == null)
            B3Capsule_TEMP_GEN_0 = B3Capsule.native_new();
        B3Capsule_TEMP_GEN_0.internal_reset(addr, false);
        return B3Capsule_TEMP_GEN_0;
    }

    public static long internal_native_GetCapsule_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetCapsule_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetCapsule(B3Capsule capsule) {
        internal_native_SetCapsule(native_address, capsule.native_address);
    }

    public static void internal_native_SetCapsule(long this_addr, long capsule_addr) {
        try {
            FFMHandles.internal_native_SetCapsule__JJ.invokeExact(this_addr, capsule_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3AABB GetAABB() {
        long addr = internal_native_GetAABB_addr(native_address);
        if (addr == 0)
            return B3AABB.NULL;
        if (B3AABB_TEMP_GEN_0 == null)
            B3AABB_TEMP_GEN_0 = B3AABB.native_new();
        B3AABB_TEMP_GEN_0.internal_reset(addr, false);
        return B3AABB_TEMP_GEN_0;
    }

    public static long internal_native_GetAABB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetAABB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Vec3 GetClosestPoint(B3Vec3 target) {
        long addr = internal_native_GetClosestPoint_addr(native_address, target.native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_0 == null)
            B3Vec3_TEMP_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetClosestPoint_addr(long this_addr, long target_addr) {
        try {
            return (long) FFMHandles.internal_native_GetClosestPoint_addr__JJ.invokeExact(this_addr, target_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void ApplyWind(B3Vec3 wind, float drag, float lift, float maxSpeed, boolean wake) {
        internal_native_ApplyWind(native_address, wind.native_address, drag, lift, maxSpeed, wake);
    }

    public static void internal_native_ApplyWind(long this_addr, long wind_addr, float drag, float lift, float maxSpeed, boolean wake) {
        try {
            FFMHandles.internal_native_ApplyWind__JJFFFZ.invokeExact(this_addr, wind_addr, drag, lift, maxSpeed, wake);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3shape_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_create_long_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3shape_create_long_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetId__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_getid", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_IsValid__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_isvalid", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_Destroy__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_destroy", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetType__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_gettype", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBodyId__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_getbodyid", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_IsSensor__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_issensor", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetDensity__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_getdensity", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDensity__JFZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_setdensity", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetFriction__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_getfriction", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetFriction__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_setfriction", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetRestitution__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_getrestitution", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetRestitution__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_setrestitution", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetFilter_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3shape_getfilter_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetFilter__JJZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_setfilter", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_EnableSensorEvents__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_enablesensorevents", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_AreSensorEventsEnabled__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_aresensoreventsenabled", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_EnableContactEvents__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_enablecontactevents", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_AreContactEventsEnabled__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_arecontacteventsenabled", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_EnableHitEvents__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_enablehitevents", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_AreHitEventsEnabled__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_arehiteventsenabled", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_RayCast_addr__JJJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3shape_raycast_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetSphere_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3shape_getsphere_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetSphere__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_setsphere", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetCapsule_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3shape_getcapsule_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetCapsule__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_setcapsule", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetAABB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3shape_getaabb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetClosestPoint_addr__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3shape_getclosestpoint_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_ApplyWind__JJFFFZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3shape_applywind", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_BOOLEAN));
    }
}
