/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public final class B3SurfaceMaterialArray extends NativeObject {

    private B3SurfaceMaterial B3SurfaceMaterial_TEMP_GEN_0;

    static public final B3SurfaceMaterialArray NULL = B3SurfaceMaterialArray.native_new();

    public B3SurfaceMaterialArray(int size) {
        long addr = internal_native_create_int_addr(size);
        internal_reset(addr, true);
    }

    public static long internal_native_create_int_addr(int size) {
        try {
            return (long) FFMHandles.internal_native_create_int_addr__I.invokeExact(size);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3SurfaceMaterialArray(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3SurfaceMaterialArray native_new() {
        return new B3SurfaceMaterialArray((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public int GetSize() {
        return internal_native_GetSize(native_address);
    }

    public static int internal_native_GetSize(long this_addr) {
        try {
            return (int) FFMHandles.internal_native_GetSize__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3SurfaceMaterial GetValue(int index) {
        long addr = internal_native_GetValue_addr(native_address, index);
        if (addr == 0)
            return B3SurfaceMaterial.NULL;
        if (B3SurfaceMaterial_TEMP_GEN_0 == null)
            B3SurfaceMaterial_TEMP_GEN_0 = B3SurfaceMaterial.native_new();
        B3SurfaceMaterial_TEMP_GEN_0.internal_reset(addr, false);
        return B3SurfaceMaterial_TEMP_GEN_0;
    }

    public static long internal_native_GetValue_addr(long this_addr, int index) {
        try {
            return (long) FFMHandles.internal_native_GetValue_addr__JI.invokeExact(this_addr, index);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetValue(int index, B3SurfaceMaterial material) {
        internal_native_SetValue(native_address, index, material.native_address);
    }

    public static void internal_native_SetValue(long this_addr, int index, long material_addr) {
        try {
            FFMHandles.internal_native_SetValue__JIJ.invokeExact(this_addr, index, material_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_int_addr__I = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3surfacematerialarray_create_int_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3surfacematerialarray_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetSize__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3surfacematerialarray_getsize", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetValue_addr__JI = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3surfacematerialarray_getvalue_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));

        static final java.lang.invoke.MethodHandle internal_native_SetValue__JIJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3surfacematerialarray_setvalue", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    }
}
