/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.ValueLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

public class B3WheelJointDef extends NativeObject {

    private B3Transform B3Transform_TEMP_GEN_0;

    private B3Transform B3Transform_TEMP_GEN_1;

    static public final B3WheelJointDef NULL = B3WheelJointDef.native_new();

    public B3WheelJointDef() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        try {
            return (long) FFMHandles.internal_native_create_addr__.invokeExact();
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3WheelJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3WheelJointDef native_new() {
        return new B3WheelJointDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        try {
            FFMHandles.internal_native_deleteNative__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetBodyIdA() {
        return internal_native_GetBodyIdA(native_address);
    }

    public static long internal_native_GetBodyIdA(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBodyIdA__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetBodyIdA(long bodyId) {
        internal_native_SetBodyIdA(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdA(long this_addr, long bodyId) {
        try {
            FFMHandles.internal_native_SetBodyIdA__JJ.invokeExact(this_addr, bodyId);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public long GetBodyIdB() {
        return internal_native_GetBodyIdB(native_address);
    }

    public static long internal_native_GetBodyIdB(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetBodyIdB__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetBodyIdB(long bodyId) {
        internal_native_SetBodyIdB(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdB(long this_addr, long bodyId) {
        try {
            FFMHandles.internal_native_SetBodyIdB__JJ.invokeExact(this_addr, bodyId);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Transform GetLocalFrameA() {
        long addr = internal_native_GetLocalFrameA_addr(native_address);
        if (addr == 0)
            return B3Transform.NULL;
        if (B3Transform_TEMP_GEN_0 == null)
            B3Transform_TEMP_GEN_0 = B3Transform.native_new();
        B3Transform_TEMP_GEN_0.internal_reset(addr, false);
        return B3Transform_TEMP_GEN_0;
    }

    public static long internal_native_GetLocalFrameA_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalFrameA_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLocalFrameA(B3Transform transform) {
        internal_native_SetLocalFrameA(native_address, transform.native_address);
    }

    public static void internal_native_SetLocalFrameA(long this_addr, long transform_addr) {
        try {
            FFMHandles.internal_native_SetLocalFrameA__JJ.invokeExact(this_addr, transform_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public B3Transform GetLocalFrameB() {
        long addr = internal_native_GetLocalFrameB_addr(native_address);
        if (addr == 0)
            return B3Transform.NULL;
        if (B3Transform_TEMP_GEN_1 == null)
            B3Transform_TEMP_GEN_1 = B3Transform.native_new();
        B3Transform_TEMP_GEN_1.internal_reset(addr, false);
        return B3Transform_TEMP_GEN_1;
    }

    public static long internal_native_GetLocalFrameB_addr(long this_addr) {
        try {
            return (long) FFMHandles.internal_native_GetLocalFrameB_addr__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLocalFrameB(B3Transform transform) {
        internal_native_SetLocalFrameB(native_address, transform.native_address);
    }

    public static void internal_native_SetLocalFrameB(long this_addr, long transform_addr) {
        try {
            FFMHandles.internal_native_SetLocalFrameB__JJ.invokeExact(this_addr, transform_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLocalPositionA(B3Vec3 position) {
        internal_native_SetLocalPositionA(native_address, position.native_address);
    }

    public static void internal_native_SetLocalPositionA(long this_addr, long position_addr) {
        try {
            FFMHandles.internal_native_SetLocalPositionA__JJ.invokeExact(this_addr, position_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLocalPositionB(B3Vec3 position) {
        internal_native_SetLocalPositionB(native_address, position.native_address);
    }

    public static void internal_native_SetLocalPositionB(long this_addr, long position_addr) {
        try {
            FFMHandles.internal_native_SetLocalPositionB__JJ.invokeExact(this_addr, position_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetDrawScale() {
        return internal_native_GetDrawScale(native_address);
    }

    public static float internal_native_GetDrawScale(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetDrawScale__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetDrawScale(float scale) {
        internal_native_SetDrawScale(native_address, scale);
    }

    public static void internal_native_SetDrawScale(long this_addr, float scale) {
        try {
            FFMHandles.internal_native_SetDrawScale__JF.invokeExact(this_addr, scale);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetCollideConnected() {
        return internal_native_GetCollideConnected(native_address);
    }

    public static boolean internal_native_GetCollideConnected(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetCollideConnected__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetCollideConnected(boolean collide) {
        internal_native_SetCollideConnected(native_address, collide);
    }

    public static void internal_native_SetCollideConnected(long this_addr, boolean collide) {
        try {
            FFMHandles.internal_native_SetCollideConnected__JZ.invokeExact(this_addr, collide);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableSuspensionSpring() {
        return internal_native_GetEnableSuspensionSpring(native_address);
    }

    public static boolean internal_native_GetEnableSuspensionSpring(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableSuspensionSpring__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableSuspensionSpring(boolean enabled) {
        internal_native_SetEnableSuspensionSpring(native_address, enabled);
    }

    public static void internal_native_SetEnableSuspensionSpring(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableSuspensionSpring__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetSuspensionHertz() {
        return internal_native_GetSuspensionHertz(native_address);
    }

    public static float internal_native_GetSuspensionHertz(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetSuspensionHertz__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetSuspensionHertz(float hertz) {
        internal_native_SetSuspensionHertz(native_address, hertz);
    }

    public static void internal_native_SetSuspensionHertz(long this_addr, float hertz) {
        try {
            FFMHandles.internal_native_SetSuspensionHertz__JF.invokeExact(this_addr, hertz);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetSuspensionDampingRatio() {
        return internal_native_GetSuspensionDampingRatio(native_address);
    }

    public static float internal_native_GetSuspensionDampingRatio(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetSuspensionDampingRatio__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetSuspensionDampingRatio(float ratio) {
        internal_native_SetSuspensionDampingRatio(native_address, ratio);
    }

    public static void internal_native_SetSuspensionDampingRatio(long this_addr, float ratio) {
        try {
            FFMHandles.internal_native_SetSuspensionDampingRatio__JF.invokeExact(this_addr, ratio);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableSuspensionLimit() {
        return internal_native_GetEnableSuspensionLimit(native_address);
    }

    public static boolean internal_native_GetEnableSuspensionLimit(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableSuspensionLimit__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableSuspensionLimit(boolean enabled) {
        internal_native_SetEnableSuspensionLimit(native_address, enabled);
    }

    public static void internal_native_SetEnableSuspensionLimit(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableSuspensionLimit__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetLowerSuspensionLimit() {
        return internal_native_GetLowerSuspensionLimit(native_address);
    }

    public static float internal_native_GetLowerSuspensionLimit(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetLowerSuspensionLimit__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLowerSuspensionLimit(float limit) {
        internal_native_SetLowerSuspensionLimit(native_address, limit);
    }

    public static void internal_native_SetLowerSuspensionLimit(long this_addr, float limit) {
        try {
            FFMHandles.internal_native_SetLowerSuspensionLimit__JF.invokeExact(this_addr, limit);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetUpperSuspensionLimit() {
        return internal_native_GetUpperSuspensionLimit(native_address);
    }

    public static float internal_native_GetUpperSuspensionLimit(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetUpperSuspensionLimit__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetUpperSuspensionLimit(float limit) {
        internal_native_SetUpperSuspensionLimit(native_address, limit);
    }

    public static void internal_native_SetUpperSuspensionLimit(long this_addr, float limit) {
        try {
            FFMHandles.internal_native_SetUpperSuspensionLimit__JF.invokeExact(this_addr, limit);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableSpinMotor() {
        return internal_native_GetEnableSpinMotor(native_address);
    }

    public static boolean internal_native_GetEnableSpinMotor(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableSpinMotor__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableSpinMotor(boolean enabled) {
        internal_native_SetEnableSpinMotor(native_address, enabled);
    }

    public static void internal_native_SetEnableSpinMotor(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableSpinMotor__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetMaxSpinTorque() {
        return internal_native_GetMaxSpinTorque(native_address);
    }

    public static float internal_native_GetMaxSpinTorque(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetMaxSpinTorque__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMaxSpinTorque(float torque) {
        internal_native_SetMaxSpinTorque(native_address, torque);
    }

    public static void internal_native_SetMaxSpinTorque(long this_addr, float torque) {
        try {
            FFMHandles.internal_native_SetMaxSpinTorque__JF.invokeExact(this_addr, torque);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetSpinSpeed() {
        return internal_native_GetSpinSpeed(native_address);
    }

    public static float internal_native_GetSpinSpeed(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetSpinSpeed__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetSpinSpeed(float speed) {
        internal_native_SetSpinSpeed(native_address, speed);
    }

    public static void internal_native_SetSpinSpeed(long this_addr, float speed) {
        try {
            FFMHandles.internal_native_SetSpinSpeed__JF.invokeExact(this_addr, speed);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableSteering() {
        return internal_native_GetEnableSteering(native_address);
    }

    public static boolean internal_native_GetEnableSteering(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableSteering__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableSteering(boolean enabled) {
        internal_native_SetEnableSteering(native_address, enabled);
    }

    public static void internal_native_SetEnableSteering(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableSteering__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetSteeringHertz() {
        return internal_native_GetSteeringHertz(native_address);
    }

    public static float internal_native_GetSteeringHertz(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetSteeringHertz__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetSteeringHertz(float hertz) {
        internal_native_SetSteeringHertz(native_address, hertz);
    }

    public static void internal_native_SetSteeringHertz(long this_addr, float hertz) {
        try {
            FFMHandles.internal_native_SetSteeringHertz__JF.invokeExact(this_addr, hertz);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetSteeringDampingRatio() {
        return internal_native_GetSteeringDampingRatio(native_address);
    }

    public static float internal_native_GetSteeringDampingRatio(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetSteeringDampingRatio__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetSteeringDampingRatio(float ratio) {
        internal_native_SetSteeringDampingRatio(native_address, ratio);
    }

    public static void internal_native_SetSteeringDampingRatio(long this_addr, float ratio) {
        try {
            FFMHandles.internal_native_SetSteeringDampingRatio__JF.invokeExact(this_addr, ratio);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetTargetSteeringAngle() {
        return internal_native_GetTargetSteeringAngle(native_address);
    }

    public static float internal_native_GetTargetSteeringAngle(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetTargetSteeringAngle__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetTargetSteeringAngle(float radians) {
        internal_native_SetTargetSteeringAngle(native_address, radians);
    }

    public static void internal_native_SetTargetSteeringAngle(long this_addr, float radians) {
        try {
            FFMHandles.internal_native_SetTargetSteeringAngle__JF.invokeExact(this_addr, radians);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetMaxSteeringTorque() {
        return internal_native_GetMaxSteeringTorque(native_address);
    }

    public static float internal_native_GetMaxSteeringTorque(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetMaxSteeringTorque__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetMaxSteeringTorque(float torque) {
        internal_native_SetMaxSteeringTorque(native_address, torque);
    }

    public static void internal_native_SetMaxSteeringTorque(long this_addr, float torque) {
        try {
            FFMHandles.internal_native_SetMaxSteeringTorque__JF.invokeExact(this_addr, torque);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public boolean GetEnableSteeringLimit() {
        return internal_native_GetEnableSteeringLimit(native_address);
    }

    public static boolean internal_native_GetEnableSteeringLimit(long this_addr) {
        try {
            return (boolean) FFMHandles.internal_native_GetEnableSteeringLimit__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetEnableSteeringLimit(boolean enabled) {
        internal_native_SetEnableSteeringLimit(native_address, enabled);
    }

    public static void internal_native_SetEnableSteeringLimit(long this_addr, boolean enabled) {
        try {
            FFMHandles.internal_native_SetEnableSteeringLimit__JZ.invokeExact(this_addr, enabled);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetLowerSteeringLimit() {
        return internal_native_GetLowerSteeringLimit(native_address);
    }

    public static float internal_native_GetLowerSteeringLimit(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetLowerSteeringLimit__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetLowerSteeringLimit(float radians) {
        internal_native_SetLowerSteeringLimit(native_address, radians);
    }

    public static void internal_native_SetLowerSteeringLimit(long this_addr, float radians) {
        try {
            FFMHandles.internal_native_SetLowerSteeringLimit__JF.invokeExact(this_addr, radians);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public float GetUpperSteeringLimit() {
        return internal_native_GetUpperSteeringLimit(native_address);
    }

    public static float internal_native_GetUpperSteeringLimit(long this_addr) {
        try {
            return (float) FFMHandles.internal_native_GetUpperSteeringLimit__J.invokeExact(this_addr);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    public void SetUpperSteeringLimit(float radians) {
        internal_native_SetUpperSteeringLimit(native_address, radians);
    }

    public static void internal_native_SetUpperSteeringLimit(long this_addr, float radians) {
        try {
            FFMHandles.internal_native_SetUpperSteeringLimit__JF.invokeExact(this_addr, radians);
        } catch (Throwable e) {
            throw com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.rethrow(e);
        }
    }

    private static final class FFMHandles {

        static final java.lang.invoke.MethodHandle internal_native_create_addr__ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3wheeljointdef_create_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_deleteNative__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_deletenative", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBodyIdA__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getbodyida", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBodyIdA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setbodyida", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetBodyIdB__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getbodyidb", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetBodyIdB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setbodyidb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalFrameA_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3wheeljointdef_getlocalframea_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLocalFrameA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setlocalframea", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetLocalFrameB_addr__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallCritical("com_github_xpenatan_box3d_b3wheeljointdef_getlocalframeb_addr", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLocalFrameB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setlocalframeb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLocalPositionA__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setlocalpositiona", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLocalPositionB__JJ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setlocalpositionb", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_GetDrawScale__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getdrawscale", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetDrawScale__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setdrawscale", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetCollideConnected__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getcollideconnected", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetCollideConnected__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setcollideconnected", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableSuspensionSpring__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getenablesuspensionspring", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableSuspensionSpring__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setenablesuspensionspring", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetSuspensionHertz__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getsuspensionhertz", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetSuspensionHertz__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setsuspensionhertz", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetSuspensionDampingRatio__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getsuspensiondampingratio", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetSuspensionDampingRatio__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setsuspensiondampingratio", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableSuspensionLimit__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getenablesuspensionlimit", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableSuspensionLimit__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setenablesuspensionlimit", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetLowerSuspensionLimit__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getlowersuspensionlimit", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLowerSuspensionLimit__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setlowersuspensionlimit", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetUpperSuspensionLimit__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getuppersuspensionlimit", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetUpperSuspensionLimit__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setuppersuspensionlimit", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableSpinMotor__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getenablespinmotor", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableSpinMotor__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setenablespinmotor", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetMaxSpinTorque__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getmaxspintorque", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMaxSpinTorque__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setmaxspintorque", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetSpinSpeed__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getspinspeed", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetSpinSpeed__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setspinspeed", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableSteering__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getenablesteering", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableSteering__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setenablesteering", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetSteeringHertz__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getsteeringhertz", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetSteeringHertz__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setsteeringhertz", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetSteeringDampingRatio__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getsteeringdampingratio", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetSteeringDampingRatio__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setsteeringdampingratio", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetTargetSteeringAngle__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_gettargetsteeringangle", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetTargetSteeringAngle__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_settargetsteeringangle", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetMaxSteeringTorque__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getmaxsteeringtorque", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetMaxSteeringTorque__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setmaxsteeringtorque", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetEnableSteeringLimit__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getenablesteeringlimit", FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetEnableSteeringLimit__JZ = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setenablesteeringlimit", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));

        static final java.lang.invoke.MethodHandle internal_native_GetLowerSteeringLimit__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getlowersteeringlimit", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetLowerSteeringLimit__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setlowersteeringlimit", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));

        static final java.lang.invoke.MethodHandle internal_native_GetUpperSteeringLimit__J = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_getuppersteeringlimit", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.JAVA_LONG));

        static final java.lang.invoke.MethodHandle internal_native_SetUpperSteeringLimit__JF = com.github.xpenatan.jparser.runtime.helper.FFMDowncallHelper.downcallDefault("com_github_xpenatan_box3d_b3wheeljointdef_setuppersteeringlimit", FunctionDescriptor.ofVoid(ValueLayout.JAVA_LONG, ValueLayout.JAVA_FLOAT));
    }
}
