/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3 extends NativeObject {

    static public final B3 NULL = B3.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3 native_new() {
        return new B3((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3.internal_native_deleteNative(this_addr);
    }

    public static int StaticBody() {
        return internal_native_StaticBody();
    }

    public static int internal_native_StaticBody() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_StaticBody();
    }

    public static int KinematicBody() {
        return internal_native_KinematicBody();
    }

    public static int internal_native_KinematicBody() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_KinematicBody();
    }

    public static int DynamicBody() {
        return internal_native_DynamicBody();
    }

    public static int internal_native_DynamicBody() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_DynamicBody();
    }

    public static int CapsuleShape() {
        return internal_native_CapsuleShape();
    }

    public static int internal_native_CapsuleShape() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_CapsuleShape();
    }

    public static int CompoundShape() {
        return internal_native_CompoundShape();
    }

    public static int internal_native_CompoundShape() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_CompoundShape();
    }

    public static int HeightShape() {
        return internal_native_HeightShape();
    }

    public static int internal_native_HeightShape() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_HeightShape();
    }

    public static int HullShape() {
        return internal_native_HullShape();
    }

    public static int internal_native_HullShape() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_HullShape();
    }

    public static int MeshShape() {
        return internal_native_MeshShape();
    }

    public static int internal_native_MeshShape() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_MeshShape();
    }

    public static int SphereShape() {
        return internal_native_SphereShape();
    }

    public static int internal_native_SphereShape() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_SphereShape();
    }

    public static int GetWorldCount() {
        return internal_native_GetWorldCount();
    }

    public static int internal_native_GetWorldCount() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_GetWorldCount();
    }

    public static int GetMaxWorldCount() {
        return internal_native_GetMaxWorldCount();
    }

    public static int internal_native_GetMaxWorldCount() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_GetMaxWorldCount();
    }

    public static long DefaultMaskBits() {
        return internal_native_DefaultMaskBits();
    }

    public static long internal_native_DefaultMaskBits() {
        return com.github.xpenatan.box3d.natives.JNI_B3.internal_native_DefaultMaskBits();
    }
}
