/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3BodyDef extends NativeObject {

    private B3Vec3 B3Vec3_TEMP_GEN_0;

    private B3Quat B3Quat_TEMP_GEN_0;

    private B3Vec3 B3Vec3_TEMP_GEN_1;

    private B3Vec3 B3Vec3_TEMP_GEN_2;

    private B3MotionLocks B3MotionLocks_TEMP_GEN_0;

    static public final B3BodyDef NULL = B3BodyDef.native_new();

    public B3BodyDef() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3BodyDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3BodyDef native_new() {
        return new B3BodyDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_deleteNative(this_addr);
    }

    public int GetType() {
        return internal_native_GetType(native_address);
    }

    public static int internal_native_GetType(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetType(this_addr);
    }

    public void SetType(int type) {
        internal_native_SetType(native_address, type);
    }

    public static void internal_native_SetType(long this_addr, int type) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetType(this_addr, type);
    }

    public B3Vec3 GetPosition() {
        long addr = internal_native_GetPosition_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_0 == null)
            B3Vec3_TEMP_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetPosition_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetPosition_addr(this_addr);
    }

    public void SetPosition(B3Vec3 position) {
        internal_native_SetPosition(native_address, position.native_address);
    }

    public static void internal_native_SetPosition(long this_addr, long position_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetPosition(this_addr, position_addr);
    }

    public B3Quat GetRotation() {
        long addr = internal_native_GetRotation_addr(native_address);
        if (addr == 0)
            return B3Quat.NULL;
        if (B3Quat_TEMP_GEN_0 == null)
            B3Quat_TEMP_GEN_0 = B3Quat.native_new();
        B3Quat_TEMP_GEN_0.internal_reset(addr, false);
        return B3Quat_TEMP_GEN_0;
    }

    public static long internal_native_GetRotation_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetRotation_addr(this_addr);
    }

    public void SetRotation(B3Quat rotation) {
        internal_native_SetRotation(native_address, rotation.native_address);
    }

    public static void internal_native_SetRotation(long this_addr, long rotation_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetRotation(this_addr, rotation_addr);
    }

    public B3Vec3 GetLinearVelocity() {
        long addr = internal_native_GetLinearVelocity_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_1 == null)
            B3Vec3_TEMP_GEN_1 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_1;
    }

    public static long internal_native_GetLinearVelocity_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetLinearVelocity_addr(this_addr);
    }

    public void SetLinearVelocity(B3Vec3 velocity) {
        internal_native_SetLinearVelocity(native_address, velocity.native_address);
    }

    public static void internal_native_SetLinearVelocity(long this_addr, long velocity_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetLinearVelocity(this_addr, velocity_addr);
    }

    public B3Vec3 GetAngularVelocity() {
        long addr = internal_native_GetAngularVelocity_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_2 == null)
            B3Vec3_TEMP_GEN_2 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_2.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_2;
    }

    public static long internal_native_GetAngularVelocity_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetAngularVelocity_addr(this_addr);
    }

    public void SetAngularVelocity(B3Vec3 velocity) {
        internal_native_SetAngularVelocity(native_address, velocity.native_address);
    }

    public static void internal_native_SetAngularVelocity(long this_addr, long velocity_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetAngularVelocity(this_addr, velocity_addr);
    }

    public float GetLinearDamping() {
        return internal_native_GetLinearDamping(native_address);
    }

    public static float internal_native_GetLinearDamping(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetLinearDamping(this_addr);
    }

    public void SetLinearDamping(float damping) {
        internal_native_SetLinearDamping(native_address, damping);
    }

    public static void internal_native_SetLinearDamping(long this_addr, float damping) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetLinearDamping(this_addr, damping);
    }

    public float GetAngularDamping() {
        return internal_native_GetAngularDamping(native_address);
    }

    public static float internal_native_GetAngularDamping(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetAngularDamping(this_addr);
    }

    public void SetAngularDamping(float damping) {
        internal_native_SetAngularDamping(native_address, damping);
    }

    public static void internal_native_SetAngularDamping(long this_addr, float damping) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetAngularDamping(this_addr, damping);
    }

    public float GetGravityScale() {
        return internal_native_GetGravityScale(native_address);
    }

    public static float internal_native_GetGravityScale(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetGravityScale(this_addr);
    }

    public void SetGravityScale(float scale) {
        internal_native_SetGravityScale(native_address, scale);
    }

    public static void internal_native_SetGravityScale(long this_addr, float scale) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetGravityScale(this_addr, scale);
    }

    public float GetSleepThreshold() {
        return internal_native_GetSleepThreshold(native_address);
    }

    public static float internal_native_GetSleepThreshold(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetSleepThreshold(this_addr);
    }

    public void SetSleepThreshold(float threshold) {
        internal_native_SetSleepThreshold(native_address, threshold);
    }

    public static void internal_native_SetSleepThreshold(long this_addr, float threshold) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetSleepThreshold(this_addr, threshold);
    }

    public B3MotionLocks GetMotionLocks() {
        long addr = internal_native_GetMotionLocks_addr(native_address);
        if (addr == 0)
            return B3MotionLocks.NULL;
        if (B3MotionLocks_TEMP_GEN_0 == null)
            B3MotionLocks_TEMP_GEN_0 = B3MotionLocks.native_new();
        B3MotionLocks_TEMP_GEN_0.internal_reset(addr, false);
        return B3MotionLocks_TEMP_GEN_0;
    }

    public static long internal_native_GetMotionLocks_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetMotionLocks_addr(this_addr);
    }

    public void SetMotionLocks(B3MotionLocks locks) {
        internal_native_SetMotionLocks(native_address, locks.native_address);
    }

    public static void internal_native_SetMotionLocks(long this_addr, long locks_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetMotionLocks(this_addr, locks_addr);
    }

    public boolean GetEnableSleep() {
        return internal_native_GetEnableSleep(native_address);
    }

    public static boolean internal_native_GetEnableSleep(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetEnableSleep(this_addr);
    }

    public void SetEnableSleep(boolean enabled) {
        internal_native_SetEnableSleep(native_address, enabled);
    }

    public static void internal_native_SetEnableSleep(long this_addr, boolean enabled) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetEnableSleep(this_addr, enabled);
    }

    public boolean GetIsAwake() {
        return internal_native_GetIsAwake(native_address);
    }

    public static boolean internal_native_GetIsAwake(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetIsAwake(this_addr);
    }

    public void SetIsAwake(boolean awake) {
        internal_native_SetIsAwake(native_address, awake);
    }

    public static void internal_native_SetIsAwake(long this_addr, boolean awake) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetIsAwake(this_addr, awake);
    }

    public boolean GetIsBullet() {
        return internal_native_GetIsBullet(native_address);
    }

    public static boolean internal_native_GetIsBullet(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetIsBullet(this_addr);
    }

    public void SetIsBullet(boolean bullet) {
        internal_native_SetIsBullet(native_address, bullet);
    }

    public static void internal_native_SetIsBullet(long this_addr, boolean bullet) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetIsBullet(this_addr, bullet);
    }

    public boolean GetIsEnabled() {
        return internal_native_GetIsEnabled(native_address);
    }

    public static boolean internal_native_GetIsEnabled(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetIsEnabled(this_addr);
    }

    public void SetIsEnabled(boolean enabled) {
        internal_native_SetIsEnabled(native_address, enabled);
    }

    public static void internal_native_SetIsEnabled(long this_addr, boolean enabled) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetIsEnabled(this_addr, enabled);
    }

    public boolean GetAllowFastRotation() {
        return internal_native_GetAllowFastRotation(native_address);
    }

    public static boolean internal_native_GetAllowFastRotation(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetAllowFastRotation(this_addr);
    }

    public void SetAllowFastRotation(boolean allowFastRotation) {
        internal_native_SetAllowFastRotation(native_address, allowFastRotation);
    }

    public static void internal_native_SetAllowFastRotation(long this_addr, boolean allowFastRotation) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetAllowFastRotation(this_addr, allowFastRotation);
    }

    public boolean GetEnableContactRecycling() {
        return internal_native_GetEnableContactRecycling(native_address);
    }

    public static boolean internal_native_GetEnableContactRecycling(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_GetEnableContactRecycling(this_addr);
    }

    public void SetEnableContactRecycling(boolean enableContactRecycling) {
        internal_native_SetEnableContactRecycling(native_address, enableContactRecycling);
    }

    public static void internal_native_SetEnableContactRecycling(long this_addr, boolean enableContactRecycling) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyDef.internal_native_SetEnableContactRecycling(this_addr, enableContactRecycling);
    }
}
