/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3BodyMoveEvent extends NativeObject {

    private B3Transform B3Transform_TEMP_GEN_0;

    static public final B3BodyMoveEvent NULL = B3BodyMoveEvent.native_new();

    public B3BodyMoveEvent() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyMoveEvent.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3BodyMoveEvent(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3BodyMoveEvent native_new() {
        return new B3BodyMoveEvent((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3BodyMoveEvent.internal_native_deleteNative(this_addr);
    }

    public long GetBodyId() {
        return internal_native_GetBodyId(native_address);
    }

    public static long internal_native_GetBodyId(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyMoveEvent.internal_native_GetBodyId(this_addr);
    }

    public B3Transform GetTransform() {
        long addr = internal_native_GetTransform_addr(native_address);
        if (addr == 0)
            return B3Transform.NULL;
        if (B3Transform_TEMP_GEN_0 == null)
            B3Transform_TEMP_GEN_0 = B3Transform.native_new();
        B3Transform_TEMP_GEN_0.internal_reset(addr, false);
        return B3Transform_TEMP_GEN_0;
    }

    public static long internal_native_GetTransform_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyMoveEvent.internal_native_GetTransform_addr(this_addr);
    }

    public boolean GetFellAsleep() {
        return internal_native_GetFellAsleep(native_address);
    }

    public static boolean internal_native_GetFellAsleep(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3BodyMoveEvent.internal_native_GetFellAsleep(this_addr);
    }
}
