/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3Body extends NativeObject {

    private B3Vec3 B3Vec3_TEMP_GEN_0;

    private B3Quat B3Quat_TEMP_GEN_0;

    private B3Transform B3Transform_TEMP_GEN_0;

    private B3Vec3 B3Vec3_TEMP_GEN_1;

    private B3Vec3 B3Vec3_TEMP_GEN_2;

    private B3Vec3 B3Vec3_TEMP_GEN_3;

    private B3Vec3 B3Vec3_TEMP_GEN_4;

    private B3Vec3 B3Vec3_TEMP_GEN_5;

    private B3Vec3 B3Vec3_TEMP_GEN_6;

    private B3Vec3 B3Vec3_TEMP_GEN_7;

    private B3RayResult B3RayResult_TEMP_GEN_0;

    private B3MotionLocks B3MotionLocks_TEMP_GEN_0;

    private B3AABB B3AABB_TEMP_GEN_0;

    static public final B3Body NULL = B3Body.native_new();

    public B3Body() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_create_addr();
    }

    public B3Body(long bodyId) {
        long addr = internal_native_create_long_addr(bodyId);
        internal_reset(addr, true);
    }

    public static long internal_native_create_long_addr(long bodyId) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_create_long_addr(bodyId);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Body(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Body native_new() {
        return new B3Body((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_deleteNative(this_addr);
    }

    public long GetId() {
        return internal_native_GetId(native_address);
    }

    public static long internal_native_GetId(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetId(this_addr);
    }

    public boolean IsValid() {
        return internal_native_IsValid(native_address);
    }

    public static boolean internal_native_IsValid(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_IsValid(this_addr);
    }

    public void Destroy() {
        internal_native_Destroy(native_address);
    }

    public static void internal_native_Destroy(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_Destroy(this_addr);
    }

    public int GetType() {
        return internal_native_GetType(native_address);
    }

    public static int internal_native_GetType(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetType(this_addr);
    }

    public void SetType(int type) {
        internal_native_SetType(native_address, type);
    }

    public static void internal_native_SetType(long this_addr, int type) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetType(this_addr, type);
    }

    public B3Vec3 GetPosition() {
        long addr = internal_native_GetPosition_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_0 == null)
            B3Vec3_TEMP_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetPosition_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetPosition_addr(this_addr);
    }

    public B3Quat GetRotation() {
        long addr = internal_native_GetRotation_addr(native_address);
        if (addr == 0)
            return B3Quat.NULL;
        if (B3Quat_TEMP_GEN_0 == null)
            B3Quat_TEMP_GEN_0 = B3Quat.native_new();
        B3Quat_TEMP_GEN_0.internal_reset(addr, false);
        return B3Quat_TEMP_GEN_0;
    }

    public static long internal_native_GetRotation_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetRotation_addr(this_addr);
    }

    public B3Transform GetTransform() {
        long addr = internal_native_GetTransform_addr(native_address);
        if (addr == 0)
            return B3Transform.NULL;
        if (B3Transform_TEMP_GEN_0 == null)
            B3Transform_TEMP_GEN_0 = B3Transform.native_new();
        B3Transform_TEMP_GEN_0.internal_reset(addr, false);
        return B3Transform_TEMP_GEN_0;
    }

    public static long internal_native_GetTransform_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetTransform_addr(this_addr);
    }

    public B3Vec3 GetWorldCenter() {
        long addr = internal_native_GetWorldCenter_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_1 == null)
            B3Vec3_TEMP_GEN_1 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_1;
    }

    public static long internal_native_GetWorldCenter_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetWorldCenter_addr(this_addr);
    }

    public B3Vec3 GetLocalPoint(B3Vec3 worldPoint) {
        long addr = internal_native_GetLocalPoint_addr(native_address, worldPoint.native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_2 == null)
            B3Vec3_TEMP_GEN_2 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_2.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_2;
    }

    public static long internal_native_GetLocalPoint_addr(long this_addr, long worldPoint_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetLocalPoint_addr(this_addr, worldPoint_addr);
    }

    public void SetTransform(B3Vec3 position, B3Quat rotation) {
        internal_native_SetTransform(native_address, position.native_address, rotation.native_address);
    }

    public static void internal_native_SetTransform(long this_addr, long position_addr, long rotation_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetTransform(this_addr, position_addr, rotation_addr);
    }

    public void SetTargetTransform(B3Vec3 position, B3Quat rotation, float timeStep, boolean wake) {
        internal_native_SetTargetTransform(native_address, position.native_address, rotation.native_address, timeStep, wake);
    }

    public static void internal_native_SetTargetTransform(long this_addr, long position_addr, long rotation_addr, float timeStep, boolean wake) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetTargetTransform(this_addr, position_addr, rotation_addr, timeStep, wake);
    }

    public B3Vec3 GetLinearVelocity() {
        long addr = internal_native_GetLinearVelocity_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_3 == null)
            B3Vec3_TEMP_GEN_3 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_3.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_3;
    }

    public static long internal_native_GetLinearVelocity_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetLinearVelocity_addr(this_addr);
    }

    public void SetLinearVelocity(B3Vec3 velocity) {
        internal_native_SetLinearVelocity(native_address, velocity.native_address);
    }

    public static void internal_native_SetLinearVelocity(long this_addr, long velocity_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetLinearVelocity(this_addr, velocity_addr);
    }

    public B3Vec3 GetAngularVelocity() {
        long addr = internal_native_GetAngularVelocity_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_4 == null)
            B3Vec3_TEMP_GEN_4 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_4.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_4;
    }

    public static long internal_native_GetAngularVelocity_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetAngularVelocity_addr(this_addr);
    }

    public void SetAngularVelocity(B3Vec3 velocity) {
        internal_native_SetAngularVelocity(native_address, velocity.native_address);
    }

    public static void internal_native_SetAngularVelocity(long this_addr, long velocity_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetAngularVelocity(this_addr, velocity_addr);
    }

    public void ApplyForce(B3Vec3 force, B3Vec3 point, boolean wake) {
        internal_native_ApplyForce(native_address, force.native_address, point.native_address, wake);
    }

    public static void internal_native_ApplyForce(long this_addr, long force_addr, long point_addr, boolean wake) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_ApplyForce(this_addr, force_addr, point_addr, wake);
    }

    public void ApplyForceToCenter(B3Vec3 force, boolean wake) {
        internal_native_ApplyForceToCenter(native_address, force.native_address, wake);
    }

    public static void internal_native_ApplyForceToCenter(long this_addr, long force_addr, boolean wake) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_ApplyForceToCenter(this_addr, force_addr, wake);
    }

    public void ApplyTorque(B3Vec3 torque, boolean wake) {
        internal_native_ApplyTorque(native_address, torque.native_address, wake);
    }

    public static void internal_native_ApplyTorque(long this_addr, long torque_addr, boolean wake) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_ApplyTorque(this_addr, torque_addr, wake);
    }

    public void ApplyLinearImpulse(B3Vec3 impulse, B3Vec3 point, boolean wake) {
        internal_native_ApplyLinearImpulse(native_address, impulse.native_address, point.native_address, wake);
    }

    public static void internal_native_ApplyLinearImpulse(long this_addr, long impulse_addr, long point_addr, boolean wake) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_ApplyLinearImpulse(this_addr, impulse_addr, point_addr, wake);
    }

    public void ApplyLinearImpulseToCenter(B3Vec3 impulse, boolean wake) {
        internal_native_ApplyLinearImpulseToCenter(native_address, impulse.native_address, wake);
    }

    public static void internal_native_ApplyLinearImpulseToCenter(long this_addr, long impulse_addr, boolean wake) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_ApplyLinearImpulseToCenter(this_addr, impulse_addr, wake);
    }

    public void ApplyAngularImpulse(B3Vec3 impulse, boolean wake) {
        internal_native_ApplyAngularImpulse(native_address, impulse.native_address, wake);
    }

    public static void internal_native_ApplyAngularImpulse(long this_addr, long impulse_addr, boolean wake) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_ApplyAngularImpulse(this_addr, impulse_addr, wake);
    }

    public float GetMass() {
        return internal_native_GetMass(native_address);
    }

    public static float internal_native_GetMass(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetMass(this_addr);
    }

    public float GetInverseMass() {
        return internal_native_GetInverseMass(native_address);
    }

    public static float internal_native_GetInverseMass(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetInverseMass(this_addr);
    }

    public void ApplyMassFromShapes() {
        internal_native_ApplyMassFromShapes(native_address);
    }

    public static void internal_native_ApplyMassFromShapes(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_ApplyMassFromShapes(this_addr);
    }

    public B3Vec3 GetLocalRotationalInertiaColumnX() {
        long addr = internal_native_GetLocalRotationalInertiaColumnX_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_5 == null)
            B3Vec3_TEMP_GEN_5 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_5.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_5;
    }

    public static long internal_native_GetLocalRotationalInertiaColumnX_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetLocalRotationalInertiaColumnX_addr(this_addr);
    }

    public B3Vec3 GetLocalRotationalInertiaColumnY() {
        long addr = internal_native_GetLocalRotationalInertiaColumnY_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_6 == null)
            B3Vec3_TEMP_GEN_6 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_6.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_6;
    }

    public static long internal_native_GetLocalRotationalInertiaColumnY_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetLocalRotationalInertiaColumnY_addr(this_addr);
    }

    public B3Vec3 GetLocalRotationalInertiaColumnZ() {
        long addr = internal_native_GetLocalRotationalInertiaColumnZ_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_7 == null)
            B3Vec3_TEMP_GEN_7 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_7.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_7;
    }

    public static long internal_native_GetLocalRotationalInertiaColumnZ_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetLocalRotationalInertiaColumnZ_addr(this_addr);
    }

    public void SetMassData(float mass, B3Vec3 center, B3Vec3 inertiaColumnX, B3Vec3 inertiaColumnY, B3Vec3 inertiaColumnZ) {
        internal_native_SetMassData(native_address, mass, center.native_address, inertiaColumnX.native_address, inertiaColumnY.native_address, inertiaColumnZ.native_address);
    }

    public static void internal_native_SetMassData(long this_addr, float mass, long center_addr, long inertiaColumnX_addr, long inertiaColumnY_addr, long inertiaColumnZ_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetMassData(this_addr, mass, center_addr, inertiaColumnX_addr, inertiaColumnY_addr, inertiaColumnZ_addr);
    }

    public float GetLinearDamping() {
        return internal_native_GetLinearDamping(native_address);
    }

    public static float internal_native_GetLinearDamping(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetLinearDamping(this_addr);
    }

    public void SetLinearDamping(float damping) {
        internal_native_SetLinearDamping(native_address, damping);
    }

    public static void internal_native_SetLinearDamping(long this_addr, float damping) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetLinearDamping(this_addr, damping);
    }

    public float GetAngularDamping() {
        return internal_native_GetAngularDamping(native_address);
    }

    public static float internal_native_GetAngularDamping(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetAngularDamping(this_addr);
    }

    public void SetAngularDamping(float damping) {
        internal_native_SetAngularDamping(native_address, damping);
    }

    public static void internal_native_SetAngularDamping(long this_addr, float damping) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetAngularDamping(this_addr, damping);
    }

    public float GetGravityScale() {
        return internal_native_GetGravityScale(native_address);
    }

    public static float internal_native_GetGravityScale(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetGravityScale(this_addr);
    }

    public void SetGravityScale(float scale) {
        internal_native_SetGravityScale(native_address, scale);
    }

    public static void internal_native_SetGravityScale(long this_addr, float scale) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetGravityScale(this_addr, scale);
    }

    public boolean IsAwake() {
        return internal_native_IsAwake(native_address);
    }

    public static boolean internal_native_IsAwake(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_IsAwake(this_addr);
    }

    public void SetAwake(boolean awake) {
        internal_native_SetAwake(native_address, awake);
    }

    public static void internal_native_SetAwake(long this_addr, boolean awake) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetAwake(this_addr, awake);
    }

    public B3RayResult CastRay(B3Vec3 origin, B3Vec3 translation, B3QueryFilter filter, float maxFraction, B3Transform bodyTransform) {
        long addr = internal_native_CastRay_addr(native_address, origin.native_address, translation.native_address, filter.native_address, maxFraction, bodyTransform.native_address);
        if (addr == 0)
            return B3RayResult.NULL;
        if (B3RayResult_TEMP_GEN_0 == null)
            B3RayResult_TEMP_GEN_0 = B3RayResult.native_new();
        B3RayResult_TEMP_GEN_0.internal_reset(addr, false);
        return B3RayResult_TEMP_GEN_0;
    }

    public static long internal_native_CastRay_addr(long this_addr, long origin_addr, long translation_addr, long filter_addr, float maxFraction, long bodyTransform_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_CastRay_addr(this_addr, origin_addr, translation_addr, filter_addr, maxFraction, bodyTransform_addr);
    }

    public boolean IsEnabled() {
        return internal_native_IsEnabled(native_address);
    }

    public static boolean internal_native_IsEnabled(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_IsEnabled(this_addr);
    }

    public void Disable() {
        internal_native_Disable(native_address);
    }

    public static void internal_native_Disable(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_Disable(this_addr);
    }

    public void Enable() {
        internal_native_Enable(native_address);
    }

    public static void internal_native_Enable(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_Enable(this_addr);
    }

    public B3MotionLocks GetMotionLocks() {
        long addr = internal_native_GetMotionLocks_addr(native_address);
        if (addr == 0)
            return B3MotionLocks.NULL;
        if (B3MotionLocks_TEMP_GEN_0 == null)
            B3MotionLocks_TEMP_GEN_0 = B3MotionLocks.native_new();
        B3MotionLocks_TEMP_GEN_0.internal_reset(addr, false);
        return B3MotionLocks_TEMP_GEN_0;
    }

    public static long internal_native_GetMotionLocks_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetMotionLocks_addr(this_addr);
    }

    public void SetMotionLocks(B3MotionLocks locks) {
        internal_native_SetMotionLocks(native_address, locks.native_address);
    }

    public static void internal_native_SetMotionLocks(long this_addr, long locks_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetMotionLocks(this_addr, locks_addr);
    }

    public boolean IsBullet() {
        return internal_native_IsBullet(native_address);
    }

    public static boolean internal_native_IsBullet(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_IsBullet(this_addr);
    }

    public void SetBullet(boolean bullet) {
        internal_native_SetBullet(native_address, bullet);
    }

    public static void internal_native_SetBullet(long this_addr, boolean bullet) {
        com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_SetBullet(this_addr, bullet);
    }

    public int GetShapeCount() {
        return internal_native_GetShapeCount(native_address);
    }

    public static int internal_native_GetShapeCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_GetShapeCount(this_addr);
    }

    public B3AABB ComputeAABB() {
        long addr = internal_native_ComputeAABB_addr(native_address);
        if (addr == 0)
            return B3AABB.NULL;
        if (B3AABB_TEMP_GEN_0 == null)
            B3AABB_TEMP_GEN_0 = B3AABB.native_new();
        B3AABB_TEMP_GEN_0.internal_reset(addr, false);
        return B3AABB_TEMP_GEN_0;
    }

    public static long internal_native_ComputeAABB_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_ComputeAABB_addr(this_addr);
    }

    public B3Shape CreateSphereShape(B3ShapeDef def, B3Sphere sphere) {
        long addr = internal_native_CreateSphereShape_addr(native_address, def.native_address, sphere.native_address);
        if (addr == 0)
            return B3Shape.NULL;
        B3Shape B3Shape_NEW = B3Shape.native_new();
        B3Shape_NEW.internal_reset(addr, true);
        return B3Shape_NEW;
    }

    public static long internal_native_CreateSphereShape_addr(long this_addr, long def_addr, long sphere_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_CreateSphereShape_addr(this_addr, def_addr, sphere_addr);
    }

    public B3Shape CreateCapsuleShape(B3ShapeDef def, B3Capsule capsule) {
        long addr = internal_native_CreateCapsuleShape_addr(native_address, def.native_address, capsule.native_address);
        if (addr == 0)
            return B3Shape.NULL;
        B3Shape B3Shape_NEW = B3Shape.native_new();
        B3Shape_NEW.internal_reset(addr, true);
        return B3Shape_NEW;
    }

    public static long internal_native_CreateCapsuleShape_addr(long this_addr, long def_addr, long capsule_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_CreateCapsuleShape_addr(this_addr, def_addr, capsule_addr);
    }

    public B3Shape CreateHullShape(B3ShapeDef def, B3Hull hull) {
        long addr = internal_native_CreateHullShape_addr(native_address, def.native_address, hull.native_address);
        if (addr == 0)
            return B3Shape.NULL;
        B3Shape B3Shape_NEW = B3Shape.native_new();
        B3Shape_NEW.internal_reset(addr, true);
        return B3Shape_NEW;
    }

    public static long internal_native_CreateHullShape_addr(long this_addr, long def_addr, long hull_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_CreateHullShape_addr(this_addr, def_addr, hull_addr);
    }

    public B3Shape CreateTransformedHullShape(B3ShapeDef def, B3Hull hull, B3Transform transform, B3Vec3 scale) {
        long addr = internal_native_CreateTransformedHullShape_addr(native_address, def.native_address, hull.native_address, transform.native_address, scale.native_address);
        if (addr == 0)
            return B3Shape.NULL;
        B3Shape B3Shape_NEW = B3Shape.native_new();
        B3Shape_NEW.internal_reset(addr, true);
        return B3Shape_NEW;
    }

    public static long internal_native_CreateTransformedHullShape_addr(long this_addr, long def_addr, long hull_addr, long transform_addr, long scale_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_CreateTransformedHullShape_addr(this_addr, def_addr, hull_addr, transform_addr, scale_addr);
    }

    public B3Shape CreateMeshShape(B3ShapeDef def, B3Mesh mesh, B3Vec3 scale) {
        long addr = internal_native_CreateMeshShape_addr(native_address, def.native_address, mesh.native_address, scale.native_address);
        if (addr == 0)
            return B3Shape.NULL;
        B3Shape B3Shape_NEW = B3Shape.native_new();
        B3Shape_NEW.internal_reset(addr, true);
        return B3Shape_NEW;
    }

    public static long internal_native_CreateMeshShape_addr(long this_addr, long def_addr, long mesh_addr, long scale_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_CreateMeshShape_addr(this_addr, def_addr, mesh_addr, scale_addr);
    }

    public B3Shape CreateMeshShapeWithMaterials(B3ShapeDef def, B3Mesh mesh, B3Vec3 scale, B3SurfaceMaterialArray materials) {
        long addr = internal_native_CreateMeshShapeWithMaterials_addr(native_address, def.native_address, mesh.native_address, scale.native_address, materials.native_address);
        if (addr == 0)
            return B3Shape.NULL;
        B3Shape B3Shape_NEW = B3Shape.native_new();
        B3Shape_NEW.internal_reset(addr, true);
        return B3Shape_NEW;
    }

    public static long internal_native_CreateMeshShapeWithMaterials_addr(long this_addr, long def_addr, long mesh_addr, long scale_addr, long materials_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_CreateMeshShapeWithMaterials_addr(this_addr, def_addr, mesh_addr, scale_addr, materials_addr);
    }

    public B3Shape CreateHeightFieldShape(B3ShapeDef def, B3HeightField heightField) {
        long addr = internal_native_CreateHeightFieldShape_addr(native_address, def.native_address, heightField.native_address);
        if (addr == 0)
            return B3Shape.NULL;
        B3Shape B3Shape_NEW = B3Shape.native_new();
        B3Shape_NEW.internal_reset(addr, true);
        return B3Shape_NEW;
    }

    public static long internal_native_CreateHeightFieldShape_addr(long this_addr, long def_addr, long heightField_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_CreateHeightFieldShape_addr(this_addr, def_addr, heightField_addr);
    }

    public B3Shape CreateBakedCompoundShape(B3ShapeDef def, B3Compound compound) {
        long addr = internal_native_CreateBakedCompoundShape_addr(native_address, def.native_address, compound.native_address);
        if (addr == 0)
            return B3Shape.NULL;
        B3Shape B3Shape_NEW = B3Shape.native_new();
        B3Shape_NEW.internal_reset(addr, true);
        return B3Shape_NEW;
    }

    public static long internal_native_CreateBakedCompoundShape_addr(long this_addr, long def_addr, long compound_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Body.internal_native_CreateBakedCompoundShape_addr(this_addr, def_addr, compound_addr);
    }
}
