/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3CompoundDef extends NativeObject {

    static public final B3CompoundDef NULL = B3CompoundDef.native_new();

    public B3CompoundDef(int capsuleCapacity, int hullCapacity, int meshCapacity, int sphereCapacity) {
        long addr = internal_native_create_int_int_int_int_addr(capsuleCapacity, hullCapacity, meshCapacity, sphereCapacity);
        internal_reset(addr, true);
    }

    public static long internal_native_create_int_int_int_int_addr(int capsuleCapacity, int hullCapacity, int meshCapacity, int sphereCapacity) {
        return com.github.xpenatan.box3d.natives.JNI_B3CompoundDef.internal_native_create_int_int_int_int_addr(capsuleCapacity, hullCapacity, meshCapacity, sphereCapacity);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3CompoundDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3CompoundDef native_new() {
        return new B3CompoundDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3CompoundDef.internal_native_deleteNative(this_addr);
    }

    public void AddCapsule(B3Capsule capsule, B3SurfaceMaterial material) {
        internal_native_AddCapsule(native_address, capsule.native_address, material.native_address);
    }

    public static void internal_native_AddCapsule(long this_addr, long capsule_addr, long material_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3CompoundDef.internal_native_AddCapsule(this_addr, capsule_addr, material_addr);
    }

    public void AddHull(B3Hull hull, B3Transform transform, B3SurfaceMaterial material) {
        internal_native_AddHull(native_address, hull.native_address, transform.native_address, material.native_address);
    }

    public static void internal_native_AddHull(long this_addr, long hull_addr, long transform_addr, long material_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3CompoundDef.internal_native_AddHull(this_addr, hull_addr, transform_addr, material_addr);
    }

    public void AddMesh(B3Mesh mesh, B3Transform transform, B3Vec3 scale, B3SurfaceMaterialArray materials) {
        internal_native_AddMesh(native_address, mesh.native_address, transform.native_address, scale.native_address, materials.native_address);
    }

    public static void internal_native_AddMesh(long this_addr, long mesh_addr, long transform_addr, long scale_addr, long materials_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3CompoundDef.internal_native_AddMesh(this_addr, mesh_addr, transform_addr, scale_addr, materials_addr);
    }

    public void AddSphere(B3Sphere sphere, B3SurfaceMaterial material) {
        internal_native_AddSphere(native_address, sphere.native_address, material.native_address);
    }

    public static void internal_native_AddSphere(long this_addr, long sphere_addr, long material_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3CompoundDef.internal_native_AddSphere(this_addr, sphere_addr, material_addr);
    }

    public int GetCapsuleCount() {
        return internal_native_GetCapsuleCount(native_address);
    }

    public static int internal_native_GetCapsuleCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3CompoundDef.internal_native_GetCapsuleCount(this_addr);
    }

    public int GetHullCount() {
        return internal_native_GetHullCount(native_address);
    }

    public static int internal_native_GetHullCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3CompoundDef.internal_native_GetHullCount(this_addr);
    }

    public int GetMeshCount() {
        return internal_native_GetMeshCount(native_address);
    }

    public static int internal_native_GetMeshCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3CompoundDef.internal_native_GetMeshCount(this_addr);
    }

    public int GetSphereCount() {
        return internal_native_GetSphereCount(native_address);
    }

    public static int internal_native_GetSphereCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3CompoundDef.internal_native_GetSphereCount(this_addr);
    }
}
