/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3Counters extends NativeObject {

    static public final B3Counters NULL = B3Counters.native_new();

    public B3Counters() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Counters(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Counters native_new() {
        return new B3Counters((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_deleteNative(this_addr);
    }

    public int GetBodyCount() {
        return internal_native_GetBodyCount(native_address);
    }

    public static int internal_native_GetBodyCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetBodyCount(this_addr);
    }

    public int GetShapeCount() {
        return internal_native_GetShapeCount(native_address);
    }

    public static int internal_native_GetShapeCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetShapeCount(this_addr);
    }

    public int GetContactCount() {
        return internal_native_GetContactCount(native_address);
    }

    public static int internal_native_GetContactCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetContactCount(this_addr);
    }

    public int GetJointCount() {
        return internal_native_GetJointCount(native_address);
    }

    public static int internal_native_GetJointCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetJointCount(this_addr);
    }

    public int GetIslandCount() {
        return internal_native_GetIslandCount(native_address);
    }

    public static int internal_native_GetIslandCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetIslandCount(this_addr);
    }

    public int GetStackUsed() {
        return internal_native_GetStackUsed(native_address);
    }

    public static int internal_native_GetStackUsed(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetStackUsed(this_addr);
    }

    public int GetArenaCapacity() {
        return internal_native_GetArenaCapacity(native_address);
    }

    public static int internal_native_GetArenaCapacity(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetArenaCapacity(this_addr);
    }

    public int GetStaticTreeHeight() {
        return internal_native_GetStaticTreeHeight(native_address);
    }

    public static int internal_native_GetStaticTreeHeight(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetStaticTreeHeight(this_addr);
    }

    public int GetTreeHeight() {
        return internal_native_GetTreeHeight(native_address);
    }

    public static int internal_native_GetTreeHeight(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetTreeHeight(this_addr);
    }

    public int GetSatCallCount() {
        return internal_native_GetSatCallCount(native_address);
    }

    public static int internal_native_GetSatCallCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetSatCallCount(this_addr);
    }

    public int GetSatCacheHitCount() {
        return internal_native_GetSatCacheHitCount(native_address);
    }

    public static int internal_native_GetSatCacheHitCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetSatCacheHitCount(this_addr);
    }

    public int GetByteCount() {
        return internal_native_GetByteCount(native_address);
    }

    public static int internal_native_GetByteCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetByteCount(this_addr);
    }

    public int GetTaskCount() {
        return internal_native_GetTaskCount(native_address);
    }

    public static int internal_native_GetTaskCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetTaskCount(this_addr);
    }

    public int GetColorCount(int index) {
        return internal_native_GetColorCount(native_address, index);
    }

    public static int internal_native_GetColorCount(long this_addr, int index) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetColorCount(this_addr, index);
    }

    public int GetManifoldCount(int index) {
        return internal_native_GetManifoldCount(native_address, index);
    }

    public static int internal_native_GetManifoldCount(long this_addr, int index) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetManifoldCount(this_addr, index);
    }

    public int GetAwakeContactCount() {
        return internal_native_GetAwakeContactCount(native_address);
    }

    public static int internal_native_GetAwakeContactCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetAwakeContactCount(this_addr);
    }

    public int GetRecycledContactCount() {
        return internal_native_GetRecycledContactCount(native_address);
    }

    public static int internal_native_GetRecycledContactCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetRecycledContactCount(this_addr);
    }

    public int GetDistanceIterations() {
        return internal_native_GetDistanceIterations(native_address);
    }

    public static int internal_native_GetDistanceIterations(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetDistanceIterations(this_addr);
    }

    public int GetPushBackIterations() {
        return internal_native_GetPushBackIterations(native_address);
    }

    public static int internal_native_GetPushBackIterations(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetPushBackIterations(this_addr);
    }

    public int GetRootIterations() {
        return internal_native_GetRootIterations(native_address);
    }

    public static int internal_native_GetRootIterations(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Counters.internal_native_GetRootIterations(this_addr);
    }
}
