/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3DistanceJointDef extends NativeObject {

    private B3Transform B3Transform_TEMP_GEN_0;

    private B3Transform B3Transform_TEMP_GEN_1;

    static public final B3DistanceJointDef NULL = B3DistanceJointDef.native_new();

    public B3DistanceJointDef() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3DistanceJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3DistanceJointDef native_new() {
        return new B3DistanceJointDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_deleteNative(this_addr);
    }

    public long GetBodyIdA() {
        return internal_native_GetBodyIdA(native_address);
    }

    public static long internal_native_GetBodyIdA(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetBodyIdA(this_addr);
    }

    public void SetBodyIdA(long bodyId) {
        internal_native_SetBodyIdA(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdA(long this_addr, long bodyId) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetBodyIdA(this_addr, bodyId);
    }

    public long GetBodyIdB() {
        return internal_native_GetBodyIdB(native_address);
    }

    public static long internal_native_GetBodyIdB(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetBodyIdB(this_addr);
    }

    public void SetBodyIdB(long bodyId) {
        internal_native_SetBodyIdB(native_address, bodyId);
    }

    public static void internal_native_SetBodyIdB(long this_addr, long bodyId) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetBodyIdB(this_addr, bodyId);
    }

    public B3Transform GetLocalFrameA() {
        long addr = internal_native_GetLocalFrameA_addr(native_address);
        if (addr == 0)
            return B3Transform.NULL;
        if (B3Transform_TEMP_GEN_0 == null)
            B3Transform_TEMP_GEN_0 = B3Transform.native_new();
        B3Transform_TEMP_GEN_0.internal_reset(addr, false);
        return B3Transform_TEMP_GEN_0;
    }

    public static long internal_native_GetLocalFrameA_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetLocalFrameA_addr(this_addr);
    }

    public void SetLocalFrameA(B3Transform transform) {
        internal_native_SetLocalFrameA(native_address, transform.native_address);
    }

    public static void internal_native_SetLocalFrameA(long this_addr, long transform_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetLocalFrameA(this_addr, transform_addr);
    }

    public B3Transform GetLocalFrameB() {
        long addr = internal_native_GetLocalFrameB_addr(native_address);
        if (addr == 0)
            return B3Transform.NULL;
        if (B3Transform_TEMP_GEN_1 == null)
            B3Transform_TEMP_GEN_1 = B3Transform.native_new();
        B3Transform_TEMP_GEN_1.internal_reset(addr, false);
        return B3Transform_TEMP_GEN_1;
    }

    public static long internal_native_GetLocalFrameB_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetLocalFrameB_addr(this_addr);
    }

    public void SetLocalFrameB(B3Transform transform) {
        internal_native_SetLocalFrameB(native_address, transform.native_address);
    }

    public static void internal_native_SetLocalFrameB(long this_addr, long transform_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetLocalFrameB(this_addr, transform_addr);
    }

    public void SetLocalPositionA(B3Vec3 position) {
        internal_native_SetLocalPositionA(native_address, position.native_address);
    }

    public static void internal_native_SetLocalPositionA(long this_addr, long position_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetLocalPositionA(this_addr, position_addr);
    }

    public void SetLocalPositionB(B3Vec3 position) {
        internal_native_SetLocalPositionB(native_address, position.native_address);
    }

    public static void internal_native_SetLocalPositionB(long this_addr, long position_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetLocalPositionB(this_addr, position_addr);
    }

    public float GetDrawScale() {
        return internal_native_GetDrawScale(native_address);
    }

    public static float internal_native_GetDrawScale(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetDrawScale(this_addr);
    }

    public void SetDrawScale(float scale) {
        internal_native_SetDrawScale(native_address, scale);
    }

    public static void internal_native_SetDrawScale(long this_addr, float scale) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetDrawScale(this_addr, scale);
    }

    public boolean GetCollideConnected() {
        return internal_native_GetCollideConnected(native_address);
    }

    public static boolean internal_native_GetCollideConnected(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetCollideConnected(this_addr);
    }

    public void SetCollideConnected(boolean collide) {
        internal_native_SetCollideConnected(native_address, collide);
    }

    public static void internal_native_SetCollideConnected(long this_addr, boolean collide) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetCollideConnected(this_addr, collide);
    }

    public float GetConstraintHertz() {
        return internal_native_GetConstraintHertz(native_address);
    }

    public static float internal_native_GetConstraintHertz(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetConstraintHertz(this_addr);
    }

    public void SetConstraintHertz(float hertz) {
        internal_native_SetConstraintHertz(native_address, hertz);
    }

    public static void internal_native_SetConstraintHertz(long this_addr, float hertz) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetConstraintHertz(this_addr, hertz);
    }

    public float GetConstraintDampingRatio() {
        return internal_native_GetConstraintDampingRatio(native_address);
    }

    public static float internal_native_GetConstraintDampingRatio(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetConstraintDampingRatio(this_addr);
    }

    public void SetConstraintDampingRatio(float ratio) {
        internal_native_SetConstraintDampingRatio(native_address, ratio);
    }

    public static void internal_native_SetConstraintDampingRatio(long this_addr, float ratio) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetConstraintDampingRatio(this_addr, ratio);
    }

    public float GetLength() {
        return internal_native_GetLength(native_address);
    }

    public static float internal_native_GetLength(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetLength(this_addr);
    }

    public void SetLength(float length) {
        internal_native_SetLength(native_address, length);
    }

    public static void internal_native_SetLength(long this_addr, float length) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetLength(this_addr, length);
    }

    public boolean GetEnableSpring() {
        return internal_native_GetEnableSpring(native_address);
    }

    public static boolean internal_native_GetEnableSpring(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetEnableSpring(this_addr);
    }

    public void SetEnableSpring(boolean enabled) {
        internal_native_SetEnableSpring(native_address, enabled);
    }

    public static void internal_native_SetEnableSpring(long this_addr, boolean enabled) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetEnableSpring(this_addr, enabled);
    }

    public float GetLowerSpringForce() {
        return internal_native_GetLowerSpringForce(native_address);
    }

    public static float internal_native_GetLowerSpringForce(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetLowerSpringForce(this_addr);
    }

    public void SetLowerSpringForce(float force) {
        internal_native_SetLowerSpringForce(native_address, force);
    }

    public static void internal_native_SetLowerSpringForce(long this_addr, float force) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetLowerSpringForce(this_addr, force);
    }

    public float GetUpperSpringForce() {
        return internal_native_GetUpperSpringForce(native_address);
    }

    public static float internal_native_GetUpperSpringForce(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetUpperSpringForce(this_addr);
    }

    public void SetUpperSpringForce(float force) {
        internal_native_SetUpperSpringForce(native_address, force);
    }

    public static void internal_native_SetUpperSpringForce(long this_addr, float force) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetUpperSpringForce(this_addr, force);
    }

    public float GetHertz() {
        return internal_native_GetHertz(native_address);
    }

    public static float internal_native_GetHertz(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetHertz(this_addr);
    }

    public void SetHertz(float hertz) {
        internal_native_SetHertz(native_address, hertz);
    }

    public static void internal_native_SetHertz(long this_addr, float hertz) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetHertz(this_addr, hertz);
    }

    public float GetDampingRatio() {
        return internal_native_GetDampingRatio(native_address);
    }

    public static float internal_native_GetDampingRatio(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetDampingRatio(this_addr);
    }

    public void SetDampingRatio(float ratio) {
        internal_native_SetDampingRatio(native_address, ratio);
    }

    public static void internal_native_SetDampingRatio(long this_addr, float ratio) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetDampingRatio(this_addr, ratio);
    }

    public boolean GetEnableLimit() {
        return internal_native_GetEnableLimit(native_address);
    }

    public static boolean internal_native_GetEnableLimit(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetEnableLimit(this_addr);
    }

    public void SetEnableLimit(boolean enabled) {
        internal_native_SetEnableLimit(native_address, enabled);
    }

    public static void internal_native_SetEnableLimit(long this_addr, boolean enabled) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetEnableLimit(this_addr, enabled);
    }

    public float GetMinLength() {
        return internal_native_GetMinLength(native_address);
    }

    public static float internal_native_GetMinLength(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetMinLength(this_addr);
    }

    public void SetMinLength(float length) {
        internal_native_SetMinLength(native_address, length);
    }

    public static void internal_native_SetMinLength(long this_addr, float length) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetMinLength(this_addr, length);
    }

    public float GetMaxLength() {
        return internal_native_GetMaxLength(native_address);
    }

    public static float internal_native_GetMaxLength(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetMaxLength(this_addr);
    }

    public void SetMaxLength(float length) {
        internal_native_SetMaxLength(native_address, length);
    }

    public static void internal_native_SetMaxLength(long this_addr, float length) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetMaxLength(this_addr, length);
    }

    public boolean GetEnableMotor() {
        return internal_native_GetEnableMotor(native_address);
    }

    public static boolean internal_native_GetEnableMotor(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetEnableMotor(this_addr);
    }

    public void SetEnableMotor(boolean enabled) {
        internal_native_SetEnableMotor(native_address, enabled);
    }

    public static void internal_native_SetEnableMotor(long this_addr, boolean enabled) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetEnableMotor(this_addr, enabled);
    }

    public float GetMaxMotorForce() {
        return internal_native_GetMaxMotorForce(native_address);
    }

    public static float internal_native_GetMaxMotorForce(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetMaxMotorForce(this_addr);
    }

    public void SetMaxMotorForce(float force) {
        internal_native_SetMaxMotorForce(native_address, force);
    }

    public static void internal_native_SetMaxMotorForce(long this_addr, float force) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetMaxMotorForce(this_addr, force);
    }

    public float GetMotorSpeed() {
        return internal_native_GetMotorSpeed(native_address);
    }

    public static float internal_native_GetMotorSpeed(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_GetMotorSpeed(this_addr);
    }

    public void SetMotorSpeed(float speed) {
        internal_native_SetMotorSpeed(native_address, speed);
    }

    public static void internal_native_SetMotorSpeed(long this_addr, float speed) {
        com.github.xpenatan.box3d.natives.JNI_B3DistanceJointDef.internal_native_SetMotorSpeed(this_addr, speed);
    }
}
