/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3FrictionCallbackEm extends NativeObject {

    static public final B3FrictionCallbackEm NULL = B3FrictionCallbackEm.native_new();

    @Deprecated()
    protected B3FrictionCallbackEm(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3FrictionCallbackEm native_new() {
        return new B3FrictionCallbackEm((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3FrictionCallbackEm.internal_native_deleteNative(this_addr);
    }

    public B3FrictionCallbackEm() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        internal_native_setupCallback(native_address);
    }

    protected float MixFriction(float frictionA, long userMaterialIdA, float frictionB, long userMaterialIdB) {
        return 0;
    }

    private float internal_MixFriction(float frictionA, long userMaterialIdA, float frictionB, long userMaterialIdB) {
        return MixFriction(frictionA, userMaterialIdA, frictionB, userMaterialIdB);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3FrictionCallbackEm.internal_native_create_addr();
    }

    public native void internal_native_setupCallback(long this_addr);
}
