/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3HeightField extends NativeObject {

    static public final B3HeightField NULL = B3HeightField.native_new();

    public B3HeightField() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3HeightField.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3HeightField(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3HeightField native_new() {
        return new B3HeightField((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3HeightField.internal_native_deleteNative(this_addr);
    }

    public static B3HeightField CreateGrid(int rowCount, int columnCount, B3Vec3 scale, boolean makeHoles) {
        long addr = internal_native_CreateGrid_addr(rowCount, columnCount, scale.native_address, makeHoles);
        if (addr == 0)
            return B3HeightField.NULL;
        B3HeightField B3HeightField_NEW = B3HeightField.native_new();
        B3HeightField_NEW.internal_reset(addr, true);
        return B3HeightField_NEW;
    }

    public static long internal_native_CreateGrid_addr(int rowCount, int columnCount, long scale_addr, boolean makeHoles) {
        return com.github.xpenatan.box3d.natives.JNI_B3HeightField.internal_native_CreateGrid_addr(rowCount, columnCount, scale_addr, makeHoles);
    }

    public static B3HeightField CreateWave(int rowCount, int columnCount, B3Vec3 scale, float rowFrequency, float columnFrequency, boolean makeHoles) {
        long addr = internal_native_CreateWave_addr(rowCount, columnCount, scale.native_address, rowFrequency, columnFrequency, makeHoles);
        if (addr == 0)
            return B3HeightField.NULL;
        B3HeightField B3HeightField_NEW = B3HeightField.native_new();
        B3HeightField_NEW.internal_reset(addr, true);
        return B3HeightField_NEW;
    }

    public static long internal_native_CreateWave_addr(int rowCount, int columnCount, long scale_addr, float rowFrequency, float columnFrequency, boolean makeHoles) {
        return com.github.xpenatan.box3d.natives.JNI_B3HeightField.internal_native_CreateWave_addr(rowCount, columnCount, scale_addr, rowFrequency, columnFrequency, makeHoles);
    }

    public boolean IsValid() {
        return internal_native_IsValid(native_address);
    }

    public static boolean internal_native_IsValid(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3HeightField.internal_native_IsValid(this_addr);
    }

    public void Destroy() {
        internal_native_Destroy(native_address);
    }

    public static void internal_native_Destroy(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3HeightField.internal_native_Destroy(this_addr);
    }
}
