/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3JointEvents extends NativeObject {

    private B3JointEvent B3JointEvent_TEMP_GEN_0;

    static public final B3JointEvents NULL = B3JointEvents.native_new();

    public B3JointEvents() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3JointEvents.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3JointEvents(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3JointEvents native_new() {
        return new B3JointEvents((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3JointEvents.internal_native_deleteNative(this_addr);
    }

    public int GetCount() {
        return internal_native_GetCount(native_address);
    }

    public static int internal_native_GetCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3JointEvents.internal_native_GetCount(this_addr);
    }

    public B3JointEvent GetEvent(int index) {
        long addr = internal_native_GetEvent_addr(native_address, index);
        if (addr == 0)
            return B3JointEvent.NULL;
        if (B3JointEvent_TEMP_GEN_0 == null)
            B3JointEvent_TEMP_GEN_0 = B3JointEvent.native_new();
        B3JointEvent_TEMP_GEN_0.internal_reset(addr, false);
        return B3JointEvent_TEMP_GEN_0;
    }

    public static long internal_native_GetEvent_addr(long this_addr, int index) {
        return com.github.xpenatan.box3d.natives.JNI_B3JointEvents.internal_native_GetEvent_addr(this_addr, index);
    }
}
