/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3Joint extends NativeObject {

    static public final B3Joint NULL = B3Joint.native_new();

    public B3Joint() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_create_addr();
    }

    public B3Joint(long jointId) {
        long addr = internal_native_create_long_addr(jointId);
        internal_reset(addr, true);
    }

    public static long internal_native_create_long_addr(long jointId) {
        return com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_create_long_addr(jointId);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Joint(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Joint native_new() {
        return new B3Joint((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_deleteNative(this_addr);
    }

    public long GetId() {
        return internal_native_GetId(native_address);
    }

    public static long internal_native_GetId(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_GetId(this_addr);
    }

    public boolean IsValid() {
        return internal_native_IsValid(native_address);
    }

    public static boolean internal_native_IsValid(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_IsValid(this_addr);
    }

    public void Destroy(boolean wakeAttached) {
        internal_native_Destroy(native_address, wakeAttached);
    }

    public static void internal_native_Destroy(long this_addr, boolean wakeAttached) {
        com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_Destroy(this_addr, wakeAttached);
    }

    public long GetBodyIdA() {
        return internal_native_GetBodyIdA(native_address);
    }

    public static long internal_native_GetBodyIdA(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_GetBodyIdA(this_addr);
    }

    public long GetBodyIdB() {
        return internal_native_GetBodyIdB(native_address);
    }

    public static long internal_native_GetBodyIdB(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_GetBodyIdB(this_addr);
    }

    public void WakeBodies() {
        internal_native_WakeBodies(native_address);
    }

    public static void internal_native_WakeBodies(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_WakeBodies(this_addr);
    }

    public float GetLinearSeparation() {
        return internal_native_GetLinearSeparation(native_address);
    }

    public static float internal_native_GetLinearSeparation(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_GetLinearSeparation(this_addr);
    }

    public float GetPrismaticTranslation() {
        return internal_native_GetPrismaticTranslation(native_address);
    }

    public static float internal_native_GetPrismaticTranslation(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_GetPrismaticTranslation(this_addr);
    }

    public void SetPrismaticMotorSpeed(float speed) {
        internal_native_SetPrismaticMotorSpeed(native_address, speed);
    }

    public static void internal_native_SetPrismaticMotorSpeed(long this_addr, float speed) {
        com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_SetPrismaticMotorSpeed(this_addr, speed);
    }

    public void SetRevoluteTargetAngle(float radians) {
        internal_native_SetRevoluteTargetAngle(native_address, radians);
    }

    public static void internal_native_SetRevoluteTargetAngle(long this_addr, float radians) {
        com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_SetRevoluteTargetAngle(this_addr, radians);
    }

    public void SetRevoluteMaxMotorTorque(float torque) {
        internal_native_SetRevoluteMaxMotorTorque(native_address, torque);
    }

    public static void internal_native_SetRevoluteMaxMotorTorque(long this_addr, float torque) {
        com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_SetRevoluteMaxMotorTorque(this_addr, torque);
    }

    public void SetRevoluteSpringHertz(float hertz) {
        internal_native_SetRevoluteSpringHertz(native_address, hertz);
    }

    public static void internal_native_SetRevoluteSpringHertz(long this_addr, float hertz) {
        com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_SetRevoluteSpringHertz(this_addr, hertz);
    }

    public void SetRevoluteSpringDampingRatio(float dampingRatio) {
        internal_native_SetRevoluteSpringDampingRatio(native_address, dampingRatio);
    }

    public static void internal_native_SetRevoluteSpringDampingRatio(long this_addr, float dampingRatio) {
        com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_SetRevoluteSpringDampingRatio(this_addr, dampingRatio);
    }

    public void SetSphericalMaxMotorTorque(float torque) {
        internal_native_SetSphericalMaxMotorTorque(native_address, torque);
    }

    public static void internal_native_SetSphericalMaxMotorTorque(long this_addr, float torque) {
        com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_SetSphericalMaxMotorTorque(this_addr, torque);
    }

    public void SetSphericalSpringHertz(float hertz) {
        internal_native_SetSphericalSpringHertz(native_address, hertz);
    }

    public static void internal_native_SetSphericalSpringHertz(long this_addr, float hertz) {
        com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_SetSphericalSpringHertz(this_addr, hertz);
    }

    public void SetSphericalSpringDampingRatio(float dampingRatio) {
        internal_native_SetSphericalSpringDampingRatio(native_address, dampingRatio);
    }

    public static void internal_native_SetSphericalSpringDampingRatio(long this_addr, float dampingRatio) {
        com.github.xpenatan.box3d.natives.JNI_B3Joint.internal_native_SetSphericalSpringDampingRatio(this_addr, dampingRatio);
    }
}
