/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3LogCallbackEm extends NativeObject {

    static public final B3LogCallbackEm NULL = B3LogCallbackEm.native_new();

    @Deprecated()
    protected B3LogCallbackEm(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3LogCallbackEm native_new() {
        return new B3LogCallbackEm((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3LogCallbackEm.internal_native_deleteNative(this_addr);
    }

    public B3LogCallbackEm() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        internal_native_setupCallback(native_address);
    }

    protected void Log(String message) {
    }

    private void internal_Log(String message_addr) {
        Log(message_addr);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3LogCallbackEm.internal_native_create_addr();
    }

    public native void internal_native_setupCallback(long this_addr);
}
