/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3LocalManifold extends NativeObject {

    private B3Vec3 B3Vec3_TEMP_GEN_0;

    private B3Vec3 B3Vec3_TEMP_GEN_1;

    private B3LocalManifoldPoint B3LocalManifoldPoint_TEMP_GEN_0;

    static public final B3LocalManifold NULL = B3LocalManifold.native_new();

    public B3LocalManifold(int capacity) {
        long addr = internal_native_create_int_addr(capacity);
        internal_reset(addr, true);
    }

    public static long internal_native_create_int_addr(int capacity) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifold.internal_native_create_int_addr(capacity);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3LocalManifold(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3LocalManifold native_new() {
        return new B3LocalManifold((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3LocalManifold.internal_native_deleteNative(this_addr);
    }

    public B3Vec3 GetNormal() {
        long addr = internal_native_GetNormal_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_0 == null)
            B3Vec3_TEMP_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetNormal_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifold.internal_native_GetNormal_addr(this_addr);
    }

    public B3Vec3 GetTriangleNormal() {
        long addr = internal_native_GetTriangleNormal_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_1 == null)
            B3Vec3_TEMP_GEN_1 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_1;
    }

    public static long internal_native_GetTriangleNormal_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifold.internal_native_GetTriangleNormal_addr(this_addr);
    }

    public int GetPointCount() {
        return internal_native_GetPointCount(native_address);
    }

    public static int internal_native_GetPointCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifold.internal_native_GetPointCount(this_addr);
    }

    public B3LocalManifoldPoint GetPoint(int index) {
        long addr = internal_native_GetPoint_addr(native_address, index);
        if (addr == 0)
            return B3LocalManifoldPoint.NULL;
        if (B3LocalManifoldPoint_TEMP_GEN_0 == null)
            B3LocalManifoldPoint_TEMP_GEN_0 = B3LocalManifoldPoint.native_new();
        B3LocalManifoldPoint_TEMP_GEN_0.internal_reset(addr, false);
        return B3LocalManifoldPoint_TEMP_GEN_0;
    }

    public static long internal_native_GetPoint_addr(long this_addr, int index) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifold.internal_native_GetPoint_addr(this_addr, index);
    }

    public int GetFeature() {
        return internal_native_GetFeature(native_address);
    }

    public static int internal_native_GetFeature(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifold.internal_native_GetFeature(this_addr);
    }

    public int GetTriangleIndex() {
        return internal_native_GetTriangleIndex(native_address);
    }

    public static int internal_native_GetTriangleIndex(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifold.internal_native_GetTriangleIndex(this_addr);
    }
}
