/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3LocalManifoldPoint extends NativeObject {

    private B3Vec3 B3Vec3_TEMP_GEN_0;

    static public final B3LocalManifoldPoint NULL = B3LocalManifoldPoint.native_new();

    public B3LocalManifoldPoint() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifoldPoint.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3LocalManifoldPoint(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3LocalManifoldPoint native_new() {
        return new B3LocalManifoldPoint((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3LocalManifoldPoint.internal_native_deleteNative(this_addr);
    }

    public B3Vec3 GetPoint() {
        long addr = internal_native_GetPoint_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_0 == null)
            B3Vec3_TEMP_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetPoint_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifoldPoint.internal_native_GetPoint_addr(this_addr);
    }

    public float GetSeparation() {
        return internal_native_GetSeparation(native_address);
    }

    public static float internal_native_GetSeparation(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifoldPoint.internal_native_GetSeparation(this_addr);
    }

    public int GetOwner1() {
        return internal_native_GetOwner1(native_address);
    }

    public static int internal_native_GetOwner1(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifoldPoint.internal_native_GetOwner1(this_addr);
    }

    public int GetIndex1() {
        return internal_native_GetIndex1(native_address);
    }

    public static int internal_native_GetIndex1(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifoldPoint.internal_native_GetIndex1(this_addr);
    }

    public int GetOwner2() {
        return internal_native_GetOwner2(native_address);
    }

    public static int internal_native_GetOwner2(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifoldPoint.internal_native_GetOwner2(this_addr);
    }

    public int GetIndex2() {
        return internal_native_GetIndex2(native_address);
    }

    public static int internal_native_GetIndex2(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifoldPoint.internal_native_GetIndex2(this_addr);
    }

    public int GetTriangleIndex() {
        return internal_native_GetTriangleIndex(native_address);
    }

    public static int internal_native_GetTriangleIndex(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3LocalManifoldPoint.internal_native_GetTriangleIndex(this_addr);
    }
}
