/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3ManifoldPoint extends NativeObject {

    private B3Vec3 B3Vec3_TEMP_GEN_0;

    private B3Vec3 B3Vec3_TEMP_GEN_1;

    static public final B3ManifoldPoint NULL = B3ManifoldPoint.native_new();

    public B3ManifoldPoint() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3ManifoldPoint(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3ManifoldPoint native_new() {
        return new B3ManifoldPoint((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_deleteNative(this_addr);
    }

    public B3Vec3 GetAnchorA() {
        long addr = internal_native_GetAnchorA_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_0 == null)
            B3Vec3_TEMP_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetAnchorA_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_GetAnchorA_addr(this_addr);
    }

    public B3Vec3 GetAnchorB() {
        long addr = internal_native_GetAnchorB_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_1 == null)
            B3Vec3_TEMP_GEN_1 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_1;
    }

    public static long internal_native_GetAnchorB_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_GetAnchorB_addr(this_addr);
    }

    public float GetSeparation() {
        return internal_native_GetSeparation(native_address);
    }

    public static float internal_native_GetSeparation(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_GetSeparation(this_addr);
    }

    public float GetBaseSeparation() {
        return internal_native_GetBaseSeparation(native_address);
    }

    public static float internal_native_GetBaseSeparation(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_GetBaseSeparation(this_addr);
    }

    public float GetNormalImpulse() {
        return internal_native_GetNormalImpulse(native_address);
    }

    public static float internal_native_GetNormalImpulse(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_GetNormalImpulse(this_addr);
    }

    public float GetTotalNormalImpulse() {
        return internal_native_GetTotalNormalImpulse(native_address);
    }

    public static float internal_native_GetTotalNormalImpulse(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_GetTotalNormalImpulse(this_addr);
    }

    public float GetNormalVelocity() {
        return internal_native_GetNormalVelocity(native_address);
    }

    public static float internal_native_GetNormalVelocity(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_GetNormalVelocity(this_addr);
    }

    public int GetFeatureId() {
        return internal_native_GetFeatureId(native_address);
    }

    public static int internal_native_GetFeatureId(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_GetFeatureId(this_addr);
    }

    public int GetTriangleIndex() {
        return internal_native_GetTriangleIndex(native_address);
    }

    public static int internal_native_GetTriangleIndex(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_GetTriangleIndex(this_addr);
    }

    public boolean GetPersisted() {
        return internal_native_GetPersisted(native_address);
    }

    public static boolean internal_native_GetPersisted(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ManifoldPoint.internal_native_GetPersisted(this_addr);
    }
}
