/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3MeshDef extends NativeObject {

    static public final B3MeshDef NULL = B3MeshDef.native_new();

    public B3MeshDef(int vertexCapacity, int triangleCapacity) {
        long addr = internal_native_create_int_int_addr(vertexCapacity, triangleCapacity);
        internal_reset(addr, true);
    }

    public static long internal_native_create_int_int_addr(int vertexCapacity, int triangleCapacity) {
        return com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_create_int_int_addr(vertexCapacity, triangleCapacity);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3MeshDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3MeshDef native_new() {
        return new B3MeshDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_deleteNative(this_addr);
    }

    public void AddVertex(B3Vec3 vertex) {
        internal_native_AddVertex(native_address, vertex.native_address);
    }

    public static void internal_native_AddVertex(long this_addr, long vertex_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_AddVertex(this_addr, vertex_addr);
    }

    public void AddTriangle(int index1, int index2, int index3, int materialIndex) {
        internal_native_AddTriangle(native_address, index1, index2, index3, materialIndex);
    }

    public static void internal_native_AddTriangle(long this_addr, int index1, int index2, int index3, int materialIndex) {
        com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_AddTriangle(this_addr, index1, index2, index3, materialIndex);
    }

    public float GetWeldTolerance() {
        return internal_native_GetWeldTolerance(native_address);
    }

    public static float internal_native_GetWeldTolerance(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_GetWeldTolerance(this_addr);
    }

    public void SetWeldTolerance(float tolerance) {
        internal_native_SetWeldTolerance(native_address, tolerance);
    }

    public static void internal_native_SetWeldTolerance(long this_addr, float tolerance) {
        com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_SetWeldTolerance(this_addr, tolerance);
    }

    public boolean GetWeldVertices() {
        return internal_native_GetWeldVertices(native_address);
    }

    public static boolean internal_native_GetWeldVertices(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_GetWeldVertices(this_addr);
    }

    public void SetWeldVertices(boolean enabled) {
        internal_native_SetWeldVertices(native_address, enabled);
    }

    public static void internal_native_SetWeldVertices(long this_addr, boolean enabled) {
        com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_SetWeldVertices(this_addr, enabled);
    }

    public boolean GetUseMedianSplit() {
        return internal_native_GetUseMedianSplit(native_address);
    }

    public static boolean internal_native_GetUseMedianSplit(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_GetUseMedianSplit(this_addr);
    }

    public void SetUseMedianSplit(boolean enabled) {
        internal_native_SetUseMedianSplit(native_address, enabled);
    }

    public static void internal_native_SetUseMedianSplit(long this_addr, boolean enabled) {
        com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_SetUseMedianSplit(this_addr, enabled);
    }

    public boolean GetIdentifyEdges() {
        return internal_native_GetIdentifyEdges(native_address);
    }

    public static boolean internal_native_GetIdentifyEdges(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_GetIdentifyEdges(this_addr);
    }

    public void SetIdentifyEdges(boolean enabled) {
        internal_native_SetIdentifyEdges(native_address, enabled);
    }

    public static void internal_native_SetIdentifyEdges(long this_addr, boolean enabled) {
        com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_SetIdentifyEdges(this_addr, enabled);
    }

    public int GetVertexCount() {
        return internal_native_GetVertexCount(native_address);
    }

    public static int internal_native_GetVertexCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_GetVertexCount(this_addr);
    }

    public int GetTriangleCount() {
        return internal_native_GetTriangleCount(native_address);
    }

    public static int internal_native_GetTriangleCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3MeshDef.internal_native_GetTriangleCount(this_addr);
    }
}
