/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3MoverPlaneResult extends NativeObject {

    private B3Vec3 B3Vec3_TEMP_GEN_0;

    private B3Vec3 B3Vec3_TEMP_GEN_1;

    static public final B3MoverPlaneResult NULL = B3MoverPlaneResult.native_new();

    public B3MoverPlaneResult() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3MoverPlaneResult.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3MoverPlaneResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3MoverPlaneResult native_new() {
        return new B3MoverPlaneResult((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3MoverPlaneResult.internal_native_deleteNative(this_addr);
    }

    public long GetShapeId() {
        return internal_native_GetShapeId(native_address);
    }

    public static long internal_native_GetShapeId(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3MoverPlaneResult.internal_native_GetShapeId(this_addr);
    }

    public B3Vec3 GetNormal() {
        long addr = internal_native_GetNormal_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_0 == null)
            B3Vec3_TEMP_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetNormal_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3MoverPlaneResult.internal_native_GetNormal_addr(this_addr);
    }

    public float GetOffset() {
        return internal_native_GetOffset(native_address);
    }

    public static float internal_native_GetOffset(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3MoverPlaneResult.internal_native_GetOffset(this_addr);
    }

    public B3Vec3 GetPoint() {
        long addr = internal_native_GetPoint_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_1 == null)
            B3Vec3_TEMP_GEN_1 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_1.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_1;
    }

    public static long internal_native_GetPoint_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3MoverPlaneResult.internal_native_GetPoint_addr(this_addr);
    }
}
