/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3Plane extends NativeObject {

    private B3Vec3 B3Vec3_TEMP_GEN_0;

    static public final B3Plane NULL = B3Plane.native_new();

    public B3Plane() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3Plane.internal_native_create_addr();
    }

    public B3Plane(B3Vec3 normal, float offset) {
        long addr = internal_native_create_B3Vec3_float_addr(normal.native_address, offset);
        internal_reset(addr, true);
    }

    public static long internal_native_create_B3Vec3_float_addr(long normal_addr, float offset) {
        return com.github.xpenatan.box3d.natives.JNI_B3Plane.internal_native_create_B3Vec3_float_addr(normal_addr, offset);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Plane(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Plane native_new() {
        return new B3Plane((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Plane.internal_native_deleteNative(this_addr);
    }

    public B3Vec3 GetNormal() {
        long addr = internal_native_GetNormal_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_0 == null)
            B3Vec3_TEMP_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetNormal_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Plane.internal_native_GetNormal_addr(this_addr);
    }

    public void SetNormal(B3Vec3 normal) {
        internal_native_SetNormal(native_address, normal.native_address);
    }

    public static void internal_native_SetNormal(long this_addr, long normal_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3Plane.internal_native_SetNormal(this_addr, normal_addr);
    }

    public float GetOffset() {
        return internal_native_GetOffset(native_address);
    }

    public static float internal_native_GetOffset(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3Plane.internal_native_GetOffset(this_addr);
    }

    public void SetOffset(float offset) {
        internal_native_SetOffset(native_address, offset);
    }

    public static void internal_native_SetOffset(long this_addr, float offset) {
        com.github.xpenatan.box3d.natives.JNI_B3Plane.internal_native_SetOffset(this_addr, offset);
    }
}
