/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3ShapeProxy extends NativeObject {

    static public final B3ShapeProxy NULL = B3ShapeProxy.native_new();

    public B3ShapeProxy(B3Vec3Array points, int count, float radius) {
        long addr = internal_native_create_B3Vec3Array_int_float_addr(points.native_address, count, radius);
        internal_reset(addr, true);
    }

    public static long internal_native_create_B3Vec3Array_int_float_addr(long points_addr, int count, float radius) {
        return com.github.xpenatan.box3d.natives.JNI_B3ShapeProxy.internal_native_create_B3Vec3Array_int_float_addr(points_addr, count, radius);
    }

    public B3ShapeProxy(B3Hull hull, float radius) {
        long addr = internal_native_create_B3Hull_float_addr(hull.native_address, radius);
        internal_reset(addr, true);
    }

    public static long internal_native_create_B3Hull_float_addr(long hull_addr, float radius) {
        return com.github.xpenatan.box3d.natives.JNI_B3ShapeProxy.internal_native_create_B3Hull_float_addr(hull_addr, radius);
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3ShapeProxy(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3ShapeProxy native_new() {
        return new B3ShapeProxy((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3ShapeProxy.internal_native_deleteNative(this_addr);
    }

    public int GetCount() {
        return internal_native_GetCount(native_address);
    }

    public static int internal_native_GetCount(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ShapeProxy.internal_native_GetCount(this_addr);
    }

    public float GetRadius() {
        return internal_native_GetRadius(native_address);
    }

    public static float internal_native_GetRadius(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3ShapeProxy.internal_native_GetRadius(this_addr);
    }
}
