/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3SurfaceMaterial extends NativeObject {

    private B3Vec3 B3Vec3_TEMP_GEN_0;

    static public final B3SurfaceMaterial NULL = B3SurfaceMaterial.native_new();

    public B3SurfaceMaterial() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    public static long internal_native_create_addr() {
        return com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_create_addr();
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3SurfaceMaterial(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3SurfaceMaterial native_new() {
        return new B3SurfaceMaterial((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    public static void internal_native_deleteNative(long this_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_deleteNative(this_addr);
    }

    public float GetFriction() {
        return internal_native_GetFriction(native_address);
    }

    public static float internal_native_GetFriction(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_GetFriction(this_addr);
    }

    public void SetFriction(float friction) {
        internal_native_SetFriction(native_address, friction);
    }

    public static void internal_native_SetFriction(long this_addr, float friction) {
        com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_SetFriction(this_addr, friction);
    }

    public float GetRestitution() {
        return internal_native_GetRestitution(native_address);
    }

    public static float internal_native_GetRestitution(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_GetRestitution(this_addr);
    }

    public void SetRestitution(float restitution) {
        internal_native_SetRestitution(native_address, restitution);
    }

    public static void internal_native_SetRestitution(long this_addr, float restitution) {
        com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_SetRestitution(this_addr, restitution);
    }

    public float GetRollingResistance() {
        return internal_native_GetRollingResistance(native_address);
    }

    public static float internal_native_GetRollingResistance(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_GetRollingResistance(this_addr);
    }

    public void SetRollingResistance(float rollingResistance) {
        internal_native_SetRollingResistance(native_address, rollingResistance);
    }

    public static void internal_native_SetRollingResistance(long this_addr, float rollingResistance) {
        com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_SetRollingResistance(this_addr, rollingResistance);
    }

    public B3Vec3 GetTangentVelocity() {
        long addr = internal_native_GetTangentVelocity_addr(native_address);
        if (addr == 0)
            return B3Vec3.NULL;
        if (B3Vec3_TEMP_GEN_0 == null)
            B3Vec3_TEMP_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_GEN_0.internal_reset(addr, false);
        return B3Vec3_TEMP_GEN_0;
    }

    public static long internal_native_GetTangentVelocity_addr(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_GetTangentVelocity_addr(this_addr);
    }

    public void SetTangentVelocity(B3Vec3 tangentVelocity) {
        internal_native_SetTangentVelocity(native_address, tangentVelocity.native_address);
    }

    public static void internal_native_SetTangentVelocity(long this_addr, long tangentVelocity_addr) {
        com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_SetTangentVelocity(this_addr, tangentVelocity_addr);
    }

    public long GetUserMaterialId() {
        return internal_native_GetUserMaterialId(native_address);
    }

    public static long internal_native_GetUserMaterialId(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_GetUserMaterialId(this_addr);
    }

    public void SetUserMaterialId(long userMaterialId) {
        internal_native_SetUserMaterialId(native_address, userMaterialId);
    }

    public static void internal_native_SetUserMaterialId(long this_addr, long userMaterialId) {
        com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_SetUserMaterialId(this_addr, userMaterialId);
    }

    public int GetCustomColor() {
        return internal_native_GetCustomColor(native_address);
    }

    public static int internal_native_GetCustomColor(long this_addr) {
        return com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_GetCustomColor(this_addr);
    }

    public void SetCustomColor(int customColor) {
        internal_native_SetCustomColor(native_address, customColor);
    }

    public static void internal_native_SetCustomColor(long this_addr, int customColor) {
        com.github.xpenatan.box3d.natives.JNI_B3SurfaceMaterial.internal_native_SetCustomColor(this_addr, customColor);
    }
}
