/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3ContactEndTouchEvent extends NativeObject {

    private B3ContactId B3ContactId_TEMP_GEN_0;

    static public final B3ContactEndTouchEvent NULL = B3ContactEndTouchEvent.native_new();

    public B3ContactEndTouchEvent() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactendtouchevent_create_addr")
    public static native long internal_native_create_addr();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3ContactEndTouchEvent(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3ContactEndTouchEvent native_new() {
        return new B3ContactEndTouchEvent((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactendtouchevent_deletenative")
    public static native void internal_native_deleteNative(long this_addr);

    public long GetShapeIdA() {
        return internal_native_GetShapeIdA(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactendtouchevent_getshapeida")
    public static native long internal_native_GetShapeIdA(long this_addr);

    public long GetShapeIdB() {
        return internal_native_GetShapeIdB(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactendtouchevent_getshapeidb")
    public static native long internal_native_GetShapeIdB(long this_addr);

    public B3ContactId GetContactId() {
        long addr = internal_native_GetContactId_addr(native_address);
        if (addr == 0)
            return B3ContactId.NULL;
        if (B3ContactId_TEMP_GEN_0 == null)
            B3ContactId_TEMP_GEN_0 = B3ContactId.native_new();
        B3ContactId_TEMP_GEN_0.internal_reset(addr, false);
        return B3ContactId_TEMP_GEN_0;
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactendtouchevent_getcontactid_addr")
    public static native long internal_native_GetContactId_addr(long this_addr);
}
