/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3ContactEvents extends NativeObject {

    private B3ContactBeginTouchEvent B3ContactBeginTouchEvent_TEMP_GEN_0;

    private B3ContactEndTouchEvent B3ContactEndTouchEvent_TEMP_GEN_0;

    private B3ContactHitEvent B3ContactHitEvent_TEMP_GEN_0;

    static public final B3ContactEvents NULL = B3ContactEvents.native_new();

    public B3ContactEvents() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactevents_create_addr")
    public static native long internal_native_create_addr();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3ContactEvents(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3ContactEvents native_new() {
        return new B3ContactEvents((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactevents_deletenative")
    public static native void internal_native_deleteNative(long this_addr);

    public int GetBeginCount() {
        return internal_native_GetBeginCount(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactevents_getbegincount")
    public static native int internal_native_GetBeginCount(long this_addr);

    public B3ContactBeginTouchEvent GetBeginEvent(int index) {
        long addr = internal_native_GetBeginEvent_addr(native_address, index);
        if (addr == 0)
            return B3ContactBeginTouchEvent.NULL;
        if (B3ContactBeginTouchEvent_TEMP_GEN_0 == null)
            B3ContactBeginTouchEvent_TEMP_GEN_0 = B3ContactBeginTouchEvent.native_new();
        B3ContactBeginTouchEvent_TEMP_GEN_0.internal_reset(addr, false);
        return B3ContactBeginTouchEvent_TEMP_GEN_0;
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactevents_getbeginevent_addr")
    public static native long internal_native_GetBeginEvent_addr(long this_addr, int index);

    public int GetEndCount() {
        return internal_native_GetEndCount(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactevents_getendcount")
    public static native int internal_native_GetEndCount(long this_addr);

    public B3ContactEndTouchEvent GetEndEvent(int index) {
        long addr = internal_native_GetEndEvent_addr(native_address, index);
        if (addr == 0)
            return B3ContactEndTouchEvent.NULL;
        if (B3ContactEndTouchEvent_TEMP_GEN_0 == null)
            B3ContactEndTouchEvent_TEMP_GEN_0 = B3ContactEndTouchEvent.native_new();
        B3ContactEndTouchEvent_TEMP_GEN_0.internal_reset(addr, false);
        return B3ContactEndTouchEvent_TEMP_GEN_0;
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactevents_getendevent_addr")
    public static native long internal_native_GetEndEvent_addr(long this_addr, int index);

    public int GetHitCount() {
        return internal_native_GetHitCount(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactevents_gethitcount")
    public static native int internal_native_GetHitCount(long this_addr);

    public B3ContactHitEvent GetHitEvent(int index) {
        long addr = internal_native_GetHitEvent_addr(native_address, index);
        if (addr == 0)
            return B3ContactHitEvent.NULL;
        if (B3ContactHitEvent_TEMP_GEN_0 == null)
            B3ContactHitEvent_TEMP_GEN_0 = B3ContactHitEvent.native_new();
        B3ContactHitEvent_TEMP_GEN_0.internal_reset(addr, false);
        return B3ContactHitEvent_TEMP_GEN_0;
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3contactevents_gethitevent_addr")
    public static native long internal_native_GetHitEvent_addr(long this_addr, int index);
}
