/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3DebugDrawEm extends NativeObject {

    private B3AABB B3AABB_TEMP_GEN_0;

    static private B3DebugShape B3DebugShape_TEMP_STATIC_GEN_0;

    static private B3Transform B3Transform_TEMP_STATIC_GEN_0;

    static private B3Vec3 B3Vec3_TEMP_STATIC_GEN_0;

    static private B3Vec3 B3Vec3_TEMP_STATIC_GEN_1;

    static private B3Transform B3Transform_TEMP_STATIC_GEN_1;

    static private B3Vec3 B3Vec3_TEMP_STATIC_GEN_2;

    static private B3Vec3 B3Vec3_TEMP_STATIC_GEN_3;

    static private B3Vec3 B3Vec3_TEMP_STATIC_GEN_4;

    static private B3Vec3 B3Vec3_TEMP_STATIC_GEN_5;

    static private B3AABB B3AABB_TEMP_STATIC_GEN_0;

    static private B3Vec3 B3Vec3_TEMP_STATIC_GEN_6;

    static private B3Transform B3Transform_TEMP_STATIC_GEN_2;

    private static final java.util.ArrayList<B3DebugDrawEm> TEAVMC_CALLBACKS = new java.util.ArrayList<>();

    private int teavmcCallbackId = -1;

    private int teavmcRegisterCallback() {
        if (teavmcCallbackId < 0) {
            teavmcCallbackId = TEAVMC_CALLBACKS.size();
            TEAVMC_CALLBACKS.add(this);
        } else {
            TEAVMC_CALLBACKS.set(teavmcCallbackId, this);
        }
        return teavmcCallbackId;
    }

    private static abstract class TEAVMC_DrawShape_Function extends org.teavm.interop.Function {

        public abstract boolean call(int callbackId, long shape_addr, long transform_addr, int color);
    }

    @org.teavm.interop.Export(name = "teavmc_DrawShape")
    private static boolean teavmc_DrawShape(int callbackId, long shape_addr, long transform_addr, int color) {
        return TEAVMC_CALLBACKS.get(callbackId).internal_DrawShape(shape_addr, transform_addr, color);
    }

    private static abstract class TEAVMC_DrawSegment_Function extends org.teavm.interop.Function {

        public abstract void call(int callbackId, long p1_addr, long p2_addr, int color);
    }

    @org.teavm.interop.Export(name = "teavmc_DrawSegment")
    private static void teavmc_DrawSegment(int callbackId, long p1_addr, long p2_addr, int color) {
        TEAVMC_CALLBACKS.get(callbackId).internal_DrawSegment(p1_addr, p2_addr, color);
    }

    private static abstract class TEAVMC_DrawTransform_Function extends org.teavm.interop.Function {

        public abstract void call(int callbackId, long transform_addr);
    }

    @org.teavm.interop.Export(name = "teavmc_DrawTransform")
    private static void teavmc_DrawTransform(int callbackId, long transform_addr) {
        TEAVMC_CALLBACKS.get(callbackId).internal_DrawTransform(transform_addr);
    }

    private static abstract class TEAVMC_DrawPoint_Function extends org.teavm.interop.Function {

        public abstract void call(int callbackId, long p_addr, float size, int color);
    }

    @org.teavm.interop.Export(name = "teavmc_DrawPoint")
    private static void teavmc_DrawPoint(int callbackId, long p_addr, float size, int color) {
        TEAVMC_CALLBACKS.get(callbackId).internal_DrawPoint(p_addr, size, color);
    }

    private static abstract class TEAVMC_DrawSphere_Function extends org.teavm.interop.Function {

        public abstract void call(int callbackId, long p_addr, float radius, int color, float alpha);
    }

    @org.teavm.interop.Export(name = "teavmc_DrawSphere")
    private static void teavmc_DrawSphere(int callbackId, long p_addr, float radius, int color, float alpha) {
        TEAVMC_CALLBACKS.get(callbackId).internal_DrawSphere(p_addr, radius, color, alpha);
    }

    private static abstract class TEAVMC_DrawCapsule_Function extends org.teavm.interop.Function {

        public abstract void call(int callbackId, long p1_addr, long p2_addr, float radius, int color, float alpha);
    }

    @org.teavm.interop.Export(name = "teavmc_DrawCapsule")
    private static void teavmc_DrawCapsule(int callbackId, long p1_addr, long p2_addr, float radius, int color, float alpha) {
        TEAVMC_CALLBACKS.get(callbackId).internal_DrawCapsule(p1_addr, p2_addr, radius, color, alpha);
    }

    private static abstract class TEAVMC_DrawBounds_Function extends org.teavm.interop.Function {

        public abstract void call(int callbackId, long aabb_addr, int color);
    }

    @org.teavm.interop.Export(name = "teavmc_DrawBounds")
    private static void teavmc_DrawBounds(int callbackId, long aabb_addr, int color) {
        TEAVMC_CALLBACKS.get(callbackId).internal_DrawBounds(aabb_addr, color);
    }

    private static abstract class TEAVMC_DrawBox_Function extends org.teavm.interop.Function {

        public abstract void call(int callbackId, long extents_addr, long transform_addr, int color);
    }

    @org.teavm.interop.Export(name = "teavmc_DrawBox")
    private static void teavmc_DrawBox(int callbackId, long extents_addr, long transform_addr, int color) {
        TEAVMC_CALLBACKS.get(callbackId).internal_DrawBox(extents_addr, transform_addr, color);
    }

    @org.teavm.interop.Import(name = "teavmc_B3DebugDrawEm_setupCallback")
    private static native void setupCallback(long this_addr, int callbackId, TEAVMC_DrawShape_Function DrawShape_fp, TEAVMC_DrawSegment_Function DrawSegment_fp, TEAVMC_DrawTransform_Function DrawTransform_fp, TEAVMC_DrawPoint_Function DrawPoint_fp, TEAVMC_DrawSphere_Function DrawSphere_fp, TEAVMC_DrawCapsule_Function DrawCapsule_fp, TEAVMC_DrawBounds_Function DrawBounds_fp, TEAVMC_DrawBox_Function DrawBox_fp);

    static public final B3DebugDrawEm NULL = B3DebugDrawEm.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3DebugDrawEm(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3DebugDrawEm native_new() {
        return new B3DebugDrawEm((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_deletenative")
    public static native void internal_native_deleteNative(long this_addr);

    public void DrawWorld(B3World world, long maskBits) {
        internal_native_DrawWorld(native_address, world.native_address, maskBits);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_drawworld")
    public static native void internal_native_DrawWorld(long this_addr, long world_addr, long maskBits);

    public void SetDrawingBounds(B3AABB bounds) {
        internal_native_SetDrawingBounds(native_address, bounds.native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawingbounds")
    public static native void internal_native_SetDrawingBounds(long this_addr, long bounds_addr);

    public B3AABB GetDrawingBounds() {
        long addr = internal_native_GetDrawingBounds_addr(native_address);
        if (addr == 0)
            return B3AABB.NULL;
        if (B3AABB_TEMP_GEN_0 == null)
            B3AABB_TEMP_GEN_0 = B3AABB.native_new();
        B3AABB_TEMP_GEN_0.internal_reset(addr, false);
        return B3AABB_TEMP_GEN_0;
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawingbounds_addr")
    public static native long internal_native_GetDrawingBounds_addr(long this_addr);

    public void SetForceScale(float scale) {
        internal_native_SetForceScale(native_address, scale);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setforcescale")
    public static native void internal_native_SetForceScale(long this_addr, float scale);

    public float GetForceScale() {
        return internal_native_GetForceScale(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getforcescale")
    public static native float internal_native_GetForceScale(long this_addr);

    public void SetJointScale(float scale) {
        internal_native_SetJointScale(native_address, scale);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setjointscale")
    public static native void internal_native_SetJointScale(long this_addr, float scale);

    public float GetJointScale() {
        return internal_native_GetJointScale(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getjointscale")
    public static native float internal_native_GetJointScale(long this_addr);

    public void SetDrawShapes(boolean enabled) {
        internal_native_SetDrawShapes(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawshapes")
    public static native void internal_native_SetDrawShapes(long this_addr, boolean enabled);

    public boolean GetDrawShapes() {
        return internal_native_GetDrawShapes(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawshapes")
    public static native boolean internal_native_GetDrawShapes(long this_addr);

    public void SetDrawJoints(boolean enabled) {
        internal_native_SetDrawJoints(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawjoints")
    public static native void internal_native_SetDrawJoints(long this_addr, boolean enabled);

    public boolean GetDrawJoints() {
        return internal_native_GetDrawJoints(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawjoints")
    public static native boolean internal_native_GetDrawJoints(long this_addr);

    public void SetDrawJointExtras(boolean enabled) {
        internal_native_SetDrawJointExtras(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawjointextras")
    public static native void internal_native_SetDrawJointExtras(long this_addr, boolean enabled);

    public boolean GetDrawJointExtras() {
        return internal_native_GetDrawJointExtras(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawjointextras")
    public static native boolean internal_native_GetDrawJointExtras(long this_addr);

    public void SetDrawBounds(boolean enabled) {
        internal_native_SetDrawBounds(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawbounds")
    public static native void internal_native_SetDrawBounds(long this_addr, boolean enabled);

    public boolean GetDrawBounds() {
        return internal_native_GetDrawBounds(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawbounds")
    public static native boolean internal_native_GetDrawBounds(long this_addr);

    public void SetDrawMass(boolean enabled) {
        internal_native_SetDrawMass(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawmass")
    public static native void internal_native_SetDrawMass(long this_addr, boolean enabled);

    public boolean GetDrawMass() {
        return internal_native_GetDrawMass(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawmass")
    public static native boolean internal_native_GetDrawMass(long this_addr);

    public void SetDrawBodyNames(boolean enabled) {
        internal_native_SetDrawBodyNames(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawbodynames")
    public static native void internal_native_SetDrawBodyNames(long this_addr, boolean enabled);

    public boolean GetDrawBodyNames() {
        return internal_native_GetDrawBodyNames(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawbodynames")
    public static native boolean internal_native_GetDrawBodyNames(long this_addr);

    public void SetDrawContacts(boolean enabled) {
        internal_native_SetDrawContacts(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawcontacts")
    public static native void internal_native_SetDrawContacts(long this_addr, boolean enabled);

    public boolean GetDrawContacts() {
        return internal_native_GetDrawContacts(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawcontacts")
    public static native boolean internal_native_GetDrawContacts(long this_addr);

    public void SetDrawAnchorA(boolean enabled) {
        internal_native_SetDrawAnchorA(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawanchora")
    public static native void internal_native_SetDrawAnchorA(long this_addr, boolean enabled);

    public boolean GetDrawAnchorA() {
        return internal_native_GetDrawAnchorA(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawanchora")
    public static native boolean internal_native_GetDrawAnchorA(long this_addr);

    public void SetDrawGraphColors(boolean enabled) {
        internal_native_SetDrawGraphColors(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawgraphcolors")
    public static native void internal_native_SetDrawGraphColors(long this_addr, boolean enabled);

    public boolean GetDrawGraphColors() {
        return internal_native_GetDrawGraphColors(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawgraphcolors")
    public static native boolean internal_native_GetDrawGraphColors(long this_addr);

    public void SetDrawContactFeatures(boolean enabled) {
        internal_native_SetDrawContactFeatures(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawcontactfeatures")
    public static native void internal_native_SetDrawContactFeatures(long this_addr, boolean enabled);

    public boolean GetDrawContactFeatures() {
        return internal_native_GetDrawContactFeatures(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawcontactfeatures")
    public static native boolean internal_native_GetDrawContactFeatures(long this_addr);

    public void SetDrawContactNormals(boolean enabled) {
        internal_native_SetDrawContactNormals(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawcontactnormals")
    public static native void internal_native_SetDrawContactNormals(long this_addr, boolean enabled);

    public boolean GetDrawContactNormals() {
        return internal_native_GetDrawContactNormals(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawcontactnormals")
    public static native boolean internal_native_GetDrawContactNormals(long this_addr);

    public void SetDrawContactForces(boolean enabled) {
        internal_native_SetDrawContactForces(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawcontactforces")
    public static native void internal_native_SetDrawContactForces(long this_addr, boolean enabled);

    public boolean GetDrawContactForces() {
        return internal_native_GetDrawContactForces(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawcontactforces")
    public static native boolean internal_native_GetDrawContactForces(long this_addr);

    public void SetDrawFrictionForces(boolean enabled) {
        internal_native_SetDrawFrictionForces(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawfrictionforces")
    public static native void internal_native_SetDrawFrictionForces(long this_addr, boolean enabled);

    public boolean GetDrawFrictionForces() {
        return internal_native_GetDrawFrictionForces(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawfrictionforces")
    public static native boolean internal_native_GetDrawFrictionForces(long this_addr);

    public void SetDrawIslands(boolean enabled) {
        internal_native_SetDrawIslands(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_setdrawislands")
    public static native void internal_native_SetDrawIslands(long this_addr, boolean enabled);

    public boolean GetDrawIslands() {
        return internal_native_GetDrawIslands(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_getdrawislands")
    public static native boolean internal_native_GetDrawIslands(long this_addr);

    public B3DebugDrawEm() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
        setupCallback();
    }

    private void setupCallback() {
        int callbackId = teavmcRegisterCallback();
        setupCallback(native_address, callbackId, org.teavm.interop.Function.get(TEAVMC_DrawShape_Function.class, B3DebugDrawEm.class, "teavmc_DrawShape"), org.teavm.interop.Function.get(TEAVMC_DrawSegment_Function.class, B3DebugDrawEm.class, "teavmc_DrawSegment"), org.teavm.interop.Function.get(TEAVMC_DrawTransform_Function.class, B3DebugDrawEm.class, "teavmc_DrawTransform"), org.teavm.interop.Function.get(TEAVMC_DrawPoint_Function.class, B3DebugDrawEm.class, "teavmc_DrawPoint"), org.teavm.interop.Function.get(TEAVMC_DrawSphere_Function.class, B3DebugDrawEm.class, "teavmc_DrawSphere"), org.teavm.interop.Function.get(TEAVMC_DrawCapsule_Function.class, B3DebugDrawEm.class, "teavmc_DrawCapsule"), org.teavm.interop.Function.get(TEAVMC_DrawBounds_Function.class, B3DebugDrawEm.class, "teavmc_DrawBounds"), org.teavm.interop.Function.get(TEAVMC_DrawBox_Function.class, B3DebugDrawEm.class, "teavmc_DrawBox"));
    }

    protected boolean DrawShape(B3DebugShape shape, B3Transform transform, int color) {
        return false;
    }

    private boolean internal_DrawShape(long shape_addr, long transform_addr, int color) {
        if (B3DebugShape_TEMP_STATIC_GEN_0 == null)
            B3DebugShape_TEMP_STATIC_GEN_0 = B3DebugShape.native_new();
        B3DebugShape_TEMP_STATIC_GEN_0.internal_reset(shape_addr, false);
        if (B3Transform_TEMP_STATIC_GEN_0 == null)
            B3Transform_TEMP_STATIC_GEN_0 = B3Transform.native_new();
        B3Transform_TEMP_STATIC_GEN_0.internal_reset(transform_addr, false);
        return DrawShape(B3DebugShape_TEMP_STATIC_GEN_0, B3Transform_TEMP_STATIC_GEN_0, color);
    }

    protected void DrawSegment(B3Vec3 p1, B3Vec3 p2, int color) {
    }

    private void internal_DrawSegment(long p1_addr, long p2_addr, int color) {
        if (B3Vec3_TEMP_STATIC_GEN_0 == null)
            B3Vec3_TEMP_STATIC_GEN_0 = B3Vec3.native_new();
        B3Vec3_TEMP_STATIC_GEN_0.internal_reset(p1_addr, false);
        if (B3Vec3_TEMP_STATIC_GEN_1 == null)
            B3Vec3_TEMP_STATIC_GEN_1 = B3Vec3.native_new();
        B3Vec3_TEMP_STATIC_GEN_1.internal_reset(p2_addr, false);
        DrawSegment(B3Vec3_TEMP_STATIC_GEN_0, B3Vec3_TEMP_STATIC_GEN_1, color);
    }

    protected void DrawTransform(B3Transform transform) {
    }

    private void internal_DrawTransform(long transform_addr) {
        if (B3Transform_TEMP_STATIC_GEN_1 == null)
            B3Transform_TEMP_STATIC_GEN_1 = B3Transform.native_new();
        B3Transform_TEMP_STATIC_GEN_1.internal_reset(transform_addr, false);
        DrawTransform(B3Transform_TEMP_STATIC_GEN_1);
    }

    protected void DrawPoint(B3Vec3 p, float size, int color) {
    }

    private void internal_DrawPoint(long p_addr, float size, int color) {
        if (B3Vec3_TEMP_STATIC_GEN_2 == null)
            B3Vec3_TEMP_STATIC_GEN_2 = B3Vec3.native_new();
        B3Vec3_TEMP_STATIC_GEN_2.internal_reset(p_addr, false);
        DrawPoint(B3Vec3_TEMP_STATIC_GEN_2, size, color);
    }

    protected void DrawSphere(B3Vec3 p, float radius, int color, float alpha) {
    }

    private void internal_DrawSphere(long p_addr, float radius, int color, float alpha) {
        if (B3Vec3_TEMP_STATIC_GEN_3 == null)
            B3Vec3_TEMP_STATIC_GEN_3 = B3Vec3.native_new();
        B3Vec3_TEMP_STATIC_GEN_3.internal_reset(p_addr, false);
        DrawSphere(B3Vec3_TEMP_STATIC_GEN_3, radius, color, alpha);
    }

    protected void DrawCapsule(B3Vec3 p1, B3Vec3 p2, float radius, int color, float alpha) {
    }

    private void internal_DrawCapsule(long p1_addr, long p2_addr, float radius, int color, float alpha) {
        if (B3Vec3_TEMP_STATIC_GEN_4 == null)
            B3Vec3_TEMP_STATIC_GEN_4 = B3Vec3.native_new();
        B3Vec3_TEMP_STATIC_GEN_4.internal_reset(p1_addr, false);
        if (B3Vec3_TEMP_STATIC_GEN_5 == null)
            B3Vec3_TEMP_STATIC_GEN_5 = B3Vec3.native_new();
        B3Vec3_TEMP_STATIC_GEN_5.internal_reset(p2_addr, false);
        DrawCapsule(B3Vec3_TEMP_STATIC_GEN_4, B3Vec3_TEMP_STATIC_GEN_5, radius, color, alpha);
    }

    protected void DrawBounds(B3AABB aabb, int color) {
    }

    private void internal_DrawBounds(long aabb_addr, int color) {
        if (B3AABB_TEMP_STATIC_GEN_0 == null)
            B3AABB_TEMP_STATIC_GEN_0 = B3AABB.native_new();
        B3AABB_TEMP_STATIC_GEN_0.internal_reset(aabb_addr, false);
        DrawBounds(B3AABB_TEMP_STATIC_GEN_0, color);
    }

    protected void DrawBox(B3Vec3 extents, B3Transform transform, int color) {
    }

    private void internal_DrawBox(long extents_addr, long transform_addr, int color) {
        if (B3Vec3_TEMP_STATIC_GEN_6 == null)
            B3Vec3_TEMP_STATIC_GEN_6 = B3Vec3.native_new();
        B3Vec3_TEMP_STATIC_GEN_6.internal_reset(extents_addr, false);
        if (B3Transform_TEMP_STATIC_GEN_2 == null)
            B3Transform_TEMP_STATIC_GEN_2 = B3Transform.native_new();
        B3Transform_TEMP_STATIC_GEN_2.internal_reset(transform_addr, false);
        DrawBox(B3Vec3_TEMP_STATIC_GEN_6, B3Transform_TEMP_STATIC_GEN_2, color);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3debugdrawem_create_addr")
    public static native long internal_native_create_addr();
}
