/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3ShapeDef extends NativeObject {

    private B3SurfaceMaterial B3SurfaceMaterial_TEMP_GEN_0;

    private B3Filter B3Filter_TEMP_GEN_0;

    static public final B3ShapeDef NULL = B3ShapeDef.native_new();

    public B3ShapeDef() {
        long addr = internal_native_create_addr();
        internal_reset(addr, true);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_create_addr")
    public static native long internal_native_create_addr();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3ShapeDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3ShapeDef native_new() {
        return new B3ShapeDef((byte) 0, (char) 0);
    }

    protected void deleteNative() {
        internal_native_deleteNative(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_deletenative")
    public static native void internal_native_deleteNative(long this_addr);

    public B3SurfaceMaterial GetBaseMaterial() {
        long addr = internal_native_GetBaseMaterial_addr(native_address);
        if (addr == 0)
            return B3SurfaceMaterial.NULL;
        if (B3SurfaceMaterial_TEMP_GEN_0 == null)
            B3SurfaceMaterial_TEMP_GEN_0 = B3SurfaceMaterial.native_new();
        B3SurfaceMaterial_TEMP_GEN_0.internal_reset(addr, false);
        return B3SurfaceMaterial_TEMP_GEN_0;
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getbasematerial_addr")
    public static native long internal_native_GetBaseMaterial_addr(long this_addr);

    public void SetBaseMaterial(B3SurfaceMaterial material) {
        internal_native_SetBaseMaterial(native_address, material.native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setbasematerial")
    public static native void internal_native_SetBaseMaterial(long this_addr, long material_addr);

    public float GetDensity() {
        return internal_native_GetDensity(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getdensity")
    public static native float internal_native_GetDensity(long this_addr);

    public void SetDensity(float density) {
        internal_native_SetDensity(native_address, density);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setdensity")
    public static native void internal_native_SetDensity(long this_addr, float density);

    public float GetExplosionScale() {
        return internal_native_GetExplosionScale(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getexplosionscale")
    public static native float internal_native_GetExplosionScale(long this_addr);

    public void SetExplosionScale(float scale) {
        internal_native_SetExplosionScale(native_address, scale);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setexplosionscale")
    public static native void internal_native_SetExplosionScale(long this_addr, float scale);

    public B3Filter GetFilter() {
        long addr = internal_native_GetFilter_addr(native_address);
        if (addr == 0)
            return B3Filter.NULL;
        if (B3Filter_TEMP_GEN_0 == null)
            B3Filter_TEMP_GEN_0 = B3Filter.native_new();
        B3Filter_TEMP_GEN_0.internal_reset(addr, false);
        return B3Filter_TEMP_GEN_0;
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getfilter_addr")
    public static native long internal_native_GetFilter_addr(long this_addr);

    public void SetFilter(B3Filter filter) {
        internal_native_SetFilter(native_address, filter.native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setfilter")
    public static native void internal_native_SetFilter(long this_addr, long filter_addr);

    public boolean GetEnableCustomFiltering() {
        return internal_native_GetEnableCustomFiltering(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getenablecustomfiltering")
    public static native boolean internal_native_GetEnableCustomFiltering(long this_addr);

    public void SetEnableCustomFiltering(boolean enabled) {
        internal_native_SetEnableCustomFiltering(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setenablecustomfiltering")
    public static native void internal_native_SetEnableCustomFiltering(long this_addr, boolean enabled);

    public boolean GetIsSensor() {
        return internal_native_GetIsSensor(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getissensor")
    public static native boolean internal_native_GetIsSensor(long this_addr);

    public void SetIsSensor(boolean sensor) {
        internal_native_SetIsSensor(native_address, sensor);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setissensor")
    public static native void internal_native_SetIsSensor(long this_addr, boolean sensor);

    public boolean GetEnableSensorEvents() {
        return internal_native_GetEnableSensorEvents(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getenablesensorevents")
    public static native boolean internal_native_GetEnableSensorEvents(long this_addr);

    public void SetEnableSensorEvents(boolean enabled) {
        internal_native_SetEnableSensorEvents(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setenablesensorevents")
    public static native void internal_native_SetEnableSensorEvents(long this_addr, boolean enabled);

    public boolean GetEnableContactEvents() {
        return internal_native_GetEnableContactEvents(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getenablecontactevents")
    public static native boolean internal_native_GetEnableContactEvents(long this_addr);

    public void SetEnableContactEvents(boolean enabled) {
        internal_native_SetEnableContactEvents(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setenablecontactevents")
    public static native void internal_native_SetEnableContactEvents(long this_addr, boolean enabled);

    public boolean GetEnableHitEvents() {
        return internal_native_GetEnableHitEvents(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getenablehitevents")
    public static native boolean internal_native_GetEnableHitEvents(long this_addr);

    public void SetEnableHitEvents(boolean enabled) {
        internal_native_SetEnableHitEvents(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setenablehitevents")
    public static native void internal_native_SetEnableHitEvents(long this_addr, boolean enabled);

    public boolean GetEnablePreSolveEvents() {
        return internal_native_GetEnablePreSolveEvents(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getenablepresolveevents")
    public static native boolean internal_native_GetEnablePreSolveEvents(long this_addr);

    public void SetEnablePreSolveEvents(boolean enabled) {
        internal_native_SetEnablePreSolveEvents(native_address, enabled);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setenablepresolveevents")
    public static native void internal_native_SetEnablePreSolveEvents(long this_addr, boolean enabled);

    public boolean GetInvokeContactCreation() {
        return internal_native_GetInvokeContactCreation(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getinvokecontactcreation")
    public static native boolean internal_native_GetInvokeContactCreation(long this_addr);

    public void SetInvokeContactCreation(boolean invokeContactCreation) {
        internal_native_SetInvokeContactCreation(native_address, invokeContactCreation);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setinvokecontactcreation")
    public static native void internal_native_SetInvokeContactCreation(long this_addr, boolean invokeContactCreation);

    public boolean GetUpdateBodyMass() {
        return internal_native_GetUpdateBodyMass(native_address);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_getupdatebodymass")
    public static native boolean internal_native_GetUpdateBodyMass(long this_addr);

    public void SetUpdateBodyMass(boolean updateBodyMass) {
        internal_native_SetUpdateBodyMass(native_address, updateBodyMass);
    }

    @org.teavm.interop.Import(name = "com_github_xpenatan_box3d_b3shapedef_setupdatebodymass")
    public static native void internal_native_SetUpdateBodyMass(long this_addr, boolean updateBodyMass);
}
