/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3ManifoldPoint {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetAnchorA_addr(long this_addr);

    public static native long internal_native_GetAnchorB_addr(long this_addr);

    public static native float internal_native_GetSeparation(long this_addr);

    public static native float internal_native_GetBaseSeparation(long this_addr);

    public static native float internal_native_GetNormalImpulse(long this_addr);

    public static native float internal_native_GetTotalNormalImpulse(long this_addr);

    public static native float internal_native_GetNormalVelocity(long this_addr);

    public static native int internal_native_GetFeatureId(long this_addr);

    public static native int internal_native_GetTriangleIndex(long this_addr);

    public static native boolean internal_native_GetPersisted(long this_addr);
}
