/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3BodyMoveEvent {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetBodyId(long this_addr);

    public static native long internal_native_GetTransform_addr(long this_addr);

    public static native boolean internal_native_GetFellAsleep(long this_addr);
}
