/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3Profile {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native float internal_native_GetStep(long this_addr);

    public static native float internal_native_GetPairs(long this_addr);

    public static native float internal_native_GetCollide(long this_addr);

    public static native float internal_native_GetSolve(long this_addr);

    public static native float internal_native_GetSolverSetup(long this_addr);

    public static native float internal_native_GetConstraints(long this_addr);

    public static native float internal_native_GetPrepareConstraints(long this_addr);

    public static native float internal_native_GetIntegrateVelocities(long this_addr);

    public static native float internal_native_GetWarmStart(long this_addr);

    public static native float internal_native_GetSolveImpulses(long this_addr);

    public static native float internal_native_GetIntegratePositions(long this_addr);

    public static native float internal_native_GetRelaxImpulses(long this_addr);

    public static native float internal_native_GetApplyRestitution(long this_addr);

    public static native float internal_native_GetStoreImpulses(long this_addr);

    public static native float internal_native_GetSplitIslands(long this_addr);

    public static native float internal_native_GetTransforms(long this_addr);

    public static native float internal_native_GetSensorHits(long this_addr);

    public static native float internal_native_GetJointEvents(long this_addr);

    public static native float internal_native_GetHitEvents(long this_addr);

    public static native float internal_native_GetRefit(long this_addr);

    public static native float internal_native_GetBullets(long this_addr);

    public static native float internal_native_GetSleepIslands(long this_addr);

    public static native float internal_native_GetSensors(long this_addr);
}
