/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3Quat {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_float_float_float_float_addr(float x, float y, float z, float w);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetV_addr(long this_addr);

    public static native void internal_native_SetV(long this_addr, long value_addr);

    public static native float internal_native_GetS(long this_addr);

    public static native void internal_native_SetS(long this_addr, float s);

    public static native void internal_native_Set(long this_addr, float x, float y, float z, float w);
}
