/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3MeshTriangle {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetA_addr(long this_addr);

    public static native long internal_native_GetB_addr(long this_addr);

    public static native long internal_native_GetC_addr(long this_addr);

    public static native int internal_native_GetTriangleIndex(long this_addr);
}
