/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3Timer {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native float internal_native_GetMilliseconds(long this_addr);

    public static native float internal_native_GetMillisecondsAndReset(long this_addr);

    public static native void internal_native_Reset(long this_addr);

    public static native long internal_native_GetTicks(long this_addr);
}
