/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3World {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_B3WorldDef_addr(long def_addr);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetId(long this_addr);

    public static native boolean internal_native_IsValid(long this_addr);

    public static native void internal_native_Destroy(long this_addr);

    public static native void internal_native_Step(long this_addr, float timeStep, int subStepCount);

    public static native long internal_native_GetBounds_addr(long this_addr);

    public static native long internal_native_GetGravity_addr(long this_addr);

    public static native void internal_native_SetGravity(long this_addr, long gravity_addr);

    public static native boolean internal_native_IsSleepingEnabled(long this_addr);

    public static native void internal_native_EnableSleeping(long this_addr, boolean enabled);

    public static native boolean internal_native_IsWarmStartingEnabled(long this_addr);

    public static native void internal_native_EnableWarmStarting(long this_addr, boolean enabled);

    public static native boolean internal_native_IsContinuousEnabled(long this_addr);

    public static native void internal_native_EnableContinuous(long this_addr, boolean enabled);

    public static native float internal_native_GetContactRecycleDistance(long this_addr);

    public static native void internal_native_SetContactRecycleDistance(long this_addr, float recycleDistance);

    public static native void internal_native_SetContactTuning(long this_addr, float hertz, float dampingRatio, float contactSpeed);

    public static native int internal_native_GetWorkerCount(long this_addr);

    public static native void internal_native_SetWorkerCount(long this_addr, int workerCount);

    public static native int internal_native_GetAwakeBodyCount(long this_addr);

    public static native long internal_native_CreateBody_addr(long this_addr, long def_addr);

    public static native long internal_native_CreateDistanceJoint_addr(long this_addr, long def_addr);

    public static native long internal_native_CreateMotorJoint_addr(long this_addr, long def_addr);

    public static native long internal_native_CreateParallelJoint_addr(long this_addr, long def_addr);

    public static native long internal_native_CreatePrismaticJoint_addr(long this_addr, long def_addr);

    public static native long internal_native_CreateSphericalJoint_addr(long this_addr, long def_addr);

    public static native long internal_native_CreateRevoluteJoint_addr(long this_addr, long def_addr);

    public static native long internal_native_CreateWeldJoint_addr(long this_addr, long def_addr);

    public static native long internal_native_CreateFilterJoint_addr(long this_addr, long def_addr);

    public static native long internal_native_CreateWheelJoint_addr(long this_addr, long def_addr);

    public static native long internal_native_GetBodyEvents_addr(long this_addr);

    public static native long internal_native_GetSensorEvents_addr(long this_addr);

    public static native long internal_native_GetContactEvents_addr(long this_addr);

    public static native long internal_native_CastRayClosest_addr(long this_addr, long origin_addr, long translation_addr, long filter_addr);
}
