/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3ContactId {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_int_int_int_addr(int value0, int value1, int value2);

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_GetValue0(long this_addr);

    public static native int internal_native_GetValue1(long this_addr);

    public static native int internal_native_GetValue2(long this_addr);

    public static native boolean internal_native_IsNull(long this_addr);
}
