/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3Body {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_long_addr(long bodyId);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_GetId(long this_addr);

    public static native boolean internal_native_IsValid(long this_addr);

    public static native void internal_native_Destroy(long this_addr);

    public static native int internal_native_GetType(long this_addr);

    public static native void internal_native_SetType(long this_addr, int type);

    public static native long internal_native_GetPosition_addr(long this_addr);

    public static native long internal_native_GetRotation_addr(long this_addr);

    public static native long internal_native_GetTransform_addr(long this_addr);

    public static native void internal_native_SetTransform(long this_addr, long position_addr, long rotation_addr);

    public static native void internal_native_SetTargetTransform(long this_addr, long position_addr, long rotation_addr, float timeStep, boolean wake);

    public static native long internal_native_GetLinearVelocity_addr(long this_addr);

    public static native void internal_native_SetLinearVelocity(long this_addr, long velocity_addr);

    public static native long internal_native_GetAngularVelocity_addr(long this_addr);

    public static native void internal_native_SetAngularVelocity(long this_addr, long velocity_addr);

    public static native void internal_native_ApplyForce(long this_addr, long force_addr, long point_addr, boolean wake);

    public static native void internal_native_ApplyForceToCenter(long this_addr, long force_addr, boolean wake);

    public static native void internal_native_ApplyTorque(long this_addr, long torque_addr, boolean wake);

    public static native void internal_native_ApplyLinearImpulse(long this_addr, long impulse_addr, long point_addr, boolean wake);

    public static native void internal_native_ApplyLinearImpulseToCenter(long this_addr, long impulse_addr, boolean wake);

    public static native void internal_native_ApplyAngularImpulse(long this_addr, long impulse_addr, boolean wake);

    public static native float internal_native_GetMass(long this_addr);

    public static native float internal_native_GetInverseMass(long this_addr);

    public static native void internal_native_ApplyMassFromShapes(long this_addr);

    public static native float internal_native_GetLinearDamping(long this_addr);

    public static native void internal_native_SetLinearDamping(long this_addr, float damping);

    public static native float internal_native_GetAngularDamping(long this_addr);

    public static native void internal_native_SetAngularDamping(long this_addr, float damping);

    public static native float internal_native_GetGravityScale(long this_addr);

    public static native void internal_native_SetGravityScale(long this_addr, float scale);

    public static native boolean internal_native_IsAwake(long this_addr);

    public static native void internal_native_SetAwake(long this_addr, boolean awake);

    public static native boolean internal_native_IsEnabled(long this_addr);

    public static native void internal_native_Disable(long this_addr);

    public static native void internal_native_Enable(long this_addr);

    public static native long internal_native_GetMotionLocks_addr(long this_addr);

    public static native void internal_native_SetMotionLocks(long this_addr, long locks_addr);

    public static native boolean internal_native_IsBullet(long this_addr);

    public static native void internal_native_SetBullet(long this_addr, boolean bullet);

    public static native int internal_native_GetShapeCount(long this_addr);

    public static native long internal_native_ComputeAABB_addr(long this_addr);

    public static native long internal_native_CreateSphereShape_addr(long this_addr, long def_addr, long sphere_addr);

    public static native long internal_native_CreateCapsuleShape_addr(long this_addr, long def_addr, long capsule_addr);

    public static native long internal_native_CreateHullShape_addr(long this_addr, long def_addr, long hull_addr);
}
