/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3DynamicTree {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_int_addr(int proxyCapacity);

    public static native void internal_native_deleteNative(long this_addr);

    public static native long internal_native_Load_addr(String fileName, float scale);

    public static native boolean internal_native_IsValid(long this_addr);

    public static native void internal_native_Destroy(long this_addr);

    public static native int internal_native_CreateProxy(long this_addr, long aabb_addr, long categoryBits, long userData);

    public static native void internal_native_DestroyProxy(long this_addr, int proxyId);

    public static native void internal_native_MoveProxy(long this_addr, int proxyId, long aabb_addr);

    public static native void internal_native_EnlargeProxy(long this_addr, int proxyId, long aabb_addr);

    public static native void internal_native_SetCategoryBits(long this_addr, int proxyId, long categoryBits);

    public static native long internal_native_GetCategoryBits(long this_addr, int proxyId);

    public static native long internal_native_GetUserData(long this_addr, int proxyId);

    public static native long internal_native_GetAABB_addr(long this_addr, int proxyId);

    public static native long internal_native_Query_addr(long this_addr, long aabb_addr, long maskBits, boolean requireAllBits, long callback_addr);

    public static native long internal_native_QueryClosest_addr(long this_addr, long point_addr, long maskBits, boolean requireAllBits, long callback_addr, float minDistanceSquared);

    public static native long internal_native_RayCast_addr(long this_addr, long input_addr, long maskBits, boolean requireAllBits, long callback_addr);

    public static native long internal_native_BoxCast_addr(long this_addr, long input_addr, long maskBits, boolean requireAllBits, long callback_addr);

    public static native int internal_native_GetHeight(long this_addr);

    public static native float internal_native_GetAreaRatio(long this_addr);

    public static native long internal_native_GetRootBounds_addr(long this_addr);

    public static native int internal_native_GetProxyCount(long this_addr);

    public static native int internal_native_Rebuild(long this_addr, boolean fullBuild);

    public static native int internal_native_GetByteCount(long this_addr);

    public static native void internal_native_Validate(long this_addr);

    public static native void internal_native_ValidateNoEnlarged(long this_addr);

    public static native void internal_native_Save(long this_addr, String fileName);
}
