/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3Counters {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_GetBodyCount(long this_addr);

    public static native int internal_native_GetShapeCount(long this_addr);

    public static native int internal_native_GetContactCount(long this_addr);

    public static native int internal_native_GetJointCount(long this_addr);

    public static native int internal_native_GetIslandCount(long this_addr);

    public static native int internal_native_GetStackUsed(long this_addr);

    public static native int internal_native_GetArenaCapacity(long this_addr);

    public static native int internal_native_GetStaticTreeHeight(long this_addr);

    public static native int internal_native_GetTreeHeight(long this_addr);

    public static native int internal_native_GetSatCallCount(long this_addr);

    public static native int internal_native_GetSatCacheHitCount(long this_addr);

    public static native int internal_native_GetByteCount(long this_addr);

    public static native int internal_native_GetTaskCount(long this_addr);

    public static native int internal_native_GetColorCount(long this_addr, int index);

    public static native int internal_native_GetManifoldCount(long this_addr, int index);

    public static native int internal_native_GetAwakeContactCount(long this_addr);

    public static native int internal_native_GetRecycledContactCount(long this_addr);

    public static native int internal_native_GetDistanceIterations(long this_addr);

    public static native int internal_native_GetPushBackIterations(long this_addr);

    public static native int internal_native_GetRootIterations(long this_addr);
}
