/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3 {

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_StaticBody();

    public static native int internal_native_KinematicBody();

    public static native int internal_native_DynamicBody();

    public static native int internal_native_CapsuleShape();

    public static native int internal_native_CompoundShape();

    public static native int internal_native_HeightShape();

    public static native int internal_native_HullShape();

    public static native int internal_native_MeshShape();

    public static native int internal_native_SphereShape();

    public static native int internal_native_GetWorldCount();

    public static native int internal_native_GetMaxWorldCount();

    public static native long internal_native_DefaultMaskBits();
}
