/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3RecPlayerInfo {

    public static native long internal_native_create_addr();

    public static native void internal_native_deleteNative(long this_addr);

    public static native int internal_native_GetFrameCount(long this_addr);

    public static native int internal_native_GetWorkerCount(long this_addr);

    public static native float internal_native_GetTimeStep(long this_addr);

    public static native int internal_native_GetSubStepCount(long this_addr);

    public static native float internal_native_GetLengthScale(long this_addr);

    public static native long internal_native_GetBounds_addr(long this_addr);
}
