/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d.natives;

import com.github.xpenatan.box3d.*;

final public class JNI_B3RecPlayer {

    public static native long internal_native_create_addr();

    public static native long internal_native_create_B3ByteArray_int_addr(long data_addr, int workerCount);

    public static native void internal_native_deleteNative(long this_addr);

    public static native boolean internal_native_IsValid(long this_addr);

    public static native void internal_native_Destroy(long this_addr);

    public static native boolean internal_native_StepFrame(long this_addr);

    public static native void internal_native_SubStepFrame(long this_addr);

    public static native void internal_native_Restart(long this_addr);

    public static native void internal_native_SeekFrame(long this_addr, int targetFrame);

    public static native long internal_native_GetWorld_addr(long this_addr);

    public static native long internal_native_GetWorldId(long this_addr);

    public static native int internal_native_GetFrame(long this_addr);

    public static native int internal_native_GetFrameCount(long this_addr);

    public static native boolean internal_native_IsAtEnd(long this_addr);

    public static native boolean internal_native_IsAtPreStep(long this_addr);

    public static native boolean internal_native_HasDiverged(long this_addr);

    public static native long internal_native_GetInfo_addr(long this_addr);

    public static native int internal_native_GetDivergeFrame(long this_addr);

    public static native void internal_native_SetWorkerCount(long this_addr, int count);

    public static native void internal_native_SetKeyframePolicy(long this_addr, long budgetBytes, int minIntervalFrames);

    public static native long internal_native_GetKeyframeBudget(long this_addr);

    public static native int internal_native_GetKeyframeMinInterval(long this_addr);

    public static native int internal_native_GetKeyframeInterval(long this_addr);

    public static native long internal_native_GetKeyframeBytes(long this_addr);

    public static native int internal_native_GetBodyCount(long this_addr);

    public static native long internal_native_GetBodyId(long this_addr, int index);

    public static native void internal_native_SetDebugShapeCallbacks(long this_addr);

    public static native void internal_native_DrawFrameQueries(long this_addr, long draw_addr, int queryIndex, int selectedIndex);

    public static native int internal_native_GetFrameQueryCount(long this_addr);

    public static native long internal_native_GetFrameQuery_addr(long this_addr, int index);

    public static native long internal_native_GetFrameQueryHit_addr(long this_addr, int queryIndex, int hitIndex);
}
