/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3BodyDef extends NativeObject {

    static public final B3BodyDef NULL = B3BodyDef.native_new();

    public B3BodyDef() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3BodyDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3BodyDef native_new() {
        return new B3BodyDef((byte) 0, (char) 0);
    }

    public int GetType() {
        return 0;
    }

    public void SetType(int type) {
    }

    public B3Vec3 GetPosition() {
        return null;
    }

    public void SetPosition(B3Vec3 position) {
    }

    public B3Quat GetRotation() {
        return null;
    }

    public void SetRotation(B3Quat rotation) {
    }

    public B3Vec3 GetLinearVelocity() {
        return null;
    }

    public void SetLinearVelocity(B3Vec3 velocity) {
    }

    public B3Vec3 GetAngularVelocity() {
        return null;
    }

    public void SetAngularVelocity(B3Vec3 velocity) {
    }

    public float GetLinearDamping() {
        return 0;
    }

    public void SetLinearDamping(float damping) {
    }

    public float GetAngularDamping() {
        return 0;
    }

    public void SetAngularDamping(float damping) {
    }

    public float GetGravityScale() {
        return 0;
    }

    public void SetGravityScale(float scale) {
    }

    public float GetSleepThreshold() {
        return 0;
    }

    public void SetSleepThreshold(float threshold) {
    }

    public B3MotionLocks GetMotionLocks() {
        return null;
    }

    public void SetMotionLocks(B3MotionLocks locks) {
    }

    public boolean GetEnableSleep() {
        return false;
    }

    public void SetEnableSleep(boolean enabled) {
    }

    public boolean GetIsAwake() {
        return false;
    }

    public void SetIsAwake(boolean awake) {
    }

    public boolean GetIsBullet() {
        return false;
    }

    public void SetIsBullet(boolean bullet) {
    }

    public boolean GetIsEnabled() {
        return false;
    }

    public void SetIsEnabled(boolean enabled) {
    }

    public boolean GetAllowFastRotation() {
        return false;
    }

    public void SetAllowFastRotation(boolean allowFastRotation) {
    }

    public boolean GetEnableContactRecycling() {
        return false;
    }

    public void SetEnableContactRecycling(boolean enableContactRecycling) {
    }
}
