/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3Body extends NativeObject {

    static public final B3Body NULL = B3Body.native_new();

    public B3Body() {
    }

    public B3Body(long bodyId) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Body(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Body native_new() {
        return new B3Body((byte) 0, (char) 0);
    }

    public long GetId() {
        return 0;
    }

    public boolean IsValid() {
        return false;
    }

    public void Destroy() {
    }

    public int GetType() {
        return 0;
    }

    public void SetType(int type) {
    }

    public B3Vec3 GetPosition() {
        return null;
    }

    public B3Quat GetRotation() {
        return null;
    }

    public B3Transform GetTransform() {
        return null;
    }

    public void SetTransform(B3Vec3 position, B3Quat rotation) {
    }

    public void SetTargetTransform(B3Vec3 position, B3Quat rotation, float timeStep, boolean wake) {
    }

    public B3Vec3 GetLinearVelocity() {
        return null;
    }

    public void SetLinearVelocity(B3Vec3 velocity) {
    }

    public B3Vec3 GetAngularVelocity() {
        return null;
    }

    public void SetAngularVelocity(B3Vec3 velocity) {
    }

    public void ApplyForce(B3Vec3 force, B3Vec3 point, boolean wake) {
    }

    public void ApplyForceToCenter(B3Vec3 force, boolean wake) {
    }

    public void ApplyTorque(B3Vec3 torque, boolean wake) {
    }

    public void ApplyLinearImpulse(B3Vec3 impulse, B3Vec3 point, boolean wake) {
    }

    public void ApplyLinearImpulseToCenter(B3Vec3 impulse, boolean wake) {
    }

    public void ApplyAngularImpulse(B3Vec3 impulse, boolean wake) {
    }

    public float GetMass() {
        return 0;
    }

    public float GetInverseMass() {
        return 0;
    }

    public void ApplyMassFromShapes() {
    }

    public float GetLinearDamping() {
        return 0;
    }

    public void SetLinearDamping(float damping) {
    }

    public float GetAngularDamping() {
        return 0;
    }

    public void SetAngularDamping(float damping) {
    }

    public float GetGravityScale() {
        return 0;
    }

    public void SetGravityScale(float scale) {
    }

    public boolean IsAwake() {
        return false;
    }

    public void SetAwake(boolean awake) {
    }

    public boolean IsEnabled() {
        return false;
    }

    public void Disable() {
    }

    public void Enable() {
    }

    public B3MotionLocks GetMotionLocks() {
        return null;
    }

    public void SetMotionLocks(B3MotionLocks locks) {
    }

    public boolean IsBullet() {
        return false;
    }

    public void SetBullet(boolean bullet) {
    }

    public int GetShapeCount() {
        return 0;
    }

    public B3AABB ComputeAABB() {
        return null;
    }

    public B3Shape CreateSphereShape(B3ShapeDef def, B3Sphere sphere) {
        return null;
    }

    public B3Shape CreateCapsuleShape(B3ShapeDef def, B3Capsule capsule) {
        return null;
    }

    public B3Shape CreateHullShape(B3ShapeDef def, B3Hull hull) {
        return null;
    }
}
