/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3BoxCastInput extends NativeObject {

    static public final B3BoxCastInput NULL = B3BoxCastInput.native_new();

    public B3BoxCastInput() {
    }

    public B3BoxCastInput(B3AABB box, B3Vec3 translation, float maxFraction) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3BoxCastInput(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3BoxCastInput native_new() {
        return new B3BoxCastInput((byte) 0, (char) 0);
    }

    public B3AABB GetBox() {
        return null;
    }

    public void SetBox(B3AABB box) {
    }

    public B3Vec3 GetTranslation() {
        return null;
    }

    public void SetTranslation(B3Vec3 translation) {
    }

    public float GetMaxFraction() {
        return 0;
    }

    public void SetMaxFraction(float fraction) {
    }
}
