/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3CastResult extends NativeObject {

    static public final B3CastResult NULL = B3CastResult.native_new();

    public B3CastResult() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3CastResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3CastResult native_new() {
        return new B3CastResult((byte) 0, (char) 0);
    }

    public long GetShapeId() {
        return 0;
    }

    public B3Vec3 GetPoint() {
        return null;
    }

    public B3Vec3 GetNormal() {
        return null;
    }

    public float GetFraction() {
        return 0;
    }

    public long GetUserMaterialId() {
        return 0;
    }

    public int GetTriangleIndex() {
        return 0;
    }

    public int GetChildIndex() {
        return 0;
    }
}
