/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3CompoundDef extends NativeObject {

    static public final B3CompoundDef NULL = B3CompoundDef.native_new();

    public B3CompoundDef(int capsuleCapacity, int hullCapacity, int meshCapacity, int sphereCapacity) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3CompoundDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3CompoundDef native_new() {
        return new B3CompoundDef((byte) 0, (char) 0);
    }

    public void AddCapsule(B3Capsule capsule, B3SurfaceMaterial material) {
    }

    public void AddHull(B3Hull hull, B3Transform transform, B3SurfaceMaterial material) {
    }

    public void AddMesh(B3Mesh mesh, B3Transform transform, B3Vec3 scale, B3SurfaceMaterialArray materials) {
    }

    public void AddSphere(B3Sphere sphere, B3SurfaceMaterial material) {
    }

    public int GetCapsuleCount() {
        return 0;
    }

    public int GetHullCount() {
        return 0;
    }

    public int GetMeshCount() {
        return 0;
    }

    public int GetSphereCount() {
        return 0;
    }
}
