/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3Collision extends NativeObject {

    static public final B3Collision NULL = B3Collision.native_new();

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Collision(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Collision native_new() {
        return new B3Collision((byte) 0, (char) 0);
    }

    public static B3LocalManifold CollideSpheres(int capacity, B3Sphere sphereA, B3Sphere sphereB, B3Transform transformBtoA) {
        return null;
    }

    public static B3LocalManifold CollideCapsuleAndSphere(int capacity, B3Capsule capsuleA, B3Sphere sphereB, B3Transform transformBtoA) {
        return null;
    }

    public static B3LocalManifold CollideHullAndSphere(int capacity, B3Hull hullA, B3Sphere sphereB, B3Transform transformBtoA) {
        return null;
    }

    public static B3LocalManifold CollideCapsules(int capacity, B3Capsule capsuleA, B3Capsule capsuleB, B3Transform transformBtoA) {
        return null;
    }

    public static B3LocalManifold CollideHullAndCapsule(int capacity, B3Hull hullA, B3Capsule capsuleB, B3Transform transformBtoA) {
        return null;
    }

    public static B3LocalManifold CollideHulls(int capacity, B3Hull hullA, B3Hull hullB, B3Transform transformBtoA) {
        return null;
    }

    public static B3LocalManifold CollideTriangleAndSphere(int capacity, B3Vec3Array triangleA, B3Sphere sphereB) {
        return null;
    }

    public static B3LocalManifold CollideTriangleAndCapsule(int capacity, B3Vec3Array triangleA, B3Capsule capsuleB) {
        return null;
    }

    public static B3LocalManifold CollideTriangleAndHull(int capacity, B3Vec3Array triangleA, int triangleFlags, B3Hull hullB, boolean enableSpeculative) {
        return null;
    }

    public static B3DistanceOutput ShapeDistance(B3ShapeProxy proxyA, B3ShapeProxy proxyB, B3Transform transformBtoA, boolean useRadii) {
        return null;
    }

    public static B3CastOutput ShapeCast(B3ShapeProxy proxyA, B3ShapeProxy proxyB, B3Transform transformBtoA, B3Vec3 translationB, float maxFraction, boolean canEncroach) {
        return null;
    }

    public static B3TOIOutput TimeOfImpact(B3ShapeProxy proxyA, B3ShapeProxy proxyB, B3Sweep sweepA, B3Sweep sweepB, float maxFraction) {
        return null;
    }

    public static B3PlaneSolverResult SolveMoverPlanes(B3Vec3 targetDelta, B3MoverCollision collision) {
        return null;
    }

    public static B3Vec3 ClipVectorToMoverPlanes(B3Vec3 vector, B3MoverCollision collision) {
        return null;
    }
}
