/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3ContactHitEvent extends NativeObject {

    static public final B3ContactHitEvent NULL = B3ContactHitEvent.native_new();

    public B3ContactHitEvent() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3ContactHitEvent(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3ContactHitEvent native_new() {
        return new B3ContactHitEvent((byte) 0, (char) 0);
    }

    public long GetShapeIdA() {
        return 0;
    }

    public long GetShapeIdB() {
        return 0;
    }

    public B3ContactId GetContactId() {
        return null;
    }

    public B3Vec3 GetPoint() {
        return null;
    }

    public B3Vec3 GetNormal() {
        return null;
    }

    public float GetApproachSpeed() {
        return 0;
    }

    public long GetUserMaterialIdA() {
        return 0;
    }

    public long GetUserMaterialIdB() {
        return 0;
    }
}
