/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3DistanceJointDef extends NativeObject {

    static public final B3DistanceJointDef NULL = B3DistanceJointDef.native_new();

    public B3DistanceJointDef() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3DistanceJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3DistanceJointDef native_new() {
        return new B3DistanceJointDef((byte) 0, (char) 0);
    }

    public long GetBodyIdA() {
        return 0;
    }

    public void SetBodyIdA(long bodyId) {
    }

    public long GetBodyIdB() {
        return 0;
    }

    public void SetBodyIdB(long bodyId) {
    }

    public B3Transform GetLocalFrameA() {
        return null;
    }

    public void SetLocalFrameA(B3Transform transform) {
    }

    public B3Transform GetLocalFrameB() {
        return null;
    }

    public void SetLocalFrameB(B3Transform transform) {
    }

    public void SetLocalPositionA(B3Vec3 position) {
    }

    public void SetLocalPositionB(B3Vec3 position) {
    }

    public float GetDrawScale() {
        return 0;
    }

    public void SetDrawScale(float scale) {
    }

    public boolean GetCollideConnected() {
        return false;
    }

    public void SetCollideConnected(boolean collide) {
    }

    public float GetConstraintHertz() {
        return 0;
    }

    public void SetConstraintHertz(float hertz) {
    }

    public float GetConstraintDampingRatio() {
        return 0;
    }

    public void SetConstraintDampingRatio(float ratio) {
    }

    public float GetLength() {
        return 0;
    }

    public void SetLength(float length) {
    }

    public boolean GetEnableSpring() {
        return false;
    }

    public void SetEnableSpring(boolean enabled) {
    }

    public float GetLowerSpringForce() {
        return 0;
    }

    public void SetLowerSpringForce(float force) {
    }

    public float GetUpperSpringForce() {
        return 0;
    }

    public void SetUpperSpringForce(float force) {
    }

    public float GetHertz() {
        return 0;
    }

    public void SetHertz(float hertz) {
    }

    public float GetDampingRatio() {
        return 0;
    }

    public void SetDampingRatio(float ratio) {
    }

    public boolean GetEnableLimit() {
        return false;
    }

    public void SetEnableLimit(boolean enabled) {
    }

    public float GetMinLength() {
        return 0;
    }

    public void SetMinLength(float length) {
    }

    public float GetMaxLength() {
        return 0;
    }

    public void SetMaxLength(float length) {
    }

    public boolean GetEnableMotor() {
        return false;
    }

    public void SetEnableMotor(boolean enabled) {
    }

    public float GetMaxMotorForce() {
        return 0;
    }

    public void SetMaxMotorForce(float force) {
    }

    public float GetMotorSpeed() {
        return 0;
    }

    public void SetMotorSpeed(float speed) {
    }
}
