/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3Hull extends NativeObject {

    static public final B3Hull NULL = B3Hull.native_new();

    public B3Hull() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Hull(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Hull native_new() {
        return new B3Hull((byte) 0, (char) 0);
    }

    public static B3Hull CreateBox(float hx, float hy, float hz) {
        return null;
    }

    public static B3Hull CreateOffsetBox(float hx, float hy, float hz, B3Vec3 offset) {
        return null;
    }

    public static B3Hull CreateTransformedBox(float hx, float hy, float hz, B3Transform transform) {
        return null;
    }

    public static B3Hull CreateScaledBox(B3Vec3 halfWidths, B3Transform transform, B3Vec3 postScale) {
        return null;
    }

    public static B3Hull CreateCube(float halfWidth) {
        return null;
    }

    public static B3Hull CreateCylinder(float height, float radius, float yOffset, int sides) {
        return null;
    }

    public static B3Hull CreateCone(float height, float radius1, float radius2, int slices) {
        return null;
    }

    public static B3Hull CreateRock(float radius) {
        return null;
    }

    public boolean IsValid() {
        return false;
    }

    public void Destroy() {
    }

    public int GetVertexCount() {
        return 0;
    }

    public int GetFaceCount() {
        return 0;
    }
}
