/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3JointEvents extends NativeObject {

    static public final B3JointEvents NULL = B3JointEvents.native_new();

    public B3JointEvents() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3JointEvents(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3JointEvents native_new() {
        return new B3JointEvents((byte) 0, (char) 0);
    }

    public int GetCount() {
        return 0;
    }

    public B3JointEvent GetEvent(int index) {
        return null;
    }
}
