/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3Joint extends NativeObject {

    static public final B3Joint NULL = B3Joint.native_new();

    public B3Joint() {
    }

    public B3Joint(long jointId) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Joint(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Joint native_new() {
        return new B3Joint((byte) 0, (char) 0);
    }

    public long GetId() {
        return 0;
    }

    public boolean IsValid() {
        return false;
    }

    public void Destroy(boolean wakeAttached) {
    }

    public long GetBodyIdA() {
        return 0;
    }

    public long GetBodyIdB() {
        return 0;
    }

    public void WakeBodies() {
    }

    public float GetLinearSeparation() {
        return 0;
    }

    public void SetRevoluteTargetAngle(float radians) {
    }
}
