/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3MoverCollision extends NativeObject {

    static public final B3MoverCollision NULL = B3MoverCollision.native_new();

    public B3MoverCollision() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3MoverCollision(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3MoverCollision native_new() {
        return new B3MoverCollision((byte) 0, (char) 0);
    }

    public int GetCount() {
        return 0;
    }

    public B3MoverPlaneResult GetResult(int index) {
        return null;
    }
}
