/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3MotorJointDef extends NativeObject {

    static public final B3MotorJointDef NULL = B3MotorJointDef.native_new();

    public B3MotorJointDef() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3MotorJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3MotorJointDef native_new() {
        return new B3MotorJointDef((byte) 0, (char) 0);
    }

    public long GetBodyIdA() {
        return 0;
    }

    public void SetBodyIdA(long bodyId) {
    }

    public long GetBodyIdB() {
        return 0;
    }

    public void SetBodyIdB(long bodyId) {
    }

    public B3Transform GetLocalFrameA() {
        return null;
    }

    public void SetLocalFrameA(B3Transform transform) {
    }

    public B3Transform GetLocalFrameB() {
        return null;
    }

    public void SetLocalFrameB(B3Transform transform) {
    }

    public void SetLocalPositionA(B3Vec3 position) {
    }

    public void SetLocalPositionB(B3Vec3 position) {
    }

    public float GetDrawScale() {
        return 0;
    }

    public void SetDrawScale(float scale) {
    }

    public boolean GetCollideConnected() {
        return false;
    }

    public void SetCollideConnected(boolean collide) {
    }

    public B3Vec3 GetLinearVelocity() {
        return null;
    }

    public void SetLinearVelocity(B3Vec3 velocity) {
    }

    public float GetMaxVelocityForce() {
        return 0;
    }

    public void SetMaxVelocityForce(float force) {
    }

    public B3Vec3 GetAngularVelocity() {
        return null;
    }

    public void SetAngularVelocity(B3Vec3 velocity) {
    }

    public float GetMaxVelocityTorque() {
        return 0;
    }

    public void SetMaxVelocityTorque(float torque) {
    }

    public float GetLinearHertz() {
        return 0;
    }

    public void SetLinearHertz(float hertz) {
    }

    public float GetLinearDampingRatio() {
        return 0;
    }

    public void SetLinearDampingRatio(float ratio) {
    }

    public float GetMaxSpringForce() {
        return 0;
    }

    public void SetMaxSpringForce(float force) {
    }

    public float GetAngularHertz() {
        return 0;
    }

    public void SetAngularHertz(float hertz) {
    }

    public float GetAngularDampingRatio() {
        return 0;
    }

    public void SetAngularDampingRatio(float ratio) {
    }

    public float GetMaxSpringTorque() {
        return 0;
    }

    public void SetMaxSpringTorque(float torque) {
    }
}
