/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3PlaneSolverResult extends NativeObject {

    static public final B3PlaneSolverResult NULL = B3PlaneSolverResult.native_new();

    public B3PlaneSolverResult() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3PlaneSolverResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3PlaneSolverResult native_new() {
        return new B3PlaneSolverResult((byte) 0, (char) 0);
    }

    public B3Vec3 GetDelta() {
        return null;
    }

    public int GetIterationCount() {
        return 0;
    }
}
