/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3RayCastInput extends NativeObject {

    static public final B3RayCastInput NULL = B3RayCastInput.native_new();

    public B3RayCastInput() {
    }

    public B3RayCastInput(B3Vec3 origin, B3Vec3 translation, float maxFraction) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3RayCastInput(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3RayCastInput native_new() {
        return new B3RayCastInput((byte) 0, (char) 0);
    }

    public B3Vec3 GetOrigin() {
        return null;
    }

    public void SetOrigin(B3Vec3 origin) {
    }

    public B3Vec3 GetTranslation() {
        return null;
    }

    public void SetTranslation(B3Vec3 translation) {
    }

    public float GetMaxFraction() {
        return 0;
    }

    public void SetMaxFraction(float fraction) {
    }
}
