/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3RevoluteJointDef extends NativeObject {

    static public final B3RevoluteJointDef NULL = B3RevoluteJointDef.native_new();

    public B3RevoluteJointDef() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3RevoluteJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3RevoluteJointDef native_new() {
        return new B3RevoluteJointDef((byte) 0, (char) 0);
    }

    public long GetBodyIdA() {
        return 0;
    }

    public void SetBodyIdA(long bodyId) {
    }

    public long GetBodyIdB() {
        return 0;
    }

    public void SetBodyIdB(long bodyId) {
    }

    public B3Transform GetLocalFrameA() {
        return null;
    }

    public void SetLocalFrameA(B3Transform transform) {
    }

    public B3Transform GetLocalFrameB() {
        return null;
    }

    public void SetLocalFrameB(B3Transform transform) {
    }

    public void SetLocalPositionA(B3Vec3 position) {
    }

    public void SetLocalPositionB(B3Vec3 position) {
    }

    public float GetDrawScale() {
        return 0;
    }

    public void SetDrawScale(float scale) {
    }

    public boolean GetCollideConnected() {
        return false;
    }

    public void SetCollideConnected(boolean collide) {
    }

    public float GetConstraintHertz() {
        return 0;
    }

    public void SetConstraintHertz(float hertz) {
    }

    public float GetConstraintDampingRatio() {
        return 0;
    }

    public void SetConstraintDampingRatio(float ratio) {
    }

    public float GetTargetAngle() {
        return 0;
    }

    public void SetTargetAngle(float radians) {
    }

    public boolean GetEnableSpring() {
        return false;
    }

    public void SetEnableSpring(boolean enabled) {
    }

    public float GetHertz() {
        return 0;
    }

    public void SetHertz(float hertz) {
    }

    public float GetDampingRatio() {
        return 0;
    }

    public void SetDampingRatio(float ratio) {
    }

    public boolean GetEnableLimit() {
        return false;
    }

    public void SetEnableLimit(boolean enabled) {
    }

    public float GetLowerAngle() {
        return 0;
    }

    public void SetLowerAngle(float radians) {
    }

    public float GetUpperAngle() {
        return 0;
    }

    public void SetUpperAngle(float radians) {
    }

    public boolean GetEnableMotor() {
        return false;
    }

    public void SetEnableMotor(boolean enabled) {
    }

    public float GetMaxMotorTorque() {
        return 0;
    }

    public void SetMaxMotorTorque(float torque) {
    }

    public float GetMotorSpeed() {
        return 0;
    }

    public void SetMotorSpeed(float speed) {
    }
}
