/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3RecPlayer extends NativeObject {

    static public final B3RecPlayer NULL = B3RecPlayer.native_new();

    public B3RecPlayer() {
    }

    public B3RecPlayer(B3ByteArray data, int workerCount) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3RecPlayer(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3RecPlayer native_new() {
        return new B3RecPlayer((byte) 0, (char) 0);
    }

    public boolean IsValid() {
        return false;
    }

    public void Destroy() {
    }

    public boolean StepFrame() {
        return false;
    }

    public void SubStepFrame() {
    }

    public void Restart() {
    }

    public void SeekFrame(int targetFrame) {
    }

    public B3World GetWorld() {
        return null;
    }

    public long GetWorldId() {
        return 0;
    }

    public int GetFrame() {
        return 0;
    }

    public int GetFrameCount() {
        return 0;
    }

    public boolean IsAtEnd() {
        return false;
    }

    public boolean IsAtPreStep() {
        return false;
    }

    public boolean HasDiverged() {
        return false;
    }

    public B3RecPlayerInfo GetInfo() {
        return null;
    }

    public int GetDivergeFrame() {
        return 0;
    }

    public void SetWorkerCount(int count) {
    }

    public void SetKeyframePolicy(long budgetBytes, int minIntervalFrames) {
    }

    public long GetKeyframeBudget() {
        return 0;
    }

    public int GetKeyframeMinInterval() {
        return 0;
    }

    public int GetKeyframeInterval() {
        return 0;
    }

    public long GetKeyframeBytes() {
        return 0;
    }

    public int GetBodyCount() {
        return 0;
    }

    public long GetBodyId(int index) {
        return 0;
    }

    public void SetDebugShapeCallbacks() {
    }

    public void DrawFrameQueries(B3DebugDrawEm draw, int queryIndex, int selectedIndex) {
    }

    public int GetFrameQueryCount() {
        return 0;
    }

    public B3RecQueryInfo GetFrameQuery(int index) {
        return null;
    }

    public B3RecQueryHit GetFrameQueryHit(int queryIndex, int hitIndex) {
        return null;
    }
}
