/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public final class B3SegmentDistanceResult extends NativeObject {

    static public final B3SegmentDistanceResult NULL = B3SegmentDistanceResult.native_new();

    public B3SegmentDistanceResult() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3SegmentDistanceResult(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3SegmentDistanceResult native_new() {
        return new B3SegmentDistanceResult((byte) 0, (char) 0);
    }

    public B3Vec3 GetPoint1() {
        return null;
    }

    public float GetFraction1() {
        return 0;
    }

    public B3Vec3 GetPoint2() {
        return null;
    }

    public float GetFraction2() {
        return 0;
    }
}
