/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3Vec3 extends NativeObject {

    static public final B3Vec3 NULL = B3Vec3.native_new();

    public B3Vec3() {
    }

    public B3Vec3(float x, float y, float z) {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3Vec3(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3Vec3 native_new() {
        return new B3Vec3((byte) 0, (char) 0);
    }

    public float GetX() {
        return 0;
    }

    public float GetY() {
        return 0;
    }

    public float GetZ() {
        return 0;
    }

    public void SetX(float x) {
    }

    public void SetY(float y) {
    }

    public void SetZ(float z) {
    }

    public void Set(float x, float y, float z) {
    }
}
