/*-------------------------------------------------------
 * This file was generated by JParser
 *
 * Do not make changes to this file
 *-------------------------------------------------------*/

package com.github.xpenatan.box3d;

import com.github.xpenatan.jParser.api.NativeObject;

public class B3WheelJointDef extends NativeObject {

    static public final B3WheelJointDef NULL = B3WheelJointDef.native_new();

    public B3WheelJointDef() {
    }

    /**
     * Dummy constructor, used internally to creates objects without C++ pointer
     */
    @Deprecated()
    protected B3WheelJointDef(byte b, char c) {
    }

    /**
     * @return An empty instance without a native address
     */
    public static B3WheelJointDef native_new() {
        return new B3WheelJointDef((byte) 0, (char) 0);
    }

    public long GetBodyIdA() {
        return 0;
    }

    public void SetBodyIdA(long bodyId) {
    }

    public long GetBodyIdB() {
        return 0;
    }

    public void SetBodyIdB(long bodyId) {
    }

    public B3Transform GetLocalFrameA() {
        return null;
    }

    public void SetLocalFrameA(B3Transform transform) {
    }

    public B3Transform GetLocalFrameB() {
        return null;
    }

    public void SetLocalFrameB(B3Transform transform) {
    }

    public void SetLocalPositionA(B3Vec3 position) {
    }

    public void SetLocalPositionB(B3Vec3 position) {
    }

    public float GetDrawScale() {
        return 0;
    }

    public void SetDrawScale(float scale) {
    }

    public boolean GetCollideConnected() {
        return false;
    }

    public void SetCollideConnected(boolean collide) {
    }

    public boolean GetEnableSuspensionSpring() {
        return false;
    }

    public void SetEnableSuspensionSpring(boolean enabled) {
    }

    public float GetSuspensionHertz() {
        return 0;
    }

    public void SetSuspensionHertz(float hertz) {
    }

    public float GetSuspensionDampingRatio() {
        return 0;
    }

    public void SetSuspensionDampingRatio(float ratio) {
    }

    public boolean GetEnableSuspensionLimit() {
        return false;
    }

    public void SetEnableSuspensionLimit(boolean enabled) {
    }

    public float GetLowerSuspensionLimit() {
        return 0;
    }

    public void SetLowerSuspensionLimit(float limit) {
    }

    public float GetUpperSuspensionLimit() {
        return 0;
    }

    public void SetUpperSuspensionLimit(float limit) {
    }

    public boolean GetEnableSpinMotor() {
        return false;
    }

    public void SetEnableSpinMotor(boolean enabled) {
    }

    public float GetMaxSpinTorque() {
        return 0;
    }

    public void SetMaxSpinTorque(float torque) {
    }

    public float GetSpinSpeed() {
        return 0;
    }

    public void SetSpinSpeed(float speed) {
    }

    public boolean GetEnableSteering() {
        return false;
    }

    public void SetEnableSteering(boolean enabled) {
    }

    public float GetSteeringHertz() {
        return 0;
    }

    public void SetSteeringHertz(float hertz) {
    }

    public float GetSteeringDampingRatio() {
        return 0;
    }

    public void SetSteeringDampingRatio(float ratio) {
    }

    public float GetTargetSteeringAngle() {
        return 0;
    }

    public void SetTargetSteeringAngle(float radians) {
    }

    public float GetMaxSteeringTorque() {
        return 0;
    }

    public void SetMaxSteeringTorque(float torque) {
    }

    public boolean GetEnableSteeringLimit() {
        return false;
    }

    public void SetEnableSteeringLimit(boolean enabled) {
    }

    public float GetLowerSteeringLimit() {
        return 0;
    }

    public void SetLowerSteeringLimit(float radians) {
    }

    public float GetUpperSteeringLimit() {
        return 0;
    }

    public void SetUpperSteeringLimit(float radians) {
    }
}
